// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity_betting.sql

package db

import (
	"context"
	"time"
)

const betsByIDs = `-- name: BetsByIDs :many
SELECT id, public_id, tournament_id, user_id, stake, potential_payout, status, ledger_stake_entry_id, ledger_refund_entry_id, payout_recalculated, settled_at, created_at, ledger_payout_entry_id FROM activity.bets
WHERE id = ANY($1::bigint[])
ORDER BY id
`

// 讀注單本體(不含腿)。呼叫前必須已 LockBetsForSettle —— 判定與派彩依賴的是
// **鎖之後**的狀態,鎖之前讀到的 status 可能是另一個 tx 正要改掉的舊快照。
//
// ORDER BY id 與取鎖順序一致,結算結果才可重現。
func (q *Queries) BetsByIDs(ctx context.Context, betIds []int64) ([]ActivityBet, error) {
	rows, err := q.db.Query(ctx, betsByIDs, betIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityBet
	for rows.Next() {
		var i ActivityBet
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TournamentID,
			&i.UserID,
			&i.Stake,
			&i.PotentialPayout,
			&i.Status,
			&i.LedgerStakeEntryID,
			&i.LedgerRefundEntryID,
			&i.PayoutRecalculated,
			&i.SettledAt,
			&i.CreatedAt,
			&i.LedgerPayoutEntryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const betsByUser = `-- name: BetsByUser :many

SELECT id, public_id, tournament_id, user_id, stake, potential_payout, status, ledger_stake_entry_id, ledger_refund_entry_id, payout_recalculated, settled_at, created_at, ledger_payout_entry_id FROM activity.bets
WHERE tournament_id = $1 AND user_id = $2
ORDER BY created_at DESC, id DESC
`

type BetsByUserParams struct {
	TournamentID int64
	UserID       int64
}

// ══ 列出自己的注單 ══════════════════════════════════════════════
// 某人在某屆的全部注單,新到舊。腿由 LegsByBetIDs 補齊(一次查詢,不是逐張回查)。
//
// id DESC 收尾:created_at 不唯一,同一次連點會落在同一個微秒,
// 沒有第二個排序鍵時清單順序會隨執行計畫變動,使用者每次重整看到的順序都不一樣。
// 走 bets_user_created_idx (user_id, created_at DESC)。
func (q *Queries) BetsByUser(ctx context.Context, arg BetsByUserParams) ([]ActivityBet, error) {
	rows, err := q.db.Query(ctx, betsByUser, arg.TournamentID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityBet
	for rows.Next() {
		var i ActivityBet
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TournamentID,
			&i.UserID,
			&i.Stake,
			&i.PotentialPayout,
			&i.Status,
			&i.LedgerStakeEntryID,
			&i.LedgerRefundEntryID,
			&i.PayoutRecalculated,
			&i.SettledAt,
			&i.CreatedAt,
			&i.LedgerPayoutEntryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bettingMatchesByPublicIDs = `-- name: BettingMatchesByPublicIDs :many
SELECT
  m.id, m.public_id, m.tournament_id, m.round, m.slot, m.status, m.result_kind,
  COALESCE(m.winner_player_id, 0)::bigint AS winner_player_id,
  COALESCE(p1.id, 0)::bigint             AS p1_player_id,
  COALESCE(p1.display_name, '')::text    AS p1_display_name,
  COALESCE(p1.user_id, 0)::bigint        AS p1_player_user_id,
  COALESCE(f1.user_id, 0)::bigint        AS p1_fencer_user_id,
  COALESCE(p2.id, 0)::bigint             AS p2_player_id,
  COALESCE(p2.display_name, '')::text    AS p2_display_name,
  COALESCE(p2.user_id, 0)::bigint        AS p2_player_user_id,
  COALESCE(f2.user_id, 0)::bigint        AS p2_fencer_user_id
FROM activity.matches m
LEFT JOIN activity.tournament_players p1 ON p1.id = m.p1_player_id
LEFT JOIN activity.fencers f1            ON f1.id = p1.fencer_id
LEFT JOIN activity.tournament_players p2 ON p2.id = m.p2_player_id
LEFT JOIN activity.fencers f2            ON f2.id = p2.fencer_id
WHERE m.public_id = ANY($1::text[])
`

type BettingMatchesByPublicIDsRow struct {
	ID             int64
	PublicID       string
	TournamentID   int64
	Round          int32
	Slot           int32
	Status         string
	ResultKind     string
	WinnerPlayerID int64
	P1PlayerID     int64
	P1DisplayName  string
	P1PlayerUserID int64
	P1FencerUserID int64
	P2PlayerID     int64
	P2DisplayName  string
	P2PlayerUserID int64
	P2FencerUserID int64
}

// 批次讀場次,順序不拘(呼叫端自己用 public_id 索引)。
//
// **兩組 user_id 都要撈**,這是「選手不得對自己參與的場次下注」的兩條比對路徑:
//
//	tournament_players.user_id  有綁帳號報名的選手
//	fencers.user_id             純活動報名(tournament_players.user_id IS NULL)、
//	                            但劍士本人曾經綁過平台帳號
//
// 只比對前者,一個沒綁帳號報名的選手就能用自己的平台帳號賭自己輸 —— 漏掉 fencers
// 那條等於整個檢查形同虛設。兩者都沒綁時擋不住,那是雙軌身分的固有代價。
//
// p1/p2 走 LEFT JOIN(對手未定時為 NULL),所以 fencers 也只能 LEFT JOIN。
// NULL 一律 COALESCE 成 0:0 不是合法的 id,而 betting.Participant.IsUser 對 0 恆回 false
// ——「兩邊都沒綁帳號」絕不能被當成「所有人都是這位選手」。
func (q *Queries) BettingMatchesByPublicIDs(ctx context.Context, publicIds []string) ([]BettingMatchesByPublicIDsRow, error) {
	rows, err := q.db.Query(ctx, bettingMatchesByPublicIDs, publicIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BettingMatchesByPublicIDsRow
	for rows.Next() {
		var i BettingMatchesByPublicIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TournamentID,
			&i.Round,
			&i.Slot,
			&i.Status,
			&i.ResultKind,
			&i.WinnerPlayerID,
			&i.P1PlayerID,
			&i.P1DisplayName,
			&i.P1PlayerUserID,
			&i.P1FencerUserID,
			&i.P2PlayerID,
			&i.P2DisplayName,
			&i.P2PlayerUserID,
			&i.P2FencerUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bettingOddsConfig = `-- name: BettingOddsConfig :one
SELECT
  COALESCE(substring(t.config -> 'odds' ->> 'smoothing'        FROM '^-?[0-9]{1,18}$'), '0')::bigint AS smoothing_votes,
  COALESCE(substring(t.config -> 'odds' ->> 'vig_bps'          FROM '^-?[0-9]{1,18}$'), '0')::bigint AS vig_bps,
  COALESCE(substring(t.config -> 'odds' ->> 'min_odds_milli'   FROM '^-?[0-9]{1,18}$'), '0')::bigint AS min_odds_milli,
  COALESCE(substring(t.config -> 'odds' ->> 'max_odds_milli'   FROM '^-?[0-9]{1,18}$'), '0')::bigint AS max_odds_milli,
  COALESCE(substring(t.config -> 'odds' ->> 'max_parlay_milli' FROM '^-?[0-9]{1,18}$'), '0')::bigint AS max_parlay_milli,
  -- max_stake 的權威在 **platform.economy_configs**,不在 tournaments.config。
  --
  -- 單注上限是平台層的風險控制,不是逐屆的玩法旋鈕 —— schemas/21 就是這樣訂的
  -- (「MAX_STAKE=500(platform 的 max_stake)」)。兩邊都放會漂移,而漂移的症狀是
  -- 「同一顆按鈕在不同賽事有不同上限,而沒有人說得出為什麼」。
  --
  -- 取法與 config.sql 的 GetCurrentConfig 一致:同一個 key 不覆寫舊值,取生效時間最新的一筆。
  COALESCE((
    -- value 是 JSONB 不是 TEXT。substring(jsonb, unknown) 不存在,直接用會 42883,
    -- 而每條下注路徑都先讀這裡 —— 整個下注功能會死在這一行。
    -- 用 #>> '{}' 取裸值而不是 ::text:seed 的 '500' 是 JSON 數字,
    -- 但裁判可能手打成 "500" JSON 字串,::text 會把引號一起帶出來而落回預設值。
    SELECT substring(ec.value #>> '{}' FROM '^-?[0-9]{1,18}$')
    FROM platform.economy_configs ec
    WHERE ec.key = 'max_stake' AND ec.effective_at <= now()
    ORDER BY ec.effective_at DESC
    LIMIT 1
  ), '0')::bigint AS max_stake
FROM activity.tournaments t
WHERE t.id = $1
`

type BettingOddsConfigRow struct {
	SmoothingVotes int64
	VigBps         int64
	MinOddsMilli   int64
	MaxOddsMilli   int64
	MaxParlayMilli int64
	MaxStake       int64
}

// 賠率參數。tournaments.config 是逐屆規則的唯一權威(同 bp_per_rank_gap 的取法),
// 這裡只負責「把 JSONB 取成整數」,預設值一律不寫在 SQL 裡 ——
// 權威在 betting.OddsConfig.Normalize(),缺值回 0 由它補,兩邊各寫一份就會漂移。
//
// substring(... FROM '^-?[0-9]{1,18}$') 是必要的護欄,不是潔癖:
//   - config 是裁判手打進 JSONB 的,'2.5' 或 'abc' 都可能出現,
//     直接 ::bigint 會讓整個下注頁變成 SQLSTATE 22P02(白畫面,沒有人看得出原因);
//     取不到合法整數字面值就回 NULL → COALESCE 0 → Normalize 退回預設值,賽事照常開。
//   - 18 位上限保證轉得進 BIGINT,不會在 cast 時溢位。
//   - 只收純整數字面值,所以這條路徑上不存在任何 float / numeric 運算。
//
// payout_tolerance_bps 刻意不讀:它不是 schemas/21 訂的設定鍵,
// 也不在 tournament.ParseConfig 認得的欄位裡。在這裡自行發明一個鍵,
// 等於讓「config 有哪些鍵」多出第二個權威。零值 → Normalize 補 2%。
func (q *Queries) BettingOddsConfig(ctx context.Context, tournamentID int64) (BettingOddsConfigRow, error) {
	row := q.db.QueryRow(ctx, bettingOddsConfig, tournamentID)
	var i BettingOddsConfigRow
	err := row.Scan(
		&i.SmoothingVotes,
		&i.VigBps,
		&i.MinOddsMilli,
		&i.MaxOddsMilli,
		&i.MaxParlayMilli,
		&i.MaxStake,
	)
	return i, err
}

const bettingTournamentBySlug = `-- name: BettingTournamentBySlug :one

SELECT id, slug FROM activity.tournaments
WHERE slug = $1
`

type BettingTournamentBySlugRow struct {
	ID   int64
	Slug string
}

// ══ 賽事與場次 ══════════════════════════════════════════════════
// 下注一律以 slug 定位賽事(對外不出現內部 id)。查無列 = 呼叫端的 ErrTournamentNotFound。
func (q *Queries) BettingTournamentBySlug(ctx context.Context, slug string) (BettingTournamentBySlugRow, error) {
	row := q.db.QueryRow(ctx, bettingTournamentBySlug, slug)
	var i BettingTournamentBySlugRow
	err := row.Scan(&i.ID, &i.Slug)
	return i, err
}

const insertBet = `-- name: InsertBet :one

INSERT INTO activity.bets (public_id, tournament_id, user_id, stake, potential_payout)
VALUES (
  $1, $2, $3,
  $4, $5
)
RETURNING id, created_at
`

type InsertBetParams struct {
	PublicID        string
	TournamentID    int64
	UserID          int64
	Stake           int64
	PotentialPayout int64
}

type InsertBetRow struct {
	ID        int64
	CreatedAt time.Time
}

// ══ 下注 ════════════════════════════════════════════════════════
// 建注單。扣款分錄 id 此時還不存在(分錄的 ref_id 要指向注單、注單要指向分錄,
// 兩邊的 id 不可能同時先有),由 SetBetStakeEntry 在同一個 tx 內補上。
//
// created_at 由資料庫給並回傳:core 不該有第二個時鐘,注單的時間與帳本分錄的時間
// 必須出自同一個來源,否則對帳時會出現「分錄比注單早」這種查不出原因的排序。
func (q *Queries) InsertBet(ctx context.Context, arg InsertBetParams) (InsertBetRow, error) {
	row := q.db.QueryRow(ctx, insertBet,
		arg.PublicID,
		arg.TournamentID,
		arg.UserID,
		arg.Stake,
		arg.PotentialPayout,
	)
	var i InsertBetRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const insertBetLegs = `-- name: InsertBetLegs :execrows
INSERT INTO activity.bet_legs (bet_id, match_id, side, odds_milli)
SELECT $1, v.match_id, v.side, v.odds_milli
FROM (
  SELECT
    unnest($2::bigint[])  AS match_id,
    unnest($3::smallint[])    AS side,
    unnest($4::bigint[]) AS odds_milli
) AS v
`

type InsertBetLegsParams struct {
	BetID     int64
	MatchIds  []int64
	Sides     []int16
	OddsMilli []int64
}

// 一次寫入整張注單的腿。
//
// unnest 批次而不是迴圈單筆(同 InsertHandicapItems 的理由):一次往返、同一個敘述,
// 中途失敗不會留下半張串關 —— 半張串關比整張失敗糟得多,因為本金已經照全部的腿算過了。
//
// 三個陣列長度不一致時,unnest 會把短的補 NULL 而撞上 NOT NULL,當場失敗。
// 這正是要的:賠率陣列少一格代表呼叫端有 bug,默默插進去的會是一張賠率不對的注單。
//
// bet_legs_bet_match_uq (bet_id, match_id) 是「同一注單不可重複押同一場」的兜底
// (押完 p1 再押 p2 等於穩賺)。這裡刻意**沒有** ON CONFLICT:撞鍵要讓 23505 冒上來,
// 而不是靜靜少插一腿 —— 少一腿的注單會用多一腿算出來的賠付派彩。
//
// :execrows 讓 adapter 核對「插進去的列數 = 腿數」,這是上面那句的另一半保險。
func (q *Queries) InsertBetLegs(ctx context.Context, arg InsertBetLegsParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertBetLegs,
		arg.BetID,
		arg.MatchIds,
		arg.Sides,
		arg.OddsMilli,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const legsByBetIDs = `-- name: LegsByBetIDs :many
SELECT
  l.id, l.bet_id, l.match_id, l.side, l.odds_milli, l.result,
  m.public_id AS match_public_id,
  m.round,
  m.slot,
  COALESCE(CASE l.side WHEN 1 THEN p1.display_name WHEN 2 THEN p2.display_name END, '')::text
    AS side_display_name
FROM activity.bet_legs l
JOIN activity.matches m                  ON m.id = l.match_id
LEFT JOIN activity.tournament_players p1 ON p1.id = m.p1_player_id
LEFT JOIN activity.tournament_players p2 ON p2.id = m.p2_player_id
WHERE l.bet_id = ANY($1::bigint[])
ORDER BY l.bet_id, l.id
`

type LegsByBetIDsRow struct {
	ID              int64
	BetID           int64
	MatchID         int64
	Side            int16
	OddsMilli       int64
	Result          string
	MatchPublicID   string
	Round           int32
	Slot            int32
	SideDisplayName string
}

// 讀這些注單的**全部**腿(含已判定的)。
//
// 為什麼不能只讀 pending:注單的狀態是所有腿的合成(全 won 才 won、任一 lost 即 lost、
// 全 void 才 void),只看這一場的腿會把串關的另一腿當成不存在,一張還在等的注單
// 會被判成全贏。
//
// 一併 join 出展示欄位(match_public_id / round / slot / 該方的顯示名):
// ListMyBets 與結算共用這一支,結算路徑用不到那幾欄但也不吃虧(同一批列已經在手上),
// 分成兩支查詢才是重複。對外只出現 public_id,內部 id 不會離開伺服器。
func (q *Queries) LegsByBetIDs(ctx context.Context, betIds []int64) ([]LegsByBetIDsRow, error) {
	rows, err := q.db.Query(ctx, legsByBetIDs, betIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LegsByBetIDsRow
	for rows.Next() {
		var i LegsByBetIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.BetID,
			&i.MatchID,
			&i.Side,
			&i.OddsMilli,
			&i.Result,
			&i.MatchPublicID,
			&i.Round,
			&i.Slot,
			&i.SideDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBetsForSettle = `-- name: LockBetsForSettle :exec
SELECT id FROM activity.bets
WHERE id = ANY($1::bigint[])
ORDER BY id
FOR UPDATE
`

// 依 id **升冪**鎖住這些注單列。
//
// 為什麼還要這把鎖:advisory lock 只擋得住「同一場被結算兩次」。一張串關的兩腿
// 分屬 A、B 兩場時,A 與 B 同時結算會各自持有**不同**的 advisory lock,誰也擋不住誰,
// 兩邊都看不到對方剛標好的腿,於是兩邊都判定「還有 pending」——
// 結果是一張全贏的注單永遠停在 open,使用者的錢就這樣卡住。
// 注單列鎖讓第二個 tx 等到第一個 commit 之後才重讀腿,那時它看得到另一腿已經 won。
//
// 升冪是全域的防死鎖慣例(與 user_id 升冪同一條規則):兩場比賽的結算若以相反順序
// 鎖同兩張注單就是死鎖。呼叫端已排好序,這裡的 ORDER BY 是 DB 側的保證 ——
// LockRows 節點在 Sort 之上,鎖就是照輸出順序取的,不會因為選到 bitmap scan 而亂序。
//
// :exec 是刻意的:回傳的 id 沒有用處(呼叫端接著會用 BetsByIDs 重讀完整注單),
// 這一句存在的唯一目的就是取鎖。
func (q *Queries) LockBetsForSettle(ctx context.Context, betIds []int64) error {
	_, err := q.db.Exec(ctx, lockBetsForSettle, betIds)
	return err
}

const lockMatchForSettle = `-- name: LockMatchForSettle :exec
SELECT pg_advisory_xact_lock(hashtext('match_settle'), ($1::bigint)::int)
`

// 同一場比賽的結算/退款互斥(ledger-invariants 第四條指定的形式)。
//
// 為什麼是 advisory 而不是 matches 的列鎖:結算不修改 matches(勝負是賽事服務寫的),
// 為了互斥去鎖一列沒有要改的資料,會跟「判定勝負」那條路徑的寫入鎖互相糾纏。
// advisory lock 是純粹的互斥語意,且隨 tx 結束自動釋放 —— 不需要也不該手動解鎖。
//
// 型別:hashtext() 回 int4,所以走 pg_advisory_xact_lock(int4, int4) 這個簽名,
// 兩個參數的型別都對得上,namespace 與 match_id 各佔一半、互不干擾。
// 單參數的 (int8) 版本得自己把 namespace 與 id 塞進同一個 64 bit 整數,
// match_id 一樣只剩 32 bit 可用,卻多一層位移運算 —— 沒有換到任何東西。
//
// ::int 的範圍檢查是刻意的:match_id 真的超過 2^31 時會拋 22003 當場失敗,
// 而不是悄悄截斷成別場的 key、讓兩場比賽共用同一把鎖(或更糟:漏鎖)。
// 參數先宣告成 bigint 再收成 int,是為了讓生成的 Go 參數是 int64,與埠的簽名一致。
func (q *Queries) LockMatchForSettle(ctx context.Context, matchID int64) error {
	_, err := q.db.Exec(ctx, lockMatchForSettle, matchID)
	return err
}

const lockUserForBet = `-- name: LockUserForBet :one


SELECT id FROM platform.users
WHERE id = $1 AND deleted_at IS NULL
FOR UPDATE
`

// 觀眾投票與下注 query(schemas/21-activity-betting.md,migrations/activity/00003 + 00005)。
// 呼叫端是 internal/core/activity/betting 的 Repository[TX] 埠,每一支都在該埠的 tx 裡跑。
//
// ── 這裡全部是真錢 ──────────────────────────────────────────────
//
// 動錢一律經 Ledger(bettingpg 用 ApplyInTx 把帳本寫入掛進同一個 tx),所以本檔
// **沒有、也不該有**任何碰 platform.token_entries / platform.user_balances 的敘述。
// 注單側只存分錄 id(ledger_stake/refund/payout_entry_id),那是稽核鏈的一半,
// 不是餘額的第二個權威。
//
// 賠率與金額全程整數:odds_milli 是賠率 ×1000(BIGINT)、vig_bps 是萬分之一。
// 本檔沒有一個 float / numeric 運算 —— 誤差會被串關連乘放大進派彩金額,
// 而派彩是真錢(ledger-invariants 第七條的直接延伸)。
//
// ── 沿用既有 query,不重寫(專案規則 9)──────────────────────
//
//	冪等鍵  ledger.sql 的 GetIdempotencyKey / InsertIdempotencyKey / SetIdempotencyResponse
//	        → 對應埠的 GetIdempotency / InsertIdempotency / SaveIdempotencyResponse。
//	        platform.idempotency_keys 是全系統唯一的冪等鍵表,活動層不另開一張。
//	outbox  ledger.sql 的 InsertOutboxEvent → 對應埠的 AppendEvents(adapter 逐筆呼叫,
//	        與 reaper.sql 同一個做法)。領域變更與事件同 tx 由呼叫端的 InTx 保證。
//
// ── 命名 ────────────────────────────────────────────────────────
//
// 生成的 db package 與 platform 的查詢同居一個命名空間(同 activity_handicap.sql 的理由),
// 所以泛用名一律加 Betting / Bet / Vote 前綴,避免與日後的 tournament.sql 撞名。
//
// ── 鎖序 ────────────────────────────────────────────────────────
//
//	platform.users(LockUserForBet)
//	  → activity.matches 的 advisory lock(LockMatchForSettle)
//	  → activity.bets 列鎖(LockBetsForSettle,**id 升冪**)
//	  → platform.user_balances(由 Ledger 取,user_id 升冪)
//
// 與 shoppg / marketpg / dailypg 同向(users 先、balances 最後),
// 所以下注與購買/成交/簽到之間結構上不可能互鎖。
// ══ 鎖 ══════════════════════════════════════════════════════════
// 同一使用者的下注以 users 列鎖串行化。
//
// 為什麼非鎖不可:下注沒有任何 UNIQUE 約束擋得住連點(同一人對同一場下兩注是合法的),
// 冪等鍵是唯一權威 —— 而 READ COMMITTED 下「先查鍵再插鍵」的兩個併發請求會同時
// 查不到鍵、同時往下走,兩邊各扣一次款。這把鎖讓第二個請求等到第一個 commit 之後
// 才做重放判定,那時它看得到鍵與上一次的 response。
//
// deleted_at IS NULL 一併驗:軟刪除的帳號不該還能下注,而且查無列時呼叫端直接失敗,
// 不必再多一次往返。
//
// SQL 與 shop.sql 的 LockUserForShop / market.sql 的 LockUserForTrade 同形 ——
// 鎖的是同一列。四支同形 query 是既有慣例的延續(各自的註解說明各自的序列化理由),
// 收斂成單一 LockUserRow 要一次改動四個 feature,不在本檔範圍。
func (q *Queries) LockUserForBet(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockUserForBet, userID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const myVotesByMatch = `-- name: MyVotesByMatch :many
SELECT match_id, side FROM activity.votes
WHERE user_id = $1
  AND match_id = ANY($2::bigint[])
`

type MyVotesByMatchParams struct {
	UserID   int64
	MatchIds []int64
}

type MyVotesByMatchRow struct {
	MatchID int64
	Side    int16
}

// **只查請求者自己的票。** user_id 是必填參數,不是可選過濾條件 ——
// 沒有它就變成「列出這些場次的所有投票」,那正是 VoteTalliesByMatch 註解裡
// 不能存在的那支查詢。要看別人投給誰,這裡沒有路。
func (q *Queries) MyVotesByMatch(ctx context.Context, arg MyVotesByMatchParams) ([]MyVotesByMatchRow, error) {
	rows, err := q.db.Query(ctx, myVotesByMatch, arg.UserID, arg.MatchIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MyVotesByMatchRow
	for rows.Next() {
		var i MyVotesByMatchRow
		if err := rows.Scan(&i.MatchID, &i.Side); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notifyWatchOdds = `-- name: NotifyWatchOdds :exec

SELECT pg_notify(
  $1::text,
  json_build_object('t', t.slug, 'k', $2::text, 'r', m.public_id)::text
)
FROM activity.matches m
JOIN activity.tournaments t ON t.id = m.tournament_id
WHERE m.id = $3
`

type NotifyWatchOddsParams struct {
	Channel string
	Kind    string
	MatchID int64
}

// ══ 即時戰況推播 ════════════════════════════════════════════════
// 投票改變了賠率,通知即時戰況的訂閱者(internal/core/activity/watch)。
//
// 為什麼投票要有自己的一支,而不是沿用 activity_match.sql 的 NotifyActivityWatch:
// 那一支收的是組好的信封字串,而投票路徑手上**只有 matches.id** ——
// UpsertVote 的參數就只有 (match_id, user_id, side)。要在 Go 裡組信封就得先查
// 一次 slug 與 public_id,那是**每一票**都要付的一次額外往返,只為了換一個
// 字串拼接的位置。所以這裡直接在同一句 SQL 裡把信封組好。
//
// 代價是信封的三個鍵名在這裡有一份鏡像(權威是 watch.Envelope 的 json tag)。
// 鍵名對不上的話推播會靜靜失效,所以 watchpg 的整合測試直接解析這一句送出的
// 信封並與 Go 的型別比對 —— 有一邊被改到,測試就會紅。
// 種類(k)與頻道名仍然由呼叫端從 Go 常數帶進來,不在 SQL 裡寫死。
//
// 查無此場次時 FROM 沒有列,自然不送通知 —— 那正是想要的行為。
// 同一個交易裡對同一場投兩次票只會送一則:Postgres 會把 (channel, payload)
// 完全相同的通知去重,而投票的信封不含票數,內容天生相同。
func (q *Queries) NotifyWatchOdds(ctx context.Context, arg NotifyWatchOddsParams) error {
	_, err := q.db.Exec(ctx, notifyWatchOdds, arg.Channel, arg.Kind, arg.MatchID)
	return err
}

const openBetsByUser = `-- name: OpenBetsByUser :many
SELECT id, public_id, tournament_id, user_id, stake, potential_payout, status, ledger_stake_entry_id, ledger_refund_entry_id, payout_recalculated, settled_at, created_at, ledger_payout_entry_id FROM activity.bets
WHERE tournament_id = $1 AND user_id = $2
  AND status = 'open'
ORDER BY created_at DESC, id DESC
`

type OpenBetsByUserParams struct {
	TournamentID int64
	UserID       int64
}

// 同上,只列未結算的。
//
// 分成獨立一支而不是在 BetsByUser 加一個 open_only 布林參數,是為了 bets_open_idx ——
// 那是 WHERE status = 'open' 的部分索引,只有把述詞寫成字面值,planner 才用得上它。
// 寫成 (NOT $3 OR status = 'open') 的話,prepared statement 的通用計畫看不到布林的值,
// 永遠只能退回全表過濾,而已結算的注單會愈積愈多。
func (q *Queries) OpenBetsByUser(ctx context.Context, arg OpenBetsByUserParams) ([]ActivityBet, error) {
	rows, err := q.db.Query(ctx, openBetsByUser, arg.TournamentID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityBet
	for rows.Next() {
		var i ActivityBet
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TournamentID,
			&i.UserID,
			&i.Stake,
			&i.PotentialPayout,
			&i.Status,
			&i.LedgerStakeEntryID,
			&i.LedgerRefundEntryID,
			&i.PayoutRecalculated,
			&i.SettledAt,
			&i.CreatedAt,
			&i.LedgerPayoutEntryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingLegsByMatch = `-- name: PendingLegsByMatch :many

SELECT id, bet_id, match_id, side, odds_milli, result FROM activity.bet_legs
WHERE match_id = $1 AND result = 'pending'
ORDER BY bet_id, id
`

// ══ 結算 ════════════════════════════════════════════════════════
// 撈出押到這場、還沒判定的腿。
//
// result = 'pending' 寫成字面值(而不是參數)是為了對上 bet_legs_match_result_idx
// 的部分索引述詞 WHERE result = 'pending' —— 已判定的腿會愈積愈多,
// 走不到那條索引的話每次結算都得掃整張表。
//
// ORDER BY bet_id, id:呼叫端要據此推出「要鎖哪些注單」,順序不穩定的話
// 同一批資料在不同執行計畫下會得到不同的取鎖順序,而取鎖順序是防死鎖的全部。
func (q *Queries) PendingLegsByMatch(ctx context.Context, matchID int64) ([]ActivityBetLeg, error) {
	rows, err := q.db.Query(ctx, pendingLegsByMatch, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityBetLeg
	for rows.Next() {
		var i ActivityBetLeg
		if err := rows.Scan(
			&i.ID,
			&i.BetID,
			&i.MatchID,
			&i.Side,
			&i.OddsMilli,
			&i.Result,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBetStakeEntry = `-- name: SetBetStakeEntry :execrows
UPDATE activity.bets
SET ledger_stake_entry_id = $1::bigint
WHERE id = $2 AND ledger_stake_entry_id IS NULL
`

type SetBetStakeEntryParams struct {
	EntryID int64
	BetID   int64
}

// 補上扣款分錄 id,完成稽核鏈的另一半(注單 ↔ 帳本雙向可查)。
//
// AND ledger_stake_entry_id IS NULL 是**不可覆寫**的 DB 側保證:分錄 id 一旦寫下就是
// 歷史的一部分,改掉它等於讓一筆扣款從帳本上「換了一張注單」。同 tx 內剛建的注單
// 必定是 NULL,所以影響 0 列代表狀態矛盾(ErrLedgerStateConflict),不是可以忽略的巧合。
//
// ::bigint 明寫是為了讓生成的參數是 int64 而不是 *int64:欄位可為 NULL,但這支
// 查詢的參數不可以 —— 「補上分錄 id」傳 NULL 是沒有意義的呼叫,不該在型別上存在。
func (q *Queries) SetBetStakeEntry(ctx context.Context, arg SetBetStakeEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, setBetStakeEntry, arg.EntryID, arg.BetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateBet = `-- name: UpdateBet :execrows
UPDATE activity.bets
SET status = $1::text,
    potential_payout = COALESCE($2::bigint, potential_payout),
    payout_recalculated = payout_recalculated OR ($2::bigint IS NOT NULL),
    ledger_refund_entry_id = COALESCE($3::bigint, ledger_refund_entry_id),
    ledger_payout_entry_id = COALESCE($4::bigint, ledger_payout_entry_id),
    settled_at = CASE WHEN $1::text = 'open' THEN NULL ELSE now() END
WHERE id = $5 AND status = 'open'
`

type UpdateBetParams struct {
	Status          string
	PotentialPayout *int64
	RefundEntryID   *int64
	PayoutEntryID   *int64
	BetID           int64
}

// 套用結算/退款結果。
//
// AND status = 'open' 是**不重複派彩**的 DB 側權威:service 已經跳過非 open 的注單,
// 但那個判斷與這次寫入之間隔著整條結算流程,而中間動的是錢。影響 0 列 = 這張注單
// 已經被別人結算過,adapter 據此失敗出聲,不要回成功但錢不對。
//
// settled_at 不由呼叫端傳:bets_settled_at_check 要求 (status='open') = (settled_at IS NULL),
// 所以時間只能由 status 推出來 —— 留在 open(串關還有其他場次沒打)就維持 NULL,
// 離開 open 就用 DB 時鐘。core 不該有第二個時鐘。
//
// potential_payout 非 NULL = 有腿因棄賽 void 而重算過,此時 payout_recalculated
// **必須**同時為 true:對帳時要看得出「這筆金額為什麼跟原始承諾不同」。
// 兩者綁在同一句裡設定,就沒有「只更新金額忘了設旗標」的寫法存在。
// 用 OR 而不是直接賦值,是因為旗標一旦為真就永遠為真(第二腿棄賽不會把它洗回 false)。
//
// 三個 ledger_*_entry_id 一律 COALESCE 保留舊值:每張注單最多派彩一次、退款一次,
// 傳 NULL 代表「這次不是這種金流」,不是「清掉那筆稽核紀錄」。
func (q *Queries) UpdateBet(ctx context.Context, arg UpdateBetParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBet,
		arg.Status,
		arg.PotentialPayout,
		arg.RefundEntryID,
		arg.PayoutEntryID,
		arg.BetID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateLegResults = `-- name: UpdateLegResults :execrows
UPDATE activity.bet_legs
SET result = $1
WHERE id = ANY($2::bigint[]) AND result = 'pending'
`

type UpdateLegResultsParams struct {
	Result string
	LegIds []int64
}

// 把指定的腿標成同一個結果(won / lost / void)。
//
// AND result = 'pending' 是重跑保護:已判定的腿不可再被改寫。少了它,
// 對同一場重複呼叫結算會把 won 的腿刷成別的值,而注單的派彩早就依 won 發出去了 ——
// 那是帳本對不上的起點。影響列數回給 adapter 核對。
//
// leg_ids 為空陣列時 WHERE id = ANY('{}') 不匹配任何列,自然是 0 列、不做事,
// 呼叫端不需要額外判斷(埠的「legIDs 為空時不做事」就是這個行為)。
func (q *Queries) UpdateLegResults(ctx context.Context, arg UpdateLegResultsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateLegResults, arg.Result, arg.LegIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertVote = `-- name: UpsertVote :exec
INSERT INTO activity.votes (match_id, user_id, side)
VALUES ($1, $2, $3::smallint)
ON CONFLICT (match_id, user_id) DO UPDATE
SET side = EXCLUDED.side, updated_at = now()
`

type UpsertVoteParams struct {
	MatchID int64
	UserID  int64
	Side    int16
}

// 一場一票,改票即覆寫。
//
// 權威是 votes_match_user_uq (match_id, user_id) 這條 UNIQUE,不是應用層的
// 「先查再決定 insert 還是 update」—— 那個寫法在併發連點下會兩邊都查不到、
// 兩邊都 insert,第二筆撞鍵報錯,使用者看到的是「投票失敗」。
// ON CONFLICT DO UPDATE 讓連點變成冪等:最後一次的 side 勝出。
//
// 改票不新增列:votes 是「當下的票」,不是投票史。要看變更時間有 updated_at,
// 而賠率只認當下 —— 留一串舊票只會讓 count 把同一個人算好幾次。
func (q *Queries) UpsertVote(ctx context.Context, arg UpsertVoteParams) error {
	_, err := q.db.Exec(ctx, upsertVote, arg.MatchID, arg.UserID, arg.Side)
	return err
}

const voteTalliesByMatch = `-- name: VoteTalliesByMatch :many

SELECT
  match_id,
  count(*) FILTER (WHERE side = 1)::bigint AS p1_votes,
  count(*) FILTER (WHERE side = 2)::bigint AS p2_votes
FROM activity.votes
WHERE match_id = ANY($1::bigint[])
GROUP BY match_id
`

type VoteTalliesByMatchRow struct {
	MatchID int64
	P1Votes int64
	P2Votes int64
}

// ══ 投票 ════════════════════════════════════════════════════════
// 數票:每場每邊各幾票。**只回票數,永不回傳誰投給誰。**
//
// 這不是效能考量也不是隱私加分項:票數直接推導賠率,公開投票人等於公開可操縱的標的
// (誰灌了票、該去說服誰改票)。所以這支查詢在型別上就沒有 user_id 可以洩漏,
// 而且整份檔案裡不存在「查別人投給誰」的第二支。
//
// 沒人投票的場次不會有列 —— 呼叫端 map 查不到即零票,零票時平滑參數會給出兩邊
// 相同的賠率,不需要在 SQL 補空列。走 votes_match_side_idx。
func (q *Queries) VoteTalliesByMatch(ctx context.Context, matchIds []int64) ([]VoteTalliesByMatchRow, error) {
	rows, err := q.db.Query(ctx, voteTalliesByMatch, matchIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VoteTalliesByMatchRow
	for rows.Next() {
		var i VoteTalliesByMatchRow
		if err := rows.Scan(&i.MatchID, &i.P1Votes, &i.P2Votes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
