// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activitylog.sql

package db

import (
	"context"
	"time"
)

const addActivityDailyXP = `-- name: AddActivityDailyXP :exec
UPDATE platform.activity_daily
SET xp_gained = xp_gained + $1
WHERE user_id = $2
  AND community_id = $3
  AND date = ($4::timestamptz AT TIME ZONE 'UTC')::date
`

type AddActivityDailyXPParams struct {
	XpGained    int64
	UserID      int64
	CommunityID int64
	OccurredAt  time.Time
}

// XP 入帳後回填當日彙總。單獨一句是因為 XP 入帳走 xp.Service(自己開 tx),
// 不在事實那個 tx 裡(理由見 activitylogpg 的註解)。
func (q *Queries) AddActivityDailyXP(ctx context.Context, arg AddActivityDailyXPParams) error {
	_, err := q.db.Exec(ctx, addActivityDailyXP,
		arg.XpGained,
		arg.UserID,
		arg.CommunityID,
		arg.OccurredAt,
	)
	return err
}

const bumpActivityDaily = `-- name: BumpActivityDaily :exec

INSERT INTO platform.activity_daily (
  user_id, community_id, date,
  messages, reactions, voice_seconds, online_seconds,
  first_seen_at, last_seen_at
) VALUES (
  $1, $2,
  ($3::timestamptz AT TIME ZONE 'UTC')::date,
  $4, $5,
  $6, $7,
  $3::timestamptz, $3::timestamptz
)
ON CONFLICT (user_id, community_id, date) DO UPDATE SET
  messages       = platform.activity_daily.messages       + EXCLUDED.messages,
  reactions      = platform.activity_daily.reactions      + EXCLUDED.reactions,
  voice_seconds  = platform.activity_daily.voice_seconds  + EXCLUDED.voice_seconds,
  online_seconds = platform.activity_daily.online_seconds + EXCLUDED.online_seconds,
  -- LEAST / GREATEST 在 Postgres 會忽略 NULL,所以舊列的空值不會吃掉新值。
  first_seen_at  = LEAST(platform.activity_daily.first_seen_at, EXCLUDED.first_seen_at),
  last_seen_at   = GREATEST(platform.activity_daily.last_seen_at, EXCLUDED.last_seen_at)
`

type BumpActivityDailyParams struct {
	UserID        int64
	CommunityID   int64
	OccurredAt    time.Time
	Messages      int32
	Reactions     int32
	VoiceSeconds  int32
	OnlineSeconds int32
}

// ══ 彙總層 ══
// 一句話完成「有就加、沒有就建」。date 由事件時間在 UTC 下取日,
// 不用使用者時區:投影必須可重算(users.timezone 會變,拿它當分桶鍵
// 會讓同一批事實在不同時間重算出不同結果)。
func (q *Queries) BumpActivityDaily(ctx context.Context, arg BumpActivityDailyParams) error {
	_, err := q.db.Exec(ctx, bumpActivityDaily,
		arg.UserID,
		arg.CommunityID,
		arg.OccurredAt,
		arg.Messages,
		arg.Reactions,
		arg.VoiceSeconds,
		arg.OnlineSeconds,
	)
	return err
}

const bumpMessageReactionCount = `-- name: BumpMessageReactionCount :exec
UPDATE platform.message_stats
SET reaction_count = GREATEST(0, reaction_count + $2), updated_at = now()
WHERE message_id = $1
`

type BumpMessageReactionCountParams struct {
	MessageID     string
	ReactionCount int32
}

// delta 為 -1 時用 GREATEST 夾住 0:計數是衍生值,寧可保守也不要出現負數。
func (q *Queries) BumpMessageReactionCount(ctx context.Context, arg BumpMessageReactionCountParams) error {
	_, err := q.db.Exec(ctx, bumpMessageReactionCount, arg.MessageID, arg.ReactionCount)
	return err
}

const claimMessage = `-- name: ClaimMessage :one

INSERT INTO platform.message_stats (message_id, user_id)
VALUES ($1, $2)
ON CONFLICT (message_id) DO NOTHING
RETURNING message_id
`

type ClaimMessageParams struct {
	MessageID string
	UserID    int64
}

// ══ 訊息 ══
// **訊息冪等的權威**:message_stats.message_id 是 PK,而且不論頻道白名單或
// opt-out 都會寫這一列 —— 所以它是唯一「每則訊息必定存在一次」的鍵。
// 回傳空列 = 這則訊息先前已處理過,整筆跳過。
// 併發同一則訊息時,後到的那個 tx 會卡在 PK 上等待,commit 後回 0 列。
func (q *Queries) ClaimMessage(ctx context.Context, arg ClaimMessageParams) (string, error) {
	row := q.db.QueryRow(ctx, claimMessage, arg.MessageID, arg.UserID)
	var message_id string
	err := row.Scan(&message_id)
	return message_id, err
}

const closePresenceSpan = `-- name: ClosePresenceSpan :exec
UPDATE platform.presence_spans
SET ended_at = $3
WHERE id = $1 AND started_at = $2 AND ended_at IS NULL
`

type ClosePresenceSpanParams struct {
	ID        int64
	StartedAt time.Time
	EndedAt   *time.Time
}

func (q *Queries) ClosePresenceSpan(ctx context.Context, arg ClosePresenceSpanParams) error {
	_, err := q.db.Exec(ctx, closePresenceSpan, arg.ID, arg.StartedAt, arg.EndedAt)
	return err
}

const closeReaction = `-- name: CloseReaction :exec
UPDATE platform.reaction_events
SET removed_at = $2
WHERE id = $1 AND removed_at IS NULL
`

type CloseReactionParams struct {
	ID        int64
	RemovedAt *time.Time
}

func (q *Queries) CloseReaction(ctx context.Context, arg CloseReactionParams) error {
	_, err := q.db.Exec(ctx, closeReaction, arg.ID, arg.RemovedAt)
	return err
}

const closeVoiceSession = `-- name: CloseVoiceSession :exec
UPDATE platform.voice_sessions
SET left_at          = $1,
    duration_seconds = $2,
    self_muted       = COALESCE($3, self_muted),
    self_deafened    = COALESCE($4, self_deafened),
    peer_count_avg   = COALESCE($5, peer_count_avg)
WHERE id = $6 AND joined_at = $7 AND left_at IS NULL
`

type CloseVoiceSessionParams struct {
	LeftAt          *time.Time
	DurationSeconds *int32
	SelfMuted       *bool
	SelfDeafened    *bool
	PeerCountAvg    *float32
	ID              int64
	JoinedAt        time.Time
}

// 帶 joined_at 讓分區裁剪生效(voice_sessions 按 joined_at 分區)。
// COALESCE:補收尾的事件若沒帶靜音狀態,保留進場時記下的值。
func (q *Queries) CloseVoiceSession(ctx context.Context, arg CloseVoiceSessionParams) error {
	_, err := q.db.Exec(ctx, closeVoiceSession,
		arg.LeftAt,
		arg.DurationSeconds,
		arg.SelfMuted,
		arg.SelfDeafened,
		arg.PeerCountAvg,
		arg.ID,
		arg.JoinedAt,
	)
	return err
}

const deletionRevisionExists = `-- name: DeletionRevisionExists :one

SELECT EXISTS (
  SELECT 1 FROM platform.message_revisions
  WHERE message_id = $1 AND kind = 'deleted'
) AS found
`

// ══ 訊息舊版本 ══
// 刪除沒有可靠的事件時間(Discord 不給),所以冪等改用「一則訊息只會被刪一次」。
func (q *Queries) DeletionRevisionExists(ctx context.Context, messageID string) (bool, error) {
	row := q.db.QueryRow(ctx, deletionRevisionExists, messageID)
	var found bool
	err := row.Scan(&found)
	return found, err
}

const editRevisionExists = `-- name: EditRevisionExists :one
SELECT EXISTS (
  SELECT 1 FROM platform.message_revisions
  WHERE message_id = $1 AND kind = 'edited' AND captured_at = $2
) AS found
`

type EditRevisionExistsParams struct {
	MessageID  string
	CapturedAt time.Time
}

// 編輯用 (message_id, captured_at):Discord 的 edited_timestamp 重送時穩定,
// 而同一則訊息可以被編輯很多次,不能只用 message_id。
func (q *Queries) EditRevisionExists(ctx context.Context, arg EditRevisionExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, editRevisionExists, arg.MessageID, arg.CapturedAt)
	var found bool
	err := row.Scan(&found)
	return found, err
}

const ensureMessageStats = `-- name: EnsureMessageStats :exec
INSERT INTO platform.message_stats (message_id, user_id)
VALUES ($1, $2)
ON CONFLICT (message_id) DO NOTHING
`

type EnsureMessageStatsParams struct {
	MessageID string
	UserID    int64
}

// reaction 用:沒見過的訊息也要有 stats 列才能累加 reaction_count。
func (q *Queries) EnsureMessageStats(ctx context.Context, arg EnsureMessageStatsParams) error {
	_, err := q.db.Exec(ctx, ensureMessageStats, arg.MessageID, arg.UserID)
	return err
}

const getOptOutLogging = `-- name: GetOptOutLogging :one
SELECT opt_out_logging FROM platform.user_privacy_settings WHERE user_id = $1
`

// 查無列 = 從未設定 = false(不退出)。
func (q *Queries) GetOptOutLogging(ctx context.Context, userID int64) (bool, error) {
	row := q.db.QueryRow(ctx, getOptOutLogging, userID)
	var opt_out_logging bool
	err := row.Scan(&opt_out_logging)
	return opt_out_logging, err
}

const getPresenceSpan = `-- name: GetPresenceSpan :one

SELECT id, started_at, ended_at FROM platform.presence_spans
WHERE user_id = $1 AND space_id = $2 AND started_at = $3
`

type GetPresenceSpanParams struct {
	UserID    int64
	SpaceID   int64
	StartedAt time.Time
}

type GetPresenceSpanRow struct {
	ID        int64
	StartedAt time.Time
	EndedAt   *time.Time
}

// ══ Presence ══
func (q *Queries) GetPresenceSpan(ctx context.Context, arg GetPresenceSpanParams) (GetPresenceSpanRow, error) {
	row := q.db.QueryRow(ctx, getPresenceSpan, arg.UserID, arg.SpaceID, arg.StartedAt)
	var i GetPresenceSpanRow
	err := row.Scan(&i.ID, &i.StartedAt, &i.EndedAt)
	return i, err
}

const getReaction = `-- name: GetReaction :one

SELECT id, removed_at FROM platform.reaction_events
WHERE message_id = $1 AND user_id = $2 AND emoji = $3
ORDER BY id
LIMIT 1
`

type GetReactionParams struct {
	MessageID string
	UserID    int64
	Emoji     string
}

type GetReactionRow struct {
	ID        int64
	RemovedAt *time.Time
}

// ══ Reaction ══
// 天然鍵 = (message_id, user_id, emoji)。一個人對同一則訊息的同一個表情
// 只有一列,按/取消是那一列的 added_at / removed_at ——
// 這正是 schemas/11 給這張表的形狀。
func (q *Queries) GetReaction(ctx context.Context, arg GetReactionParams) (GetReactionRow, error) {
	row := q.db.QueryRow(ctx, getReaction, arg.MessageID, arg.UserID, arg.Emoji)
	var i GetReactionRow
	err := row.Scan(&i.ID, &i.RemovedAt)
	return i, err
}

const getSpaceByExternalID = `-- name: GetSpaceByExternalID :one
SELECT id, community_id FROM platform.community_spaces
WHERE provider = $1 AND external_id = $2
`

type GetSpaceByExternalIDParams struct {
	Provider   string
	ExternalID string
}

type GetSpaceByExternalIDRow struct {
	ID          int64
	CommunityID int64
}

// guild snowflake → (space_id, community_id)。community_id 是 activity_daily 的 PK 之一。
func (q *Queries) GetSpaceByExternalID(ctx context.Context, arg GetSpaceByExternalIDParams) (GetSpaceByExternalIDRow, error) {
	row := q.db.QueryRow(ctx, getSpaceByExternalID, arg.Provider, arg.ExternalID)
	var i GetSpaceByExternalIDRow
	err := row.Scan(&i.ID, &i.CommunityID)
	return i, err
}

const getSpaceChannel = `-- name: GetSpaceChannel :one
SELECT log_messages, grant_xp FROM platform.space_channels
WHERE space_id = $1 AND external_id = $2
`

type GetSpaceChannelParams struct {
	SpaceID    int64
	ExternalID string
}

type GetSpaceChannelRow struct {
	LogMessages bool
	GrantXp     bool
}

// 頻道註冊表(schemas/01 增補 C)= 白名單權威。
// 查無列 = 未註冊:log_messages 視為 false(白名單制),grant_xp 視為 true
// (欄位預設值;白名單管的是「內容要不要落地」,不是「要不要計分」)。
func (q *Queries) GetSpaceChannel(ctx context.Context, arg GetSpaceChannelParams) (GetSpaceChannelRow, error) {
	row := q.db.QueryRow(ctx, getSpaceChannel, arg.SpaceID, arg.ExternalID)
	var i GetSpaceChannelRow
	err := row.Scan(&i.LogMessages, &i.GrantXp)
	return i, err
}

const getVoiceSession = `-- name: GetVoiceSession :one

SELECT id, joined_at, left_at, duration_seconds FROM platform.voice_sessions
WHERE user_id = $1 AND space_id = $2 AND channel_id = $3 AND joined_at = $4
`

type GetVoiceSessionParams struct {
	UserID    int64
	SpaceID   int64
	ChannelID string
	JoinedAt  time.Time
}

type GetVoiceSessionRow struct {
	ID              int64
	JoinedAt        time.Time
	LeftAt          *time.Time
	DurationSeconds *int32
}

// ══ 語音 ══
// 天然鍵 = (user_id, space_id, channel_id, joined_at)。
func (q *Queries) GetVoiceSession(ctx context.Context, arg GetVoiceSessionParams) (GetVoiceSessionRow, error) {
	row := q.db.QueryRow(ctx, getVoiceSession,
		arg.UserID,
		arg.SpaceID,
		arg.ChannelID,
		arg.JoinedAt,
	)
	var i GetVoiceSessionRow
	err := row.Scan(
		&i.ID,
		&i.JoinedAt,
		&i.LeftAt,
		&i.DurationSeconds,
	)
	return i, err
}

const incrementReplyCount = `-- name: IncrementReplyCount :exec
UPDATE platform.message_stats
SET reply_count = reply_count + 1, updated_at = now()
WHERE message_id = $1
`

// 只有 hestia 見過的被回覆訊息才累加(message_stats.user_id 是 NOT NULL,
// 沒見過就沒有作者可填 —— 那種情況直接略過,不猜)。
func (q *Queries) IncrementReplyCount(ctx context.Context, messageID string) error {
	_, err := q.db.Exec(ctx, incrementReplyCount, messageID)
	return err
}

const insertMessageLog = `-- name: InsertMessageLog :exec
INSERT INTO platform.message_logs (
  user_id, space_id, channel_id, channel_kind, thread_id, message_id,
  excerpt, full_length, has_attachment, reply_to, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (message_id, created_at) DO NOTHING
`

type InsertMessageLogParams struct {
	UserID        int64
	SpaceID       int64
	ChannelID     string
	ChannelKind   string
	ThreadID      *string
	MessageID     string
	Excerpt       *string
	FullLength    *int32
	HasAttachment bool
	ReplyTo       *string
	CreatedAt     time.Time
}

// excerpt 為 NULL 的兩種情況:頻道沒開 log_messages(那時根本不呼叫本查詢)、
// 作者 opt_out_logging(呼叫但 excerpt 傳 NULL)。full_length 照記 ——
// 它是長度不是內容,而且是「截斷長度夠不夠」的唯一檢討依據。
// ON CONFLICT 對應既有的 UNIQUE (message_id, created_at):ClaimMessage 已經擋過
// 一次,這裡是資料表自己的第二道防線,不是第二個權威。
func (q *Queries) InsertMessageLog(ctx context.Context, arg InsertMessageLogParams) error {
	_, err := q.db.Exec(ctx, insertMessageLog,
		arg.UserID,
		arg.SpaceID,
		arg.ChannelID,
		arg.ChannelKind,
		arg.ThreadID,
		arg.MessageID,
		arg.Excerpt,
		arg.FullLength,
		arg.HasAttachment,
		arg.ReplyTo,
		arg.CreatedAt,
	)
	return err
}

const insertMessageRevision = `-- name: InsertMessageRevision :exec
INSERT INTO platform.message_revisions (message_id, user_id, excerpt, kind, captured_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertMessageRevisionParams struct {
	MessageID  string
	UserID     int64
	Excerpt    *string
	Kind       string
	CapturedAt time.Time
}

func (q *Queries) InsertMessageRevision(ctx context.Context, arg InsertMessageRevisionParams) error {
	_, err := q.db.Exec(ctx, insertMessageRevision,
		arg.MessageID,
		arg.UserID,
		arg.Excerpt,
		arg.Kind,
		arg.CapturedAt,
	)
	return err
}

const insertPresenceSpan = `-- name: InsertPresenceSpan :exec
INSERT INTO platform.presence_spans (user_id, space_id, status, started_at, ended_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertPresenceSpanParams struct {
	UserID    int64
	SpaceID   int64
	Status    string
	StartedAt time.Time
	EndedAt   *time.Time
}

func (q *Queries) InsertPresenceSpan(ctx context.Context, arg InsertPresenceSpanParams) error {
	_, err := q.db.Exec(ctx, insertPresenceSpan,
		arg.UserID,
		arg.SpaceID,
		arg.Status,
		arg.StartedAt,
		arg.EndedAt,
	)
	return err
}

const insertReaction = `-- name: InsertReaction :exec
INSERT INTO platform.reaction_events (message_id, user_id, space_id, emoji, added_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertReactionParams struct {
	MessageID string
	UserID    int64
	SpaceID   int64
	Emoji     string
	AddedAt   time.Time
}

func (q *Queries) InsertReaction(ctx context.Context, arg InsertReactionParams) error {
	_, err := q.db.Exec(ctx, insertReaction,
		arg.MessageID,
		arg.UserID,
		arg.SpaceID,
		arg.Emoji,
		arg.AddedAt,
	)
	return err
}

const insertVoiceSession = `-- name: InsertVoiceSession :exec
INSERT INTO platform.voice_sessions (
  user_id, space_id, channel_id, joined_at, left_at,
  duration_seconds, self_muted, self_deafened, peer_count_avg
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertVoiceSessionParams struct {
	UserID          int64
	SpaceID         int64
	ChannelID       string
	JoinedAt        time.Time
	LeftAt          *time.Time
	DurationSeconds *int32
	SelfMuted       *bool
	SelfDeafened    *bool
	PeerCountAvg    *float32
}

func (q *Queries) InsertVoiceSession(ctx context.Context, arg InsertVoiceSessionParams) error {
	_, err := q.db.Exec(ctx, insertVoiceSession,
		arg.UserID,
		arg.SpaceID,
		arg.ChannelID,
		arg.JoinedAt,
		arg.LeftAt,
		arg.DurationSeconds,
		arg.SelfMuted,
		arg.SelfDeafened,
		arg.PeerCountAvg,
	)
	return err
}

const lockActivityKey = `-- name: LockActivityKey :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

// 沒有 UNIQUE 約束可用時的併發防線:把「同一個天然鍵」的併發寫入串行化,
// 讓「先查再寫」不會兩個 tx 同時通過檢查。tx 結束自動釋放。
// hash 碰撞只會造成無關鍵之間偶爾互等,不影響正確性。
func (q *Queries) LockActivityKey(ctx context.Context, lockKey string) error {
	_, err := q.db.Exec(ctx, lockActivityKey, lockKey)
	return err
}

const markMessageDeleted = `-- name: MarkMessageDeleted :exec
UPDATE platform.message_logs
SET deleted_at = $2
WHERE message_id = $1 AND deleted_at IS NULL
`

type MarkMessageDeletedParams struct {
	MessageID string
	DeletedAt *time.Time
}

// 刪除事件同時在 message_logs 打上 deleted_at(欄位本來就是為此存在)。
// 沒有那一列(頻道沒開白名單)時什麼都不做。
func (q *Queries) MarkMessageDeleted(ctx context.Context, arg MarkMessageDeletedParams) error {
	_, err := q.db.Exec(ctx, markMessageDeleted, arg.MessageID, arg.DeletedAt)
	return err
}

const messageStatsExists = `-- name: MessageStatsExists :one
SELECT EXISTS (
  SELECT 1 FROM platform.message_stats WHERE message_id = $1
) AS found
`

func (q *Queries) MessageStatsExists(ctx context.Context, messageID string) (bool, error) {
	row := q.db.QueryRow(ctx, messageStatsExists, messageID)
	var found bool
	err := row.Scan(&found)
	return found, err
}

const reopenReaction = `-- name: ReopenReaction :exec
UPDATE platform.reaction_events
SET added_at = $2, removed_at = NULL
WHERE id = $1
`

type ReopenReactionParams struct {
	ID      int64
	AddedAt time.Time
}

// 取消後又按回來:復用同一列。activity_daily.reactions **不再加一次** ——
// 否則按了取消再按就是無限刷參與度。
func (q *Queries) ReopenReaction(ctx context.Context, arg ReopenReactionParams) error {
	_, err := q.db.Exec(ctx, reopenReaction, arg.ID, arg.AddedAt)
	return err
}

const resolveIdentityUser = `-- name: ResolveIdentityUser :one


SELECT user_id FROM platform.identities
WHERE provider = $1 AND provider_user_id = $2
`

type ResolveIdentityUserParams struct {
	Provider       string
	ProviderUserID string
}

// 活動記錄(schemas/10-activity-logs.md、schemas/11-messages.md)。
//
// 貫穿本檔的兩件事:
//  1. **寫入時彙總**:事實與 activity_daily / message_stats 在同一個 tx。
//  2. **冪等靠天然唯一鍵**,不另設冪等鍵表(專案第 9 條)。
//     有 UNIQUE 的用 ON CONFLICT;沒有 UNIQUE 的(voice_sessions /
//     presence_spans / reaction_events 這三張表沒有天然鍵的約束)
//     用 advisory lock 把同鍵的併發串行化,再「查了才寫」。
//
// ══ 解析:外部識別碼 → 內部 id ══
// X-Acting-User 的解析。查不到就是查不到 —— 呼叫端絕不可在這裡建帳號,
// 建帳號的權威在 OAuth 登入流程(否則會產生沒有 privacy 設定列的殘缺使用者)。
func (q *Queries) ResolveIdentityUser(ctx context.Context, arg ResolveIdentityUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, resolveIdentityUser, arg.Provider, arg.ProviderUserID)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}
