// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity_handicap.sql

package db

import (
	"context"
	"time"
)

const findMatchBudgetByMatch = `-- name: FindMatchBudgetByMatch :one
SELECT b.match_id, b.player_id, p.public_id AS player_public_id, b.budget, b.spent
FROM activity.match_budgets b
JOIN activity.tournament_players p ON p.id = b.player_id
WHERE b.match_id = $1
LIMIT 1
`

type FindMatchBudgetByMatchRow struct {
	MatchID        int64
	PlayerID       int64
	PlayerPublicID string
	Budget         int64
	Spent          int64
}

// 一場最多一列:只有低段位方會被建列(高段位方永不獲得反向補償),
// 所以「這場的預算」等於「施加者的預算」。LIMIT 1 是對這個不變量的防守,
// 不是在多列裡挑一列 —— 真的出現兩列代表發預算的路徑有 bug。
func (q *Queries) FindMatchBudgetByMatch(ctx context.Context, matchID int64) (FindMatchBudgetByMatchRow, error) {
	row := q.db.QueryRow(ctx, findMatchBudgetByMatch, matchID)
	var i FindMatchBudgetByMatchRow
	err := row.Scan(
		&i.MatchID,
		&i.PlayerID,
		&i.PlayerPublicID,
		&i.Budget,
		&i.Spent,
	)
	return i, err
}

const getHandicapItemByPublicID = `-- name: GetHandicapItemByPublicID :one
SELECT id, public_id, tournament_id, category, name, description, referee_note,
       cost, repeatable, sort_order
FROM activity.handicap_items
WHERE tournament_id = $1 AND public_id = $2
`

type GetHandicapItemByPublicIDParams struct {
	TournamentID int64
	PublicID     string
}

type GetHandicapItemByPublicIDRow struct {
	ID           int64
	PublicID     string
	TournamentID int64
	Category     string
	Name         string
	Description  *string
	RefereeNote  *string
	Cost         int64
	Repeatable   bool
	SortOrder    int32
}

// tournament_id 一起進 WHERE 而不是查到再比對:項目逐屆一套、價格逐屆可調,
// 拿上一屆的 public_id 買這一屆的場次必須是「找不到」,不是「找到但不給用」。
func (q *Queries) GetHandicapItemByPublicID(ctx context.Context, arg GetHandicapItemByPublicIDParams) (GetHandicapItemByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, getHandicapItemByPublicID, arg.TournamentID, arg.PublicID)
	var i GetHandicapItemByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TournamentID,
		&i.Category,
		&i.Name,
		&i.Description,
		&i.RefereeNote,
		&i.Cost,
		&i.Repeatable,
		&i.SortOrder,
	)
	return i, err
}

const getHandicapSelection = `-- name: GetHandicapSelection :one
SELECT s.id, s.public_id, s.match_id, m.public_id AS match_public_id,
       s.player_id, s.item_id,
       i.public_id AS item_ref, i.name AS item_name, i.category,
       s.cost, s.target_note, s.voided, s.created_at
FROM activity.handicap_selections s
JOIN activity.handicap_items i ON i.id = s.item_id
JOIN activity.matches m ON m.id = s.match_id
WHERE s.public_id = $1
`

type GetHandicapSelectionRow struct {
	ID            int64
	PublicID      string
	MatchID       int64
	MatchPublicID string
	PlayerID      int64
	ItemID        int64
	ItemRef       string
	ItemName      string
	Category      string
	Cost          int64
	TargetNote    *string
	Voided        bool
	CreatedAt     time.Time
}

// 與 ListHandicapSelections 相反,這裡**含已作廢者**,voided 原樣回傳:
// 退選路徑必須分得出「已經退過」(ErrSelectionAlreadyVoided)與「不存在」
// (ErrSelectionNotFound)。過濾掉作廢列會讓重複退選看起來像查無此筆。
//
// match_public_id 是退選路徑的必要欄位:呼叫端拿它去 LockMatchForHandicap,
// 也就是「從一筆選擇找到它所屬的序列化點」。
func (q *Queries) GetHandicapSelection(ctx context.Context, publicID string) (GetHandicapSelectionRow, error) {
	row := q.db.QueryRow(ctx, getHandicapSelection, publicID)
	var i GetHandicapSelectionRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.MatchID,
		&i.MatchPublicID,
		&i.PlayerID,
		&i.ItemID,
		&i.ItemRef,
		&i.ItemName,
		&i.Category,
		&i.Cost,
		&i.TargetNote,
		&i.Voided,
		&i.CreatedAt,
	)
	return i, err
}

const getMatchBudget = `-- name: GetMatchBudget :one

SELECT b.match_id, b.player_id, p.public_id AS player_public_id, b.budget, b.spent
FROM activity.match_budgets b
JOIN activity.tournament_players p ON p.id = b.player_id
WHERE b.match_id = $1 AND b.player_id = $2
`

type GetMatchBudgetParams struct {
	MatchID  int64
	PlayerID int64
}

type GetMatchBudgetRow struct {
	MatchID        int64
	PlayerID       int64
	PlayerPublicID string
	Budget         int64
	Spent          int64
}

// ── BP 預算 ─────────────────────────────────────────────────────
// 沒有列 = 本場無讓武(同段對決)、或這個人是高段位方、或根本不是這場的選手。
// 三者對呼叫端是同一件事,一律 ErrNoBudget —— 分得更細等於洩漏「這場的預算持有者
// 不是你」以外的資訊。
//
// JOIN tournament_players 只為了帶回 public_id:對外永不出現內部 BIGINT id(鐵則 5)。
func (q *Queries) GetMatchBudget(ctx context.Context, arg GetMatchBudgetParams) (GetMatchBudgetRow, error) {
	row := q.db.QueryRow(ctx, getMatchBudget, arg.MatchID, arg.PlayerID)
	var i GetMatchBudgetRow
	err := row.Scan(
		&i.MatchID,
		&i.PlayerID,
		&i.PlayerPublicID,
		&i.Budget,
		&i.Spent,
	)
	return i, err
}

const getMatchForHandicap = `-- name: GetMatchForHandicap :one
SELECT
  m.id, m.public_id, m.tournament_id, m.status, m.handicap_open, m.handicap_locked_at,
  m.p1_player_id, m.p2_player_id,
  p1.public_id AS p1_player_public_id,
  p2.public_id AS p2_player_public_id,
  p1.rank_level AS p1_rank_level,
  p2.rank_level AS p2_rank_level,
  COALESCE(NULLIF(t.config ->> 'bp_per_rank_gap', ''), '0')::bigint AS per_rank_gap
FROM activity.matches m
JOIN activity.tournaments t ON t.id = m.tournament_id
LEFT JOIN activity.tournament_players p1 ON p1.id = m.p1_player_id
LEFT JOIN activity.tournament_players p2 ON p2.id = m.p2_player_id
WHERE m.public_id = $1
`

type GetMatchForHandicapRow struct {
	ID               int64
	PublicID         string
	TournamentID     int64
	Status           string
	HandicapOpen     bool
	HandicapLockedAt *time.Time
	P1PlayerID       *int64
	P2PlayerID       *int64
	P1PlayerPublicID *string
	P2PlayerPublicID *string
	P1RankLevel      *int16
	P2RankLevel      *int16
	PerRankGap       int64
}

// 唯讀路徑(MyBudget / MatchHandicaps)的無鎖版本,欄位與 LockMatchForHandicap 完全一致。
//
// 一次撈齊而不是分三次查,是因為讓武的每個判斷(狀態、段位差、逐屆設定)都同時用到
// 這三者;分開查會讓它們來自不同的快照,出現「用舊段位算新預算」這種查不出來的錯。
func (q *Queries) GetMatchForHandicap(ctx context.Context, matchPublicID string) (GetMatchForHandicapRow, error) {
	row := q.db.QueryRow(ctx, getMatchForHandicap, matchPublicID)
	var i GetMatchForHandicapRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TournamentID,
		&i.Status,
		&i.HandicapOpen,
		&i.HandicapLockedAt,
		&i.P1PlayerID,
		&i.P2PlayerID,
		&i.P1PlayerPublicID,
		&i.P2PlayerPublicID,
		&i.P1RankLevel,
		&i.P2RankLevel,
		&i.PerRankGap,
	)
	return i, err
}

const insertHandicapItems = `-- name: InsertHandicapItems :one
WITH inserted AS (
  INSERT INTO activity.handicap_items (
    tournament_id, public_id, category, name, description, referee_note,
    cost, repeatable, sort_order
  )
  SELECT
    $1, v.public_id, v.category, v.name,
    NULLIF(v.description, ''), NULLIF(v.referee_note, ''),
    v.cost, v.repeatable, v.sort_order
  FROM (
    SELECT
      unnest($2::text[])     AS public_id,
      unnest($3::text[])     AS category,
      unnest($4::text[])          AS name,
      unnest($5::text[])   AS description,
      unnest($6::text[])  AS referee_note,
      unnest($7::bigint[])        AS cost,
      unnest($8::boolean[]) AS repeatable,
      unnest($9::int[])     AS sort_order
  ) AS v
  ON CONFLICT (tournament_id, category, name) DO NOTHING
  RETURNING id
)
SELECT count(*)::bigint AS inserted FROM inserted
`

type InsertHandicapItemsParams struct {
	TournamentID int64
	PublicIds    []string
	Categories   []string
	Names        []string
	Descriptions []string
	RefereeNotes []string
	Costs        []int64
	Repeatables  []bool
	SortOrders   []int32
}

// 把種子定義一次實例化到某一屆,回**實際插入**的列數。
//
// ON CONFLICT (tournament_id, category, name) DO NOTHING:重跑安裝回 0,不改價格。
// 改價是裁判的明確動作,不該由「不小心重跑一次 seed」造成。
//
// unnest 批次而不是迴圈單筆:34 次往返換一次,而且整批同一個敘述 ——
// 中途失敗不會留下半套項目。public_id(ULID)由 adapter 產生後傳入,SQL 生不出 ULID。
//
// NULLIF(..., ”) 把空字串收斂成 NULL:text[] 參數的元素表達不了 NULL,
// 而「還沒寫」的 referee_note 在 DB 裡就該是 NULL(seed 目前全為 null,待裁判補)。
//
// 八個單引數 unnest 併排在子查詢裡,而不是 unnest(a, b, ...) AS v(...):
// sqlc 的 catalog 只認單引數 unnest,多引數形式會編譯失敗。兩者語意相同 ——
// select list 裡的多個集合回傳函數自 PG10 起同步展開(長度一致時逐列對齊)。
func (q *Queries) InsertHandicapItems(ctx context.Context, arg InsertHandicapItemsParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertHandicapItems,
		arg.TournamentID,
		arg.PublicIds,
		arg.Categories,
		arg.Names,
		arg.Descriptions,
		arg.RefereeNotes,
		arg.Costs,
		arg.Repeatables,
		arg.SortOrders,
	)
	var inserted int64
	err := row.Scan(&inserted)
	return inserted, err
}

const insertHandicapSelection = `-- name: InsertHandicapSelection :one
WITH ins AS (
  INSERT INTO activity.handicap_selections (
    public_id, match_id, player_id, item_id, cost, target_note
  )
  VALUES (
    $1, $2, $3, $4,
    $5, NULLIF($6::text, '')
  )
  RETURNING id, public_id, match_id, player_id, item_id, cost, target_note, voided, created_at
)
SELECT s.id, s.public_id, s.match_id, m.public_id AS match_public_id,
       s.player_id, s.item_id,
       i.public_id AS item_ref, i.name AS item_name, i.category,
       s.cost, s.target_note, s.voided, s.created_at
FROM ins s
JOIN activity.handicap_items i ON i.id = s.item_id
JOIN activity.matches m ON m.id = s.match_id
`

type InsertHandicapSelectionParams struct {
	PublicID   string
	MatchID    int64
	PlayerID   int64
	ItemID     int64
	Cost       int64
	TargetNote string
}

type InsertHandicapSelectionRow struct {
	ID            int64
	PublicID      string
	MatchID       int64
	MatchPublicID string
	PlayerID      int64
	ItemID        int64
	ItemRef       string
	ItemName      string
	Category      string
	Cost          int64
	TargetNote    *string
	Voided        bool
	CreatedAt     time.Time
}

// 每買一次一列,同一項目買三次就是三列 —— 不是一列 qty=3。
// handicap_selections 刻意沒有 UNIQUE (match_id, player_id, item_id),所以這裡
// **不能**加 ON CONFLICT:重複購買同一項目是設計(09-12 定案),不是要吞掉的衝突。
//
// cost 由呼叫端傳入而不是就地 SELECT i.cost:價格快照要與餘額檢查看到的是同一個值,
// 這裡再查一次等於在檢查與寫入之間開一道改價的縫。
// 外鍵 handicap_selections_budget_fkey 指向 match_budgets 的複合鍵 ——
// 沒有預算的人連一列都插不進來,這是應用層檢查之外的第二道保險。
//
// CTE + JOIN 回填項目與場次快照,一次往返就給出完整的 Selection。
func (q *Queries) InsertHandicapSelection(ctx context.Context, arg InsertHandicapSelectionParams) (InsertHandicapSelectionRow, error) {
	row := q.db.QueryRow(ctx, insertHandicapSelection,
		arg.PublicID,
		arg.MatchID,
		arg.PlayerID,
		arg.ItemID,
		arg.Cost,
		arg.TargetNote,
	)
	var i InsertHandicapSelectionRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.MatchID,
		&i.MatchPublicID,
		&i.PlayerID,
		&i.ItemID,
		&i.ItemRef,
		&i.ItemName,
		&i.Category,
		&i.Cost,
		&i.TargetNote,
		&i.Voided,
		&i.CreatedAt,
	)
	return i, err
}

const insertMatchBudget = `-- name: InsertMatchBudget :one
WITH ins AS (
  INSERT INTO activity.match_budgets (match_id, player_id, budget)
  VALUES ($1, $2, $3)
  RETURNING match_id, player_id, budget, spent
)
SELECT ins.match_id, ins.player_id, p.public_id AS player_public_id, ins.budget, ins.spent
FROM ins
JOIN activity.tournament_players p ON p.id = ins.player_id
`

type InsertMatchBudgetParams struct {
	MatchID  int64
	PlayerID int64
	Budget   int64
}

type InsertMatchBudgetRow struct {
	MatchID        int64
	PlayerID       int64
	PlayerPublicID string
	Budget         int64
	Spent          int64
}

// 刻意**沒有** ON CONFLICT:複合主鍵 (match_id, player_id) 撞鍵時要讓 23505 冒上來,
// adapter 轉成 ErrBudgetExists,呼叫端再去比對既有金額與當下段位差是否一致。
// 吞掉衝突(DO NOTHING / DO UPDATE)會讓「抽籤後有人改了段位」變成默默覆蓋,
// 而已經花掉的 spent 會對不上新的 budget。
//
// 用 CTE 而不是單純 RETURNING:RETURNING 看不到 join 進來的 public_id,
// 而呼叫端拿到的 Budget 必須是完整的(少一個欄位就得多一次往返)。
func (q *Queries) InsertMatchBudget(ctx context.Context, arg InsertMatchBudgetParams) (InsertMatchBudgetRow, error) {
	row := q.db.QueryRow(ctx, insertMatchBudget, arg.MatchID, arg.PlayerID, arg.Budget)
	var i InsertMatchBudgetRow
	err := row.Scan(
		&i.MatchID,
		&i.PlayerID,
		&i.PlayerPublicID,
		&i.Budget,
		&i.Spent,
	)
	return i, err
}

const listHandicapItems = `-- name: ListHandicapItems :many

SELECT id, public_id, tournament_id, category, name, description, referee_note,
       cost, repeatable, sort_order
FROM activity.handicap_items
WHERE tournament_id = $1
ORDER BY category, sort_order, id
`

type ListHandicapItemsRow struct {
	ID           int64
	PublicID     string
	TournamentID int64
	Category     string
	Name         string
	Description  *string
	RefereeNote  *string
	Cost         int64
	Repeatable   bool
	SortOrder    int32
}

// ── 讓武項目 ────────────────────────────────────────────────────
// 排序即前端的呈現順序:先分類,類內依 sort_order,最後以 id 收尾 ——
// sort_order 允許重複,沒有第三個鍵的話同分項目的順序會隨執行計畫變動,
// 選購頁每次重整就換一次位置。走 handicap_items_tournament_idx。
func (q *Queries) ListHandicapItems(ctx context.Context, tournamentID int64) ([]ListHandicapItemsRow, error) {
	rows, err := q.db.Query(ctx, listHandicapItems, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHandicapItemsRow
	for rows.Next() {
		var i ListHandicapItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.TournamentID,
			&i.Category,
			&i.Name,
			&i.Description,
			&i.RefereeNote,
			&i.Cost,
			&i.Repeatable,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHandicapSelections = `-- name: ListHandicapSelections :many

SELECT s.id, s.public_id, s.match_id, m.public_id AS match_public_id,
       s.player_id, s.item_id,
       i.public_id AS item_ref, i.name AS item_name, i.category,
       s.cost, s.target_note, s.voided, s.created_at
FROM activity.handicap_selections s
JOIN activity.handicap_items i ON i.id = s.item_id
JOIN activity.matches m ON m.id = s.match_id
WHERE s.match_id = $1 AND s.player_id = $2 AND NOT s.voided
ORDER BY s.created_at, s.id
`

type ListHandicapSelectionsParams struct {
	MatchID  int64
	PlayerID int64
}

type ListHandicapSelectionsRow struct {
	ID            int64
	PublicID      string
	MatchID       int64
	MatchPublicID string
	PlayerID      int64
	ItemID        int64
	ItemRef       string
	ItemName      string
	Category      string
	Cost          int64
	TargetNote    *string
	Voided        bool
	CreatedAt     time.Time
}

// ── 讓武選擇 ────────────────────────────────────────────────────
// 只回**未作廢**的:退掉的項目對餘額與公開清單都不存在,
// 讓呼叫端每次自己補 WHERE NOT voided 遲早會漏一處。
//
// 依 created_at 排序 = 購買順序,同時以 id 收尾:created_at 不唯一,
// 同一次連點會落在同一個微秒,沒有第二個鍵清單順序就不穩定。
//
// JOIN handicap_items 帶回名稱與分類快照,前端顯示一張清單不必逐項回查;
// 但 cost 一律取 s.cost(購買當下的價格快照),項目改價不影響已成立的選擇。
// 順帶帶回 match 的 public_id,免得同一個 Selection 型別在不同查詢路徑有不同的完整度。
func (q *Queries) ListHandicapSelections(ctx context.Context, arg ListHandicapSelectionsParams) ([]ListHandicapSelectionsRow, error) {
	rows, err := q.db.Query(ctx, listHandicapSelections, arg.MatchID, arg.PlayerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHandicapSelectionsRow
	for rows.Next() {
		var i ListHandicapSelectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.MatchID,
			&i.MatchPublicID,
			&i.PlayerID,
			&i.ItemID,
			&i.ItemRef,
			&i.ItemName,
			&i.Category,
			&i.Cost,
			&i.TargetNote,
			&i.Voided,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMatchForHandicap = `-- name: LockMatchForHandicap :one


SELECT
  m.id, m.public_id, m.tournament_id, m.status, m.handicap_open, m.handicap_locked_at,
  m.p1_player_id, m.p2_player_id,
  p1.public_id AS p1_player_public_id,
  p2.public_id AS p2_player_public_id,
  p1.rank_level AS p1_rank_level,
  p2.rank_level AS p2_rank_level,
  COALESCE(NULLIF(t.config ->> 'bp_per_rank_gap', ''), '0')::bigint AS per_rank_gap
FROM activity.matches m
JOIN activity.tournaments t ON t.id = m.tournament_id
LEFT JOIN activity.tournament_players p1 ON p1.id = m.p1_player_id
LEFT JOIN activity.tournament_players p2 ON p2.id = m.p2_player_id
WHERE m.public_id = $1
FOR UPDATE OF m
`

type LockMatchForHandicapRow struct {
	ID               int64
	PublicID         string
	TournamentID     int64
	Status           string
	HandicapOpen     bool
	HandicapLockedAt *time.Time
	P1PlayerID       *int64
	P2PlayerID       *int64
	P1PlayerPublicID *string
	P2PlayerPublicID *string
	P1RankLevel      *int16
	P2RankLevel      *int16
	PerRankGap       int64
}

// 讓武 BP query(schemas/20-activity-tournament.md,migrations/activity/00002 + 00004)。
//
// BP 不走 Ledger、不需冪等鍵:它每輪重發、沒花完即作廢、不可交易、不可累積,
// 四個性質沒一個符合貨幣(理由寫在 00002_handicap.sql 的檔頭)。因此這裡是
// activity schema 內部的純 CRUD,沒有任何 token_entries 的影子。
//
// 但「不是錢」不代表可以亂:BP 超支會直接毀掉一場比賽的公正性,所以這組查詢
// 有兩道防線 ——
//  1. 寫入路徑一律先鎖場次列(FOR UPDATE OF m),以 matches 那一列為序列化點;
//  2. spent 是覆寫而非增量,權威永遠是 RecalcMatchBudgetSpent 的 SUM。
//
// 命名一律 *Handicap* / *MatchBudget* 前綴:生成的 db package 與 platform 的查詢
// 同居一個命名空間,GetItem / ListItems 這種名字撞得到。
// ── 場次 ────────────────────────────────────────────────────────
// 整個 handicap package 的**序列化點**。
//
// 選購、退選、封盤三條寫入路徑的第一步都是這一句,所以它們對同一場比賽彼此互斥:
// 連點兩次買同一項不會同時通過餘額檢查(第二個請求會等到第一個 commit 之後才讀到
// 新的 spent),一邊買一邊封盤也不會出現「檢查時沒封盤、寫入時已封盤」的縫隙。
//
// FOR UPDATE OF m 是必要的寫法,不是精簡:
//   - p1/p2 走 LEFT JOIN(對手未定時為 NULL),Postgres 禁止對外連接的可空側加鎖;
//   - 賽事與選手列是共享讀的參考資料,鎖了只會讓不同場次互相卡住。
//
// per_rank_gap 取自 tournaments.config;缺鍵時回 0,由 bp 套件退回預設值 8
// (預設值的權威在 bp.DefaultPerRankGap,不在這裡再寫一份)。
func (q *Queries) LockMatchForHandicap(ctx context.Context, matchPublicID string) (LockMatchForHandicapRow, error) {
	row := q.db.QueryRow(ctx, lockMatchForHandicap, matchPublicID)
	var i LockMatchForHandicapRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.TournamentID,
		&i.Status,
		&i.HandicapOpen,
		&i.HandicapLockedAt,
		&i.P1PlayerID,
		&i.P2PlayerID,
		&i.P1PlayerPublicID,
		&i.P2PlayerPublicID,
		&i.P1RankLevel,
		&i.P2RankLevel,
		&i.PerRankGap,
	)
	return i, err
}

const lockMatchHandicaps = `-- name: LockMatchHandicaps :execrows
UPDATE activity.matches
SET handicap_open = false,
    handicap_locked_at = $1,
    status = 'locked',
    updated_at = now()
WHERE id = $2 AND handicap_locked_at IS NULL
`

type LockMatchHandicapsParams struct {
	LockedAt *time.Time
	MatchID  int64
}

// 封盤。status 一起改成 'locked' 不是多管閒事,是 matches_locked_at_check 逼出來的:
// handicap_locked_at 非 NULL 時 status 必須是 locked/live/done,只改時間戳會被 DB 擋掉。
//
// handicap_locked_at IS NULL 是**封盤不可逆**的 DB 側保證:重複封盤影響 0 列,
// 呼叫端據此回 ErrAlreadyLocked。默默成功會讓 Discord 公告每呼叫一次就再發一次。
func (q *Queries) LockMatchHandicaps(ctx context.Context, arg LockMatchHandicapsParams) (int64, error) {
	result, err := q.db.Exec(ctx, lockMatchHandicaps, arg.LockedAt, arg.MatchID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markHandicapSelectionVoided = `-- name: MarkHandicapSelectionVoided :execrows
UPDATE activity.handicap_selections
SET voided = true
WHERE id = $1 AND NOT voided
`

// voided 之外一律不動:退費只是 BP 內部的事(標記 + 覆寫 spent),不經 Ledger,
// 也不刪列 —— 買過又退掉是裁判事後要看得到的事實。
//
// AND NOT voided 讓重複退選影響 0 列。呼叫端已在場次鎖下檢查過一次,
// 這條是同一個判斷在 DB 側的備份,不是它的替代品。
func (q *Queries) MarkHandicapSelectionVoided(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, markHandicapSelectionVoided, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recalcMatchBudgetSpent = `-- name: RecalcMatchBudgetSpent :one
SELECT COALESCE(SUM(cost), 0)::bigint AS spent
FROM activity.handicap_selections
WHERE match_id = $1 AND player_id = $2 AND NOT voided
`

type RecalcMatchBudgetSpentParams struct {
	MatchID  int64
	PlayerID int64
}

// spent 的權威算式。service 每次寫入前拿它與 match_budgets.spent 核對,
// 對不上就整個動作失敗(ErrBudgetInconsistent)而不自動修正 ——
// 衍生資料對不上代表寫入路徑有 bug,繼續算下去只會把錯誤擴散到下一次餘額檢查。
// 這是 schemas/20 待確認 ② 要求的那條驗證。述詞與 handicap_selections_match_player_idx
// 的部分索引條件(WHERE NOT voided)同形,走得到那條索引。
func (q *Queries) RecalcMatchBudgetSpent(ctx context.Context, arg RecalcMatchBudgetSpentParams) (int64, error) {
	row := q.db.QueryRow(ctx, recalcMatchBudgetSpent, arg.MatchID, arg.PlayerID)
	var spent int64
	err := row.Scan(&spent)
	return spent, err
}

const setMatchBudgetSpent = `-- name: SetMatchBudgetSpent :execrows
UPDATE activity.match_budgets
SET spent = $1,
    updated_at = now()
WHERE match_id = $2 AND player_id = $3
`

type SetMatchBudgetSpentParams struct {
	Spent    int64
	MatchID  int64
	PlayerID int64
}

// **覆寫,不是增量**。權威值永遠是 RecalcMatchBudgetSpent 的 SUM;
// 用 spent = spent + cost 的話,任何一次漏算都會永遠留在資料裡,而且無法事後分辨。
//
// match_budgets_spent_check(0 <= spent <= budget)是超支的最後一道保險:
// 應用層已經擋過,但呼叫順序一旦有 bug,DB 會當場擋下來,而不是讓比賽帶著錯的 BP 開打。
// :execrows 讓 adapter 分得出「預算列不存在」(0 列)與「寫成功」。
func (q *Queries) SetMatchBudgetSpent(ctx context.Context, arg SetMatchBudgetSpentParams) (int64, error) {
	result, err := q.db.Exec(ctx, setMatchBudgetSpent, arg.Spent, arg.MatchID, arg.PlayerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
