// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: adminecon.sql

package db

import (
	"context"
)

const getTokenEntryByID = `-- name: GetTokenEntryByID :one

SELECT id, user_id, currency, amount, reason, ref_type, ref_id, actor_id, created_at, community_id, scope FROM platform.token_entries WHERE id = $1
`

// 管理員經濟操作 query。動錢一律走 ledger 的 ApplyInTx,這裡只有讀取;
// audit 寫入用 audit.sql 的 InsertAdminAudit,不重複定義。
// 退款前讀原分錄(分區表,依 id 掃全分區;管理操作低頻,可接受)
func (q *Queries) GetTokenEntryByID(ctx context.Context, id int64) (PlatformTokenEntry, error) {
	row := q.db.QueryRow(ctx, getTokenEntryByID, id)
	var i PlatformTokenEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Currency,
		&i.Amount,
		&i.Reason,
		&i.RefType,
		&i.RefID,
		&i.ActorID,
		&i.CreatedAt,
		&i.CommunityID,
		&i.Scope,
	)
	return i, err
}
