// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
)

const insertAdminAudit = `-- name: InsertAdminAudit :one
INSERT INTO platform.admin_audit_logs
  (actor_user_id, action, target_type, target_id, before, after, reason)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type InsertAdminAuditParams struct {
	ActorUserID int64
	Action      string
	TargetType  *string
	TargetID    *int64
	Before      []byte
	After       []byte
	Reason      string
}

// reason NOT NULL 是刻意的:強迫動作當下寫理由(schemas/03)
func (q *Queries) InsertAdminAudit(ctx context.Context, arg InsertAdminAuditParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertAdminAudit,
		arg.ActorUserID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Before,
		arg.After,
		arg.Reason,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listAdminAuditByActor = `-- name: ListAdminAuditByActor :many
SELECT id, actor_user_id, action, target_type, target_id, before, after, reason, created_at FROM platform.admin_audit_logs
WHERE actor_user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListAdminAuditByActorParams struct {
	ActorUserID int64
	Limit       int32
}

func (q *Queries) ListAdminAuditByActor(ctx context.Context, arg ListAdminAuditByActorParams) ([]PlatformAdminAuditLog, error) {
	rows, err := q.db.Query(ctx, listAdminAuditByActor, arg.ActorUserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlatformAdminAuditLog
	for rows.Next() {
		var i PlatformAdminAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Before,
			&i.After,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
