// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chunker.sql

package db

import (
	"context"
)

const insertConversationChunks = `-- name: InsertConversationChunks :execrows
WITH watermark AS (
  SELECT space_id, channel_id, thread_id, max(ended_at) AS last_ended_at
  FROM platform.conversation_chunks
  GROUP BY space_id, channel_id, thread_id
),
eligible AS (
  SELECT m.id, m.space_id, m.channel_id, m.thread_id, m.user_id, m.created_at, m.excerpt
  FROM platform.message_logs m
  JOIN platform.space_channels sc
    ON sc.space_id = m.space_id
   AND sc.external_id = m.channel_id
   AND sc.log_messages
  LEFT JOIN platform.user_privacy_settings p ON p.user_id = m.user_id
  LEFT JOIN watermark w
    ON w.space_id = m.space_id
   AND w.channel_id = m.channel_id
   AND w.thread_id IS NOT DISTINCT FROM m.thread_id
  WHERE m.deleted_at IS NULL
    AND m.excerpt IS NOT NULL
    AND COALESCE(p.opt_out_ai_corpus, false) = false
    -- Bot 排除:schema 沒有 is_bot 欄位,唯一能用的帳號性質訊號是「有沒有綁第三方身分」。
    -- Bot / webhook / 系統帳號不會走 OAuth 綁定流程,因此沒有 identities 列。
    -- 這是縱深防禦,第一道仍在寫入端(閘道本來就不該把 bot 訊息寫進 message_logs)。
    AND EXISTS (SELECT 1 FROM platform.identities i WHERE i.user_id = m.user_id)
    AND (w.last_ended_at IS NULL OR m.created_at > w.last_ended_at)
    AND length(regexp_replace(
          regexp_replace(m.excerpt, '<a?:[^:>]+:[0-9]+>|<[@#][!&]?[0-9]+>', '', 'g'),
          '[^[:alnum:]]', '', 'g')) >= $4::int
),
marked AS (
  SELECT e.id, e.space_id, e.channel_id, e.thread_id, e.user_id, e.created_at, e.excerpt,
    CASE WHEN e.created_at - lag(e.created_at) OVER (
           PARTITION BY e.space_id, e.channel_id, e.thread_id
           ORDER BY e.created_at, e.id
         ) > make_interval(mins => $1::int)
    THEN 1 ELSE 0 END AS is_break
  FROM eligible e
),
grouped AS (
  -- 累加斷點數 = chunk 序號。ROWS 框架是必要的:預設的 RANGE 框架遇到同一時刻的
  -- 多則訊息會把它們的 is_break 一起算進來,序號就會跳。
  SELECT m.id, m.space_id, m.channel_id, m.thread_id, m.user_id, m.created_at, m.excerpt, m.is_break, sum(m.is_break) OVER (
    PARTITION BY m.space_id, m.channel_id, m.thread_id
    ORDER BY m.created_at, m.id
    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS chunk_no
  FROM marked m
),
agg AS (
  SELECT space_id, channel_id, thread_id,
         min(created_at)::timestamptz              AS started_at,
         max(created_at)::timestamptz              AS ended_at,
         count(*)::int                             AS message_count,
         array_agg(DISTINCT user_id)::bigint[]     AS participant_user_ids,
         string_agg(excerpt, E'\n' ORDER BY created_at, id)::text AS text
  FROM grouped
  GROUP BY space_id, channel_id, thread_id, chunk_no
)
INSERT INTO platform.conversation_chunks
  (space_id, channel_id, thread_id, started_at, ended_at,
   participant_user_ids, message_count, text)
SELECT a.space_id, a.channel_id, a.thread_id, a.started_at, a.ended_at,
       a.participant_user_ids, a.message_count, a.text
FROM agg a
WHERE a.ended_at <= now() - make_interval(mins => $1::int)
  AND a.message_count >= $2::int
  AND length(a.text) >= $3::int
  -- 第二道防重:水位線之外的保險(例如水位線被手動清掉時)。
  AND NOT EXISTS (
    SELECT 1 FROM platform.conversation_chunks c
    WHERE c.space_id = a.space_id
      AND c.channel_id = a.channel_id
      AND c.thread_id IS NOT DISTINCT FROM a.thread_id
      AND c.started_at = a.started_at)
`

type InsertConversationChunksParams struct {
	GapMinutes      int32
	MinMessages     int32
	MinChunkChars   int32
	MinMessageChars int32
}

// 聚合規則:同 space + channel + thread,相鄰(合格)訊息間隔超過 chunk_gap_minutes 即斷開。
//
// 排除(schemas/12 明列)——都在 eligible 這層做掉,被排除的訊息也不參與斷句判定:
//  1. 未註冊/未開 log_messages 的頻道:語料範圍跟隨白名單(schemas/01 增補 C),不另設旗標;
//  2. opt_out_ai_corpus 使用者:只踢掉他的發言,同段對話其他人的仍保留;
//  3. Bot / 無第三方身分綁定的系統帳號:見 EXISTS(identities) 的註解;
//  4. 已刪訊息(deleted_at):使用者刪掉的內容不進長期語料;
//  5. 純表情 / 極短訊息:剝掉 Discord 自訂表情與 mention 標記後,
//     有意義字元(alnum,含 CJK)少於 min_message_chars 的一律不算發言。
//
// 只寫「已封閉」的 chunk(ended_at 已超過一個 gap):還在 gap 內的尾段可能再有人發言,
// 現在寫下去就會把同一段對話切成兩個 chunk——這是整個 job 最關鍵的一條。
//
// 冪等:watermark = 每個 (space, channel, thread) 已產生 chunk 的最大 ended_at,
// 只處理它之後的訊息。訊息本身可能因保留期被刪,水位線留在 chunks 表裡才不會漂移。
// embed_model / embedded_at 刻意留 NULL:嵌入模型尚未選型(schemas/12 的 N 待定)。
// 它們的用途是「換模型時判斷哪些 chunk 要重算」——NULL = 從未嵌入,
// 值不等於現行模型 = 需重算。向量隨時能從 text 重建,所以現在只累積事實層。
func (q *Queries) InsertConversationChunks(ctx context.Context, arg InsertConversationChunksParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertConversationChunks,
		arg.GapMinutes,
		arg.MinMessages,
		arg.MinChunkChars,
		arg.MinMessageChars,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockChunkBuild = `-- name: LockChunkBuild :exec

SELECT pg_advisory_xact_lock(hashtext('chunker'), hashtext('build_chunks'))
`

// 對話 chunk 聚合(schemas/12-ai-corpus.md)。
// 設計核心:不對單則訊息做 embedding,合併成對話 chunk 才有檢索價值(grill Q16)。
//
// 一次執行 = 一句 SQL:分組、切段、過濾、寫入全在 DB 內完成。把訊息撈回應用層再切
// 會在「撈出來」與「寫回去」之間留下一個 race window,也會把整段對話搬過網路。
//
// 去識別化(schemas/12 的硬要求):participant_user_ids 只放內部 id,text 只放
// excerpt 本身——不含暱稱、不含發言者標記。chunk 是語意材料,不是逐字稿。
// 交易級 advisory lock:同時間只有一個 BuildChunks 在跑。
// conversation_chunks 目前沒有唯一約束(見 schemas/12),下面的 NOT EXISTS 在
// READ COMMITTED 下擋不住併發雙寫,防重的第一道權威因此是這把鎖。
// 用阻塞版(非 try):後到者等前者 commit 後再跑,會看見新的水位線而自然變成 no-op,
// 不會像 try 版那樣白白丟掉一輪工作。
func (q *Queries) LockChunkBuild(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockChunkBuild)
	return err
}
