// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: community.sql

package db

import (
	"context"
	"time"
)

const clearChannelPurpose = `-- name: ClearChannelPurpose :execrows
DELETE FROM platform.space_channel_purposes WHERE space_id = $1 AND purpose = $2
`

type ClearChannelPurposeParams struct {
	SpaceID int64
	Purpose string
}

func (q *Queries) ClearChannelPurpose(ctx context.Context, arg ClearChannelPurposeParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearChannelPurpose, arg.SpaceID, arg.Purpose)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createCommunity = `-- name: CreateCommunity :one

INSERT INTO platform.communities (public_id, name)
VALUES ($1, $2)
RETURNING id, public_id, name
`

type CreateCommunityParams struct {
	PublicID string
	Name     string
}

type CreateCommunityRow struct {
	ID       int64
	PublicID string
	Name     string
}

// 社群與空間的管理端查詢(cmd/admin)。
//
// 為什麼這幾支不在 activitylog.sql:那支是**執行期**的讀取路徑
// (guild → space,每則訊息都會走)。這裡是管理端的建立與列出,
// 頻率、權限、失敗後果都不同,混在一起會讓「哪些查詢在熱路徑上」看不出來。
//
// 目前唯一的呼叫端是 CLI。之後補管理 RPC 時直接複用這些查詢,
// 不要另外寫一份近義的 SQL(專案第 9 條)。
func (q *Queries) CreateCommunity(ctx context.Context, arg CreateCommunityParams) (CreateCommunityRow, error) {
	row := q.db.QueryRow(ctx, createCommunity, arg.PublicID, arg.Name)
	var i CreateCommunityRow
	err := row.Scan(&i.ID, &i.PublicID, &i.Name)
	return i, err
}

const createSpace = `-- name: CreateSpace :one
INSERT INTO platform.community_spaces (public_id, community_id, provider, external_id, name)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, public_id, community_id, name
`

type CreateSpaceParams struct {
	PublicID    string
	CommunityID int64
	Provider    string
	ExternalID  string
	Name        *string
}

type CreateSpaceRow struct {
	ID          int64
	PublicID    string
	CommunityID int64
	Name        *string
}

func (q *Queries) CreateSpace(ctx context.Context, arg CreateSpaceParams) (CreateSpaceRow, error) {
	row := q.db.QueryRow(ctx, createSpace,
		arg.PublicID,
		arg.CommunityID,
		arg.Provider,
		arg.ExternalID,
		arg.Name,
	)
	var i CreateSpaceRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.CommunityID,
		&i.Name,
	)
	return i, err
}

const ensureSpaceChannel = `-- name: EnsureSpaceChannel :exec
INSERT INTO platform.space_channels (space_id, external_id, name, kind)
VALUES ($1, $2, $3, $4)
ON CONFLICT (space_id, external_id) DO NOTHING
`

type EnsureSpaceChannelParams struct {
	SpaceID    int64
	ExternalID string
	Name       *string
	Kind       string
}

// 設定用途前先確保頻道在 space_channels 裡有一列。
// space_channel_purposes 對它有外鍵(打錯 channel id 當場擋下),但註冊頻道
// 原本是「要不要記訊息」的動作,不該因此多逼使用者跑一次指令 —— 缺就補建,
// 用欄位預設(不記內容、計 XP),與現行未註冊頻道的行為完全相同。
func (q *Queries) EnsureSpaceChannel(ctx context.Context, arg EnsureSpaceChannelParams) error {
	_, err := q.db.Exec(ctx, ensureSpaceChannel,
		arg.SpaceID,
		arg.ExternalID,
		arg.Name,
		arg.Kind,
	)
	return err
}

const getChannelForPurpose = `-- name: GetChannelForPurpose :one
SELECT channel_external_id FROM platform.space_channel_purposes
WHERE space_id = $1 AND purpose = $2
`

type GetChannelForPurposeParams struct {
	SpaceID int64
	Purpose string
}

// 投遞時用:這個空間的這個用途要貼到哪個頻道。
// 查無列 = 沒設定,呼叫端應略過而不是報錯(部署可能刻意不設某個用途)。
func (q *Queries) GetChannelForPurpose(ctx context.Context, arg GetChannelForPurposeParams) (string, error) {
	row := q.db.QueryRow(ctx, getChannelForPurpose, arg.SpaceID, arg.Purpose)
	var channel_external_id string
	err := row.Scan(&channel_external_id)
	return channel_external_id, err
}

const getCommunityByPublicID = `-- name: GetCommunityByPublicID :one
SELECT id, public_id, name FROM platform.communities WHERE public_id = $1
`

type GetCommunityByPublicIDRow struct {
	ID       int64
	PublicID string
	Name     string
}

func (q *Queries) GetCommunityByPublicID(ctx context.Context, publicID string) (GetCommunityByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, getCommunityByPublicID, publicID)
	var i GetCommunityByPublicIDRow
	err := row.Scan(&i.ID, &i.PublicID, &i.Name)
	return i, err
}

const getSpaceByProviderExternalID = `-- name: GetSpaceByProviderExternalID :one
SELECT id, public_id, community_id, name FROM platform.community_spaces
WHERE provider = $1 AND external_id = $2
`

type GetSpaceByProviderExternalIDParams struct {
	Provider   string
	ExternalID string
}

type GetSpaceByProviderExternalIDRow struct {
	ID          int64
	PublicID    string
	CommunityID int64
	Name        *string
}

// 註冊前先查:CLI 重跑不該噴 UNIQUE violation,也不該無聲改掉既有設定。
func (q *Queries) GetSpaceByProviderExternalID(ctx context.Context, arg GetSpaceByProviderExternalIDParams) (GetSpaceByProviderExternalIDRow, error) {
	row := q.db.QueryRow(ctx, getSpaceByProviderExternalID, arg.Provider, arg.ExternalID)
	var i GetSpaceByProviderExternalIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.CommunityID,
		&i.Name,
	)
	return i, err
}

const listChannelPurposes = `-- name: ListChannelPurposes :many
SELECT key, name, description, enabled FROM platform.channel_purposes
WHERE enabled ORDER BY key
`

type ListChannelPurposesRow struct {
	Key         string
	Name        string
	Description *string
	Enabled     bool
}

func (q *Queries) ListChannelPurposes(ctx context.Context) ([]ListChannelPurposesRow, error) {
	rows, err := q.db.Query(ctx, listChannelPurposes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelPurposesRow
	for rows.Next() {
		var i ListChannelPurposesRow
		if err := rows.Scan(
			&i.Key,
			&i.Name,
			&i.Description,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommunities = `-- name: ListCommunities :many
SELECT id, public_id, name, xp_ruleset_id, created_at
FROM platform.communities ORDER BY id
`

type ListCommunitiesRow struct {
	ID          int64
	PublicID    string
	Name        string
	XpRulesetID *int64
	CreatedAt   time.Time
}

func (q *Queries) ListCommunities(ctx context.Context) ([]ListCommunitiesRow, error) {
	rows, err := q.db.Query(ctx, listCommunities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommunitiesRow
	for rows.Next() {
		var i ListCommunitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Name,
			&i.XpRulesetID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpaceChannels = `-- name: ListSpaceChannels :many
SELECT id, external_id, name, kind, log_messages, grant_xp, archived_at
FROM platform.space_channels WHERE space_id = $1 ORDER BY id
`

type ListSpaceChannelsRow struct {
	ID          int64
	ExternalID  string
	Name        *string
	Kind        string
	LogMessages bool
	GrantXp     bool
	ArchivedAt  *time.Time
}

func (q *Queries) ListSpaceChannels(ctx context.Context, spaceID int64) ([]ListSpaceChannelsRow, error) {
	rows, err := q.db.Query(ctx, listSpaceChannels, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSpaceChannelsRow
	for rows.Next() {
		var i ListSpaceChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Name,
			&i.Kind,
			&i.LogMessages,
			&i.GrantXp,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpacePurposes = `-- name: ListSpacePurposes :many
SELECT p.purpose, p.channel_external_id, cp.name AS purpose_name
FROM platform.space_channel_purposes p
JOIN platform.channel_purposes cp ON cp.key = p.purpose
WHERE p.space_id = $1 ORDER BY p.purpose
`

type ListSpacePurposesRow struct {
	Purpose           string
	ChannelExternalID string
	PurposeName       string
}

func (q *Queries) ListSpacePurposes(ctx context.Context, spaceID int64) ([]ListSpacePurposesRow, error) {
	rows, err := q.db.Query(ctx, listSpacePurposes, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSpacePurposesRow
	for rows.Next() {
		var i ListSpacePurposesRow
		if err := rows.Scan(&i.Purpose, &i.ChannelExternalID, &i.PurposeName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpaces = `-- name: ListSpaces :many
SELECT s.id, s.public_id, s.community_id, s.provider, s.external_id, s.name,
       c.name AS community_name, c.public_id AS community_public_id
FROM platform.community_spaces s
JOIN platform.communities c ON c.id = s.community_id
ORDER BY s.id
`

type ListSpacesRow struct {
	ID                int64
	PublicID          string
	CommunityID       int64
	Provider          string
	ExternalID        string
	Name              *string
	CommunityName     string
	CommunityPublicID string
}

func (q *Queries) ListSpaces(ctx context.Context) ([]ListSpacesRow, error) {
	rows, err := q.db.Query(ctx, listSpaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSpacesRow
	for rows.Next() {
		var i ListSpacesRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.CommunityID,
			&i.Provider,
			&i.ExternalID,
			&i.Name,
			&i.CommunityName,
			&i.CommunityPublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setChannelPurpose = `-- name: SetChannelPurpose :one
INSERT INTO platform.space_channel_purposes (space_id, purpose, channel_external_id)
VALUES ($1, $2, $3)
ON CONFLICT (space_id, purpose) DO UPDATE
SET channel_external_id = EXCLUDED.channel_external_id,
    updated_at          = now()
RETURNING id, purpose, channel_external_id
`

type SetChannelPurposeParams struct {
	SpaceID           int64
	Purpose           string
	ChannelExternalID string
}

type SetChannelPurposeRow struct {
	ID                int64
	Purpose           string
	ChannelExternalID string
}

func (q *Queries) SetChannelPurpose(ctx context.Context, arg SetChannelPurposeParams) (SetChannelPurposeRow, error) {
	row := q.db.QueryRow(ctx, setChannelPurpose, arg.SpaceID, arg.Purpose, arg.ChannelExternalID)
	var i SetChannelPurposeRow
	err := row.Scan(&i.ID, &i.Purpose, &i.ChannelExternalID)
	return i, err
}

const upsertSpaceChannel = `-- name: UpsertSpaceChannel :one
INSERT INTO platform.space_channels (space_id, external_id, name, kind, log_messages, grant_xp)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (space_id, external_id) DO UPDATE SET
  name         = EXCLUDED.name,
  kind         = EXCLUDED.kind,
  log_messages = EXCLUDED.log_messages,
  grant_xp     = EXCLUDED.grant_xp,
  archived_at  = NULL
RETURNING id, external_id, name, kind, log_messages, grant_xp
`

type UpsertSpaceChannelParams struct {
	SpaceID     int64
	ExternalID  string
	Name        *string
	Kind        string
	LogMessages bool
	GrantXp     bool
}

type UpsertSpaceChannelRow struct {
	ID          int64
	ExternalID  string
	Name        *string
	Kind        string
	LogMessages bool
	GrantXp     bool
}

// 這裡用 upsert 而不是「先查再建」,是因為重跑的語意不同:再跑一次
// register-channel 帶不同旗標,意思就是「改成這樣」。
// archived_at 一併清掉:重新註冊等於重新啟用。
func (q *Queries) UpsertSpaceChannel(ctx context.Context, arg UpsertSpaceChannelParams) (UpsertSpaceChannelRow, error) {
	row := q.db.QueryRow(ctx, upsertSpaceChannel,
		arg.SpaceID,
		arg.ExternalID,
		arg.Name,
		arg.Kind,
		arg.LogMessages,
		arg.GrantXp,
	)
	var i UpsertSpaceChannelRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Name,
		&i.Kind,
		&i.LogMessages,
		&i.GrantXp,
	)
	return i, err
}
