// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: config.sql

package db

import (
	"context"
	"time"
)

const getCurrentConfig = `-- name: GetCurrentConfig :one

SELECT value FROM platform.economy_configs
WHERE key = $1 AND effective_at <= now()
ORDER BY effective_at DESC
LIMIT 1
`

// 經濟設定:不覆寫舊值,讀取取「生效時間最新」的一筆
func (q *Queries) GetCurrentConfig(ctx context.Context, key string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getCurrentConfig, key)
	var value []byte
	err := row.Scan(&value)
	return value, err
}

const insertConfig = `-- name: InsertConfig :one
INSERT INTO platform.economy_configs (key, value, effective_at, created_by, note)
VALUES ($1, $2, COALESCE($5::timestamptz, now()), $3, $4)
RETURNING id, key, value, effective_at, created_by, note
`

type InsertConfigParams struct {
	Key         string
	Value       []byte
	CreatedBy   *int64
	Note        *string
	EffectiveAt *time.Time
}

// 調整 = 插新列(必帶 created_by;seed 列 created_by 為 NULL)
func (q *Queries) InsertConfig(ctx context.Context, arg InsertConfigParams) (PlatformEconomyConfig, error) {
	row := q.db.QueryRow(ctx, insertConfig,
		arg.Key,
		arg.Value,
		arg.CreatedBy,
		arg.Note,
		arg.EffectiveAt,
	)
	var i PlatformEconomyConfig
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Value,
		&i.EffectiveAt,
		&i.CreatedBy,
		&i.Note,
	)
	return i, err
}

const listCurrentConfigs = `-- name: ListCurrentConfigs :many
SELECT DISTINCT ON (key) key, value, effective_at
FROM platform.economy_configs
WHERE effective_at <= now()
ORDER BY key, effective_at DESC
`

type ListCurrentConfigsRow struct {
	Key         string
	Value       []byte
	EffectiveAt time.Time
}

func (q *Queries) ListCurrentConfigs(ctx context.Context) ([]ListCurrentConfigsRow, error) {
	rows, err := q.db.Query(ctx, listCurrentConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrentConfigsRow
	for rows.Next() {
		var i ListCurrentConfigsRow
		if err := rows.Scan(&i.Key, &i.Value, &i.EffectiveAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
