// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daily.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDailyState = `-- name: GetDailyState :one
SELECT user_id, current_streak, best_streak, last_claim_date, updated_at FROM platform.user_daily_state WHERE user_id = $1
`

func (q *Queries) GetDailyState(ctx context.Context, userID int64) (PlatformUserDailyState, error) {
	row := q.db.QueryRow(ctx, getDailyState, userID)
	var i PlatformUserDailyState
	err := row.Scan(
		&i.UserID,
		&i.CurrentStreak,
		&i.BestStreak,
		&i.LastClaimDate,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDailyClaim = `-- name: InsertDailyClaim :one

INSERT INTO platform.daily_claims (user_id, claim_date, timezone, streak, amount, source)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING user_id, claim_date, claimed_at, timezone, streak, amount, source
`

type InsertDailyClaimParams struct {
	UserID    int64
	ClaimDate pgtype.Date
	Timezone  string
	Streak    int32
	Amount    int64
	Source    string
}

// 簽到:防連點靠 daily_claims 的 PK(user_id, claim_date),不用冪等鍵(ledger-invariants 第三條)
func (q *Queries) InsertDailyClaim(ctx context.Context, arg InsertDailyClaimParams) (PlatformDailyClaim, error) {
	row := q.db.QueryRow(ctx, insertDailyClaim,
		arg.UserID,
		arg.ClaimDate,
		arg.Timezone,
		arg.Streak,
		arg.Amount,
		arg.Source,
	)
	var i PlatformDailyClaim
	err := row.Scan(
		&i.UserID,
		&i.ClaimDate,
		&i.ClaimedAt,
		&i.Timezone,
		&i.Streak,
		&i.Amount,
		&i.Source,
	)
	return i, err
}

const upsertDailyState = `-- name: UpsertDailyState :exec
INSERT INTO platform.user_daily_state (user_id, current_streak, best_streak, last_claim_date, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (user_id) DO UPDATE
SET current_streak = EXCLUDED.current_streak,
    best_streak    = GREATEST(platform.user_daily_state.best_streak, EXCLUDED.best_streak),
    last_claim_date = EXCLUDED.last_claim_date,
    updated_at     = now()
`

type UpsertDailyStateParams struct {
	UserID        int64
	CurrentStreak int32
	BestStreak    int32
	LastClaimDate pgtype.Date
}

func (q *Queries) UpsertDailyState(ctx context.Context, arg UpsertDailyStateParams) error {
	_, err := q.db.Exec(ctx, upsertDailyState,
		arg.UserID,
		arg.CurrentStreak,
		arg.BestStreak,
		arg.LastClaimDate,
	)
	return err
}
