// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daily.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDailyState = `-- name: GetDailyState :one
SELECT user_id, current_streak, best_streak, last_claim_date, updated_at FROM platform.user_daily_state WHERE user_id = $1
`

func (q *Queries) GetDailyState(ctx context.Context, userID int64) (PlatformUserDailyState, error) {
	row := q.db.QueryRow(ctx, getDailyState, userID)
	var i PlatformUserDailyState
	err := row.Scan(
		&i.UserID,
		&i.CurrentStreak,
		&i.BestStreak,
		&i.LastClaimDate,
		&i.UpdatedAt,
	)
	return i, err
}

const getLastDailyClaim = `-- name: GetLastDailyClaim :one
SELECT user_id, claim_date, claimed_at, timezone, streak, amount, source FROM platform.daily_claims
WHERE user_id = $1
ORDER BY claimed_at DESC
LIMIT 1
`

// 最近一次簽到(依絕對時間),供改時區冷卻檢查(timezone_change_min_gap_hours)比對 claimed_at
func (q *Queries) GetLastDailyClaim(ctx context.Context, userID int64) (PlatformDailyClaim, error) {
	row := q.db.QueryRow(ctx, getLastDailyClaim, userID)
	var i PlatformDailyClaim
	err := row.Scan(
		&i.UserID,
		&i.ClaimDate,
		&i.ClaimedAt,
		&i.Timezone,
		&i.Streak,
		&i.Amount,
		&i.Source,
	)
	return i, err
}

const insertDailyClaim = `-- name: InsertDailyClaim :one

INSERT INTO platform.daily_claims (user_id, claim_date, timezone, streak, amount, source)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING user_id, claim_date, claimed_at, timezone, streak, amount, source
`

type InsertDailyClaimParams struct {
	UserID    int64
	ClaimDate pgtype.Date
	Timezone  string
	Streak    int32
	Amount    int64
	Source    string
}

// 簽到:防連點靠 daily_claims 的 PK(user_id, claim_date),不用冪等鍵(ledger-invariants 第三條)
func (q *Queries) InsertDailyClaim(ctx context.Context, arg InsertDailyClaimParams) (PlatformDailyClaim, error) {
	row := q.db.QueryRow(ctx, insertDailyClaim,
		arg.UserID,
		arg.ClaimDate,
		arg.Timezone,
		arg.Streak,
		arg.Amount,
		arg.Source,
	)
	var i PlatformDailyClaim
	err := row.Scan(
		&i.UserID,
		&i.ClaimDate,
		&i.ClaimedAt,
		&i.Timezone,
		&i.Streak,
		&i.Amount,
		&i.Source,
	)
	return i, err
}

const lockUserForDaily = `-- name: LockUserForDaily :one
SELECT timezone, timezone_changed_at FROM platform.users
WHERE id = $1 AND deleted_at IS NULL
FOR UPDATE
`

type LockUserForDailyRow struct {
	Timezone          string
	TimezoneChangedAt *time.Time
}

// 串行化同一使用者的併發 Claim:跨當地午夜(或併發改時區)時兩個 tx 可能算出
// 不同 claim_date,單靠 PK 擋不住(streak 誤算、20h 閘門可繞過)。
// 先鎖 users 列,之後的冷卻/streak 讀取全在鎖後;PK 仍是防連點的最終防線。
func (q *Queries) LockUserForDaily(ctx context.Context, id int64) (LockUserForDailyRow, error) {
	row := q.db.QueryRow(ctx, lockUserForDaily, id)
	var i LockUserForDailyRow
	err := row.Scan(&i.Timezone, &i.TimezoneChangedAt)
	return i, err
}

const upsertDailyState = `-- name: UpsertDailyState :exec
INSERT INTO platform.user_daily_state (user_id, current_streak, best_streak, last_claim_date, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (user_id) DO UPDATE
SET current_streak = EXCLUDED.current_streak,
    best_streak    = GREATEST(platform.user_daily_state.best_streak, EXCLUDED.best_streak),
    last_claim_date = EXCLUDED.last_claim_date,
    updated_at     = now()
`

type UpsertDailyStateParams struct {
	UserID        int64
	CurrentStreak int32
	BestStreak    int32
	LastClaimDate pgtype.Date
}

func (q *Queries) UpsertDailyState(ctx context.Context, arg UpsertDailyStateParams) error {
	_, err := q.db.Exec(ctx, upsertDailyState,
		arg.UserID,
		arg.CurrentStreak,
		arg.BestStreak,
		arg.LastClaimDate,
	)
	return err
}
