// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: eventlog.sql

package db

import (
	"context"
)

const insertEventLog = `-- name: InsertEventLog :exec

INSERT INTO platform.event_logs (
  request_id, channel, kind, action, user_id, space_id,
  status, error_code, latency_ms, request, response, trace_id
) VALUES (
  $1, $2, $3, $4,
  $5, $6,
  $7, $8, $9,
  $10, $11, $12
)
`

type InsertEventLogParams struct {
	RequestID *string
	Channel   string
	Kind      string
	Action    string
	UserID    *int64
	SpaceID   *int64
	Status    *string
	ErrorCode *string
	LatencyMs *int32
	Request   []byte
	Response  []byte
	TraceID   *string
}

// 入口層操作紀錄(schemas/13-event-logs.md)。所有進到系統的動作——API / gRPC /
// Discord bot / webhook / 排程——都在這張表留痕,由各入口的攔截器統一寫,
// **不在業務碼裡手刻**。內容不存這裡(訊息 = message_logs、錢 = token_entries、
// 管理 = admin_audit_logs);這張只記「發生過什麼操作、誰、結果、多慢」。
//
// request / response 是白名單摘要:只放路由層級資訊與業務 public_id,
// 絕不放 token、密碼或完整 payload。
// 只有 INSERT:操作紀錄寫下去就不改(同帳本的 append-only 精神),
// 到期整個分區 DROP,不做逐列刪除。
func (q *Queries) InsertEventLog(ctx context.Context, arg InsertEventLogParams) error {
	_, err := q.db.Exec(ctx, insertEventLog,
		arg.RequestID,
		arg.Channel,
		arg.Kind,
		arg.Action,
		arg.UserID,
		arg.SpaceID,
		arg.Status,
		arg.ErrorCode,
		arg.LatencyMs,
		arg.Request,
		arg.Response,
		arg.TraceID,
	)
	return err
}
