// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package db

import (
	"context"
	"net/netip"
	"time"
)

const cleanupSessions = `-- name: CleanupSessions :execrows
DELETE FROM platform.sessions
WHERE COALESCE(revoked_at, expires_at) < now() - make_interval(days => $1::int)
`

// 膨脹歸宿(schemas/14)。條件形態**原樣**對齊表達式索引 sessions_retention_idx,
// 改寫成 (revoked_at < ... OR expires_at < ...) 會退化成全表掃描。
// 起算點 COALESCE(revoked_at, expires_at) 保證只命中「已撤銷或已過期」的列:
// 截止線早於 now(),未撤銷且未過期的列不可能落在它之前。
// rotated_from 的子列指標由 FK 的 ON DELETE SET NULL 自動斷開,不會撞 FK。
func (q *Queries) CleanupSessions(ctx context.Context, retentionDays int32) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupSessions, retentionDays)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensurePrivacySettings = `-- name: EnsurePrivacySettings :exec
INSERT INTO platform.user_privacy_settings (user_id) VALUES ($1)
ON CONFLICT (user_id) DO NOTHING
`

// 預設列(兩級 optout 都是 false)。ON CONFLICT DO NOTHING:重跑不炸。
func (q *Queries) EnsurePrivacySettings(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, ensurePrivacySettings, userID)
	return err
}

const getLocalIdentity = `-- name: GetLocalIdentity :one

SELECT i.id         AS identity_id,
       i.secret_hash,
       u.id         AS user_id,
       u.deleted_at AS user_deleted_at
FROM platform.identities i
JOIN platform.users u ON u.id = i.user_id
WHERE i.provider = 'local' AND i.provider_user_id = $1
`

type GetLocalIdentityRow struct {
	IdentityID    int64
	SecretHash    *string
	UserID        int64
	UserDeletedAt *time.Time
}

// ── 本地登入(provider='local',migration 00031)────────────────────────────
//
// 只有 local 身分會有 secret_hash。OAuth 身分的那一欄永遠是 NULL,
// 所以下面每一支都把 provider = 'local' 寫進 WHERE ——
// 少了它,一個 Discord 帳號的 provider_user_id(snowflake)就成了可猜測的登入名。
// 本地登入的唯一讀取點。
//
// 刻意不過濾 users.deleted_at:軟刪除的帳號必須讓應用層看見並走「憑證不正確」
// 那條路(含誘餌雜湊),查不到就直接短路的話,已註銷的登入名會回得比較快,
// 而那個時間差就是一支帳號列舉器。
func (q *Queries) GetLocalIdentity(ctx context.Context, loginName string) (GetLocalIdentityRow, error) {
	row := q.db.QueryRow(ctx, getLocalIdentity, loginName)
	var i GetLocalIdentityRow
	err := row.Scan(
		&i.IdentityID,
		&i.SecretHash,
		&i.UserID,
		&i.UserDeletedAt,
	)
	return i, err
}

const getLoginIdentity = `-- name: GetLoginIdentity :one

SELECT i.id            AS identity_id,
       i.username      AS identity_username,
       u.id            AS user_id,
       u.public_id     AS user_public_id,
       u.deleted_at    AS user_deleted_at
FROM platform.identities i
JOIN platform.users u ON u.id = i.user_id
WHERE i.provider = $1 AND i.provider_user_id = $2
`

type GetLoginIdentityParams struct {
	Provider       string
	ProviderUserID string
}

type GetLoginIdentityRow struct {
	IdentityID       int64
	IdentityUsername *string
	UserID           int64
	UserPublicID     string
	UserDeletedAt    *time.Time
}

// 身分層(schemas/02):OAuth2 登入、身分綁定、登入 session(增補 F)。
//
// 兩個 token 概念不要混:
//
//	identities.access_token_enc / refresh_token_enc = Discord 發給我們的憑證(加密存)
//	sessions.refresh_token_hash                     = 使用者登入我們系統的憑證(只存 SHA-256)
//
// 「有效 session」在本檔案只有一個定義,所有查詢一律照抄:
//
//	revoked_at IS NULL AND expires_at > now() AND users.deleted_at IS NULL
//
// 第三個條件 schema 表達不了(跨表),只能靠查詢契約——漏掉就是「軟刪除的帳號
// 仍能無限滑動續期」。
// 登入時查既有綁定。刻意不過濾 deleted_at:軟刪除的使用者仍佔著
// UNIQUE(provider, provider_user_id),必須讓應用層看見並明確拒絕,
// 而不是查不到就再建一個 user(那會撞唯一鍵)。
func (q *Queries) GetLoginIdentity(ctx context.Context, arg GetLoginIdentityParams) (GetLoginIdentityRow, error) {
	row := q.db.QueryRow(ctx, getLoginIdentity, arg.Provider, arg.ProviderUserID)
	var i GetLoginIdentityRow
	err := row.Scan(
		&i.IdentityID,
		&i.IdentityUsername,
		&i.UserID,
		&i.UserPublicID,
		&i.UserDeletedAt,
	)
	return i, err
}

const getSessionByRefreshHash = `-- name: GetSessionByRefreshHash :one
SELECT s.id, s.user_id, s.expires_at, s.revoked_at, s.revoked_reason,
       s.expires_at <= now() AS is_expired,
       u.deleted_at AS user_deleted_at
FROM platform.sessions s
JOIN platform.users u ON u.id = s.user_id
WHERE s.refresh_token_hash = $1
`

type GetSessionByRefreshHashRow struct {
	ID            int64
	UserID        int64
	ExpiresAt     time.Time
	RevokedAt     *time.Time
	RevokedReason *string
	IsExpired     bool
	UserDeletedAt *time.Time
}

// refresh 的前置讀取。這裡讀到的狀態只用來「提早回錯」與取得 user_id;
// 「這個 token 只能換發一次」的權威是 sessions_rotated_from_uq(見 InsertSession),
// 不是這次讀取——先查後寫在併發下擋不住,唯一索引擋得住。
func (q *Queries) GetSessionByRefreshHash(ctx context.Context, refreshTokenHash []byte) (GetSessionByRefreshHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshHash, refreshTokenHash)
	var i GetSessionByRefreshHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.IsExpired,
		&i.UserDeletedAt,
	)
	return i, err
}

const getSessionIDByPublicID = `-- name: GetSessionIDByPublicID :one
SELECT id FROM platform.sessions
WHERE public_id = $1 AND user_id = $2
`

type GetSessionIDByPublicIDParams struct {
	PublicID string
	UserID   int64
}

// 「登出這台」的入口。帶 user_id 條件是越權防線(只知道 public_id 動不了別人的裝置);
// **刻意不帶 revoked_at IS NULL**:裝置清單上拿到的 public_id 可能在使用者按下登出
// 之前就被背景 refresh 輪替掉了(舊列 revoked、換了新 public_id)。
// 以它為起點展開輪替鏈才能撤到那台裝置目前真正在用的那一列。
func (q *Queries) GetSessionIDByPublicID(ctx context.Context, arg GetSessionIDByPublicIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, getSessionIDByPublicID, arg.PublicID, arg.UserID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getUserIDByPublicID = `-- name: GetUserIDByPublicID :one
SELECT id FROM platform.users
WHERE public_id = $1 AND deleted_at IS NULL
`

// access token 驗簽通過後把 public_id 解成內部 id(順帶擋掉已軟刪除的帳號)。
func (q *Queries) GetUserIDByPublicID(ctx context.Context, publicID string) (int64, error) {
	row := q.db.QueryRow(ctx, getUserIDByPublicID, publicID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getUserPublicID = `-- name: GetUserPublicID :one
SELECT public_id FROM platform.users
WHERE id = $1 AND deleted_at IS NULL
`

// 輪替時要把 public_id 放進新的 access token;順帶再擋一次軟刪除的帳號。
func (q *Queries) GetUserPublicID(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, getUserPublicID, id)
	var public_id string
	err := row.Scan(&public_id)
	return public_id, err
}

const grantRoleByKey = `-- name: GrantRoleByKey :execrows
INSERT INTO platform.user_roles (user_id, role_id, community_id, source)
SELECT $1, r.id, NULL, 'manual'
FROM platform.roles r
WHERE r.key = $2
ON CONFLICT (user_id, role_id, COALESCE(community_id, 0)) DO NOTHING
`

type GrantRoleByKeyParams struct {
	UserID  int64
	RoleKey string
}

// 授予全域角色(community_id IS NULL)。source='manual':之後同步 Discord
// 身分組時只撤 provider_sync,手動授予不受影響(migration 00004 的設計)。
// ON CONFLICT DO NOTHING 對齊 user_roles_uniq,重跑不炸。
func (q *Queries) GrantRoleByKey(ctx context.Context, arg GrantRoleByKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, grantRoleByKey, arg.UserID, arg.RoleKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertLocalIdentity = `-- name: InsertLocalIdentity :one
INSERT INTO platform.identities (user_id, provider, provider_user_id, username, secret_hash)
VALUES ($1, 'local', $2, $3, $4::text)
RETURNING id
`

type InsertLocalIdentityParams struct {
	UserID     int64
	LoginName  string
	Username   *string
	SecretHash string
}

// 建立本地身分。撞 UNIQUE(provider, provider_user_id) = 這個登入名已被用掉,
// 那是唯一權威(不靠先查後寫)。
func (q *Queries) InsertLocalIdentity(ctx context.Context, arg InsertLocalIdentityParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertLocalIdentity,
		arg.UserID,
		arg.LoginName,
		arg.Username,
		arg.SecretHash,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertLoginIdentity = `-- name: InsertLoginIdentity :one
INSERT INTO platform.identities
  (user_id, provider, provider_user_id, username, access_token_enc, refresh_token_enc, scope, expires_at)
VALUES ($1, $2, $3, $4,
        $5, $6, $7,
        $8)
RETURNING id
`

type InsertLoginIdentityParams struct {
	UserID          int64
	Provider        string
	ProviderUserID  string
	Username        *string
	AccessTokenEnc  []byte
	RefreshTokenEnc []byte
	Scope           *string
	ExpiresAt       *time.Time
}

func (q *Queries) InsertLoginIdentity(ctx context.Context, arg InsertLoginIdentityParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertLoginIdentity,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.Username,
		arg.AccessTokenEnc,
		arg.RefreshTokenEnc,
		arg.Scope,
		arg.ExpiresAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertLoginUser = `-- name: InsertLoginUser :one
INSERT INTO platform.users (public_id, display_name, avatar_url, email, last_seen_at)
VALUES ($1, $2, $3, $4, now())
RETURNING id, public_id
`

type InsertLoginUserParams struct {
	PublicID    string
	DisplayName *string
	AvatarUrl   *string
	Email       *string
}

type InsertLoginUserRow struct {
	ID       int64
	PublicID string
}

// 首次 OAuth 登入建立內部使用者(內部 id 是唯一權威,provider 帳號只是掛在上面的憑證)。
func (q *Queries) InsertLoginUser(ctx context.Context, arg InsertLoginUserParams) (InsertLoginUserRow, error) {
	row := q.db.QueryRow(ctx, insertLoginUser,
		arg.PublicID,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Email,
	)
	var i InsertLoginUserRow
	err := row.Scan(&i.ID, &i.PublicID)
	return i, err
}

const insertSession = `-- name: InsertSession :one
INSERT INTO platform.sessions
  (public_id, user_id, refresh_token_hash, expires_at, last_used_at, user_agent, ip, rotated_from)
VALUES ($1, $2, $3,
        now() + make_interval(days => $4::int),
        now(), $5, CAST($6 AS inet), $7)
RETURNING id, public_id, issued_at, expires_at
`

type InsertSessionParams struct {
	PublicID         string
	UserID           int64
	RefreshTokenHash []byte
	TtlDays          int32
	UserAgent        *string
	Ip               *netip.Addr
	RotatedFrom      *int64
}

type InsertSessionRow struct {
	ID        int64
	PublicID  string
	IssuedAt  time.Time
	ExpiresAt time.Time
}

// expires_at 用 **DB 時鐘**(應用機器時鐘漂移不該影響憑證壽命)。
// rotated_from 撞 sessions_rotated_from_uq = 這條 session 已經被輪替過一次,
// 也就是同一個 refresh token 被用了第二次 —— 呼叫端據此觸發重用偵測。
func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (InsertSessionRow, error) {
	row := q.db.QueryRow(ctx, insertSession,
		arg.PublicID,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.TtlDays,
		arg.UserAgent,
		arg.Ip,
		arg.RotatedFrom,
	)
	var i InsertSessionRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.IssuedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listActiveSessionIDs = `-- name: ListActiveSessionIDs :many
SELECT id FROM platform.sessions
WHERE user_id = $1 AND revoked_at IS NULL
ORDER BY id
`

func (q *Queries) ListActiveSessionIDs(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listActiveSessionIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserDevices = `-- name: ListUserDevices :many
SELECT s.public_id, s.user_agent, COALESCE(host(s.ip), '')::text AS ip,
       s.issued_at, s.last_used_at, s.expires_at
FROM platform.sessions s
JOIN platform.users u ON u.id = s.user_id
WHERE s.user_id = $1
  AND s.revoked_at IS NULL AND s.expires_at > now() AND u.deleted_at IS NULL
ORDER BY COALESCE(s.last_used_at, s.issued_at) DESC, s.id DESC
`

type ListUserDevicesRow struct {
	PublicID   string
	UserAgent  *string
	Ip         string
	IssuedAt   time.Time
	LastUsedAt *time.Time
	ExpiresAt  time.Time
}

// 有效 session 的定義照抄檔頭三條件(含 users.deleted_at)。
func (q *Queries) ListUserDevices(ctx context.Context, userID int64) ([]ListUserDevicesRow, error) {
	rows, err := q.db.Query(ctx, listUserDevices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserDevicesRow
	for rows.Next() {
		var i ListUserDevicesRow
		if err := rows.Scan(
			&i.PublicID,
			&i.UserAgent,
			&i.Ip,
			&i.IssuedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUserSessions = `-- name: LockUserSessions :exec

SELECT pg_advisory_xact_lock(hashtext('user_sessions'), ($1::bigint & 2147483647)::int)
`

// ── session(schemas/02 增補 F)────────────────────────────────────────────
// 同一使用者的 session 多列操作(輪替、全撤、重用偵測)一律先拿這把 xact advisory lock。
// 全系統同一把鎖、同一個取得時機 ⇒ 併發的多列操作被完全串行化,死鎖在結構上不可能,
// 同時關掉「封鎖進行中又發出新 session」的競態窗。
func (q *Queries) LockUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, lockUserSessions, userID)
	return err
}

const markSessionRotated = `-- name: MarkSessionRotated :execrows
UPDATE platform.sessions
SET revoked_at = now(), revoked_reason = 'rotated', last_used_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

// revoked_at / revoked_reason 成對寫入(CHECK sessions_revocation_paired)。
// 回傳列數是**必須檢查**的:0 列 = 舊列在前置讀取之後被撤銷(登出/封鎖),
// 此時整個 tx 必須回滾,不能讓新發的 session 從一條已死的鏈上長出來。
func (q *Queries) MarkSessionRotated(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, markSessionRotated, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSessionsByID = `-- name: RevokeSessionsByID :execrows
UPDATE platform.sessions
SET revoked_at = now(), revoked_reason = $1::text
WHERE id = ANY($2::bigint[]) AND revoked_at IS NULL
`

type RevokeSessionsByIDParams struct {
	RevokedReason string
	Ids           []int64
}

// 重用偵測 / 封鎖:把清單內**尚未撤銷**的列一次撤掉。
// 只動未撤銷的列不是保守,是必須:撤銷紀錄一旦寫下即為歷史
// (trigger sessions_revocation_is_final 會擋下覆寫),而已撤銷的列本來就已失效,
// 安全效果不變、稽核紀錄還保留了「當時是為什麼被撤的」。
// 呼叫端傳升冪 id;併發安全另由 LockUserSessions 保證。
func (q *Queries) RevokeSessionsByID(ctx context.Context, arg RevokeSessionsByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSessionsByID, arg.RevokedReason, arg.Ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sessionChainIDs = `-- name: SessionChainIDs :many
WITH RECURSIVE chain AS (
  SELECT s.id, s.rotated_from
  FROM platform.sessions s
  WHERE s.id = $1
  UNION
  SELECT s.id, s.rotated_from
  FROM platform.sessions s, chain c
  WHERE s.id = c.rotated_from OR s.rotated_from = c.id
)
SELECT id FROM chain ORDER BY id
`

// 輪替鏈:從任一列沿 rotated_from 往上(被取代者)與往下(取代者)展開整條。
// 複合 FK 保證整條鏈同屬一個使用者,不可能撤到別人的裝置。升冪回傳。
func (q *Queries) SessionChainIDs(ctx context.Context, sessionID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, sessionChainIDs, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchLoginUser = `-- name: TouchLoginUser :exec
UPDATE platform.users SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) TouchLoginUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchLoginUser, id)
	return err
}

const updateLocalSecret = `-- name: UpdateLocalSecret :execrows
UPDATE platform.identities
SET secret_hash = $1::text
WHERE provider = 'local' AND provider_user_id = $2
`

type UpdateLocalSecretParams struct {
	SecretHash string
	LoginName  string
}

// 重新產生通行碼(裁判忘記時的唯一修復路徑 —— 雜湊格式手寫不出來)。
// 回傳列數要檢查:0 列 = 這個登入名沒有本地身分,不能無聲當成成功。
func (q *Queries) UpdateLocalSecret(ctx context.Context, arg UpdateLocalSecretParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateLocalSecret, arg.SecretHash, arg.LoginName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateLoginIdentity = `-- name: UpdateLoginIdentity :exec
UPDATE platform.identities
SET username          = $1,
    access_token_enc  = $2,
    refresh_token_enc = $3,
    scope             = $4,
    expires_at        = $5
WHERE id = $6
`

type UpdateLoginIdentityParams struct {
	Username        *string
	AccessTokenEnc  []byte
	RefreshTokenEnc []byte
	Scope           *string
	ExpiresAt       *time.Time
	ID              int64
}

// 既有綁定重新登入:更新 provider 側的顯示名與憑證(內部 users 的資料不覆蓋——
// display_name 之後可由使用者自訂,provider 的名字權威在 identities.username)。
func (q *Queries) UpdateLoginIdentity(ctx context.Context, arg UpdateLoginIdentityParams) error {
	_, err := q.db.Exec(ctx, updateLoginIdentity,
		arg.Username,
		arg.AccessTokenEnc,
		arg.RefreshTokenEnc,
		arg.Scope,
		arg.ExpiresAt,
		arg.ID,
	)
	return err
}
