// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package db

import (
	"context"
	"time"
)

const applyBalanceDelta = `-- name: ApplyBalanceDelta :one
UPDATE platform.user_balances
SET balance = balance + $3, updated_at = now()
WHERE user_id = $1 AND currency = $2
  AND COALESCE(community_id, 0) = COALESCE($4::bigint, 0)
RETURNING balance
`

type ApplyBalanceDeltaParams struct {
	UserID      int64
	Currency    string
	Balance     int64
	CommunityID *int64
}

// 呼叫前必須已 LockBalanceForUpdate;CHECK(balance >= 0) 是最後防線,不是主要檢查
func (q *Queries) ApplyBalanceDelta(ctx context.Context, arg ApplyBalanceDeltaParams) (int64, error) {
	row := q.db.QueryRow(ctx, applyBalanceDelta,
		arg.UserID,
		arg.Currency,
		arg.Balance,
		arg.CommunityID,
	)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const claimPendingOutbox = `-- name: ClaimPendingOutbox :many
SELECT id, topic, payload, status, attempts, next_retry_at, created_at FROM platform.outbox_events
WHERE status = 'pending'
  AND (next_retry_at IS NULL OR next_retry_at <= now())
  -- COALESCE 不可省:topic <> ALL(NULL) 求值為 NULL 而非 true,
  -- 呼叫端沒傳清單時會變成「一筆都認領不到」,消費者靜默停擺。
  AND topic <> ALL(COALESCE($1::text[], ARRAY[]::text[]))
ORDER BY id
FOR UPDATE SKIP LOCKED
LIMIT $2
`

type ClaimPendingOutboxParams struct {
	ExcludedTopics []string
	RowLimit       int32
}

// 多實例安全消費:SKIP LOCKED
//
// excluded_topics 是「由別人負責投遞」的 topic(目前是閘道經 NotificationService
// 拉取的公告)。少了這段,in-process 消費者會認領它們、找不到 handler、
// 退避重試到上限後標 failed —— 閘道離線一小時,公告就被燒光了。
// 傳空陣列 = 全部都歸這個消費者(既有行為)。
func (q *Queries) ClaimPendingOutbox(ctx context.Context, arg ClaimPendingOutboxParams) ([]PlatformOutboxEvent, error) {
	rows, err := q.db.Query(ctx, claimPendingOutbox, arg.ExcludedTopics, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlatformOutboxEvent
	for rows.Next() {
		var i PlatformOutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.NextRetryAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ensureBalanceRow = `-- name: EnsureBalanceRow :exec
INSERT INTO platform.user_balances (user_id, currency, community_id, scope, balance)
SELECT $1, $2, $3::bigint, c.scope, 0
FROM platform.currencies c WHERE c.code = $2
ON CONFLICT (user_id, currency, COALESCE(community_id, 0)) DO NOTHING
`

type EnsureBalanceRowParams struct {
	UserID      int64
	Currency    string
	CommunityID *int64
}

func (q *Queries) EnsureBalanceRow(ctx context.Context, arg EnsureBalanceRowParams) error {
	_, err := q.db.Exec(ctx, ensureBalanceRow, arg.UserID, arg.Currency, arg.CommunityID)
	return err
}

const getBalance = `-- name: GetBalance :one
SELECT balance FROM platform.user_balances
WHERE user_id = $1 AND currency = $2
  AND COALESCE(community_id, 0) = COALESCE($3::bigint, 0)
`

type GetBalanceParams struct {
	UserID      int64
	Currency    string
	CommunityID *int64
}

func (q *Queries) GetBalance(ctx context.Context, arg GetBalanceParams) (int64, error) {
	row := q.db.QueryRow(ctx, getBalance, arg.UserID, arg.Currency, arg.CommunityID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT key, request_hash, response, created_at FROM platform.idempotency_keys WHERE key = $1
`

func (q *Queries) GetIdempotencyKey(ctx context.Context, key string) (PlatformIdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, key)
	var i PlatformIdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.RequestHash,
		&i.Response,
		&i.CreatedAt,
	)
	return i, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :exec
INSERT INTO platform.idempotency_keys (key, request_hash, response)
VALUES ($1, $2, $3)
`

type InsertIdempotencyKeyParams struct {
	Key         string
	RequestHash string
	Response    []byte
}

// 與動錢同一個 transaction 寫入(見 ledger-invariants 第三條)。
// 在 tx 開頭先插(response 先 NULL),讓併發同 key 的第二個 tx 直接撞 PK;
// tx 若 rollback,key 同步消失,合法重試不會被擋。
func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, insertIdempotencyKey, arg.Key, arg.RequestHash, arg.Response)
	return err
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :one
INSERT INTO platform.outbox_events (topic, payload)
VALUES ($1, $2)
RETURNING id
`

type InsertOutboxEventParams struct {
	Topic   string
	Payload []byte
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertOutboxEvent, arg.Topic, arg.Payload)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertTokenEntry = `-- name: InsertTokenEntry :one
INSERT INTO platform.token_entries
  (user_id, currency, community_id, scope, amount, reason, ref_type, ref_id, actor_id)
SELECT $1, $2, $8::bigint, c.scope, $3, $4, $5, $6, $7
FROM platform.currencies c WHERE c.code = $2
RETURNING id, created_at
`

type InsertTokenEntryParams struct {
	UserID      int64
	Currency    string
	Amount      int64
	Reason      string
	RefType     *string
	RefID       *int64
	ActorID     *int64
	CommunityID *int64
}

type InsertTokenEntryRow struct {
	ID        int64
	CreatedAt time.Time
}

func (q *Queries) InsertTokenEntry(ctx context.Context, arg InsertTokenEntryParams) (InsertTokenEntryRow, error) {
	row := q.db.QueryRow(ctx, insertTokenEntry,
		arg.UserID,
		arg.Currency,
		arg.Amount,
		arg.Reason,
		arg.RefType,
		arg.RefID,
		arg.ActorID,
		arg.CommunityID,
	)
	var i InsertTokenEntryRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listEntriesByUser = `-- name: ListEntriesByUser :many
SELECT id, user_id, currency, amount, reason, ref_type, ref_id, actor_id, created_at, community_id, scope FROM platform.token_entries
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListEntriesByUserParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

func (q *Queries) ListEntriesByUser(ctx context.Context, arg ListEntriesByUserParams) ([]PlatformTokenEntry, error) {
	rows, err := q.db.Query(ctx, listEntriesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlatformTokenEntry
	for rows.Next() {
		var i PlatformTokenEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Currency,
			&i.Amount,
			&i.Reason,
			&i.RefType,
			&i.RefID,
			&i.ActorID,
			&i.CreatedAt,
			&i.CommunityID,
			&i.Scope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBalanceForUpdate = `-- name: LockBalanceForUpdate :one


SELECT balance FROM platform.user_balances
WHERE user_id = $1 AND currency = $2
  AND COALESCE(community_id, 0) = COALESCE($3::bigint, 0)
FOR UPDATE
`

type LockBalanceForUpdateParams struct {
	UserID      int64
	Currency    string
	CommunityID *int64
}

// 帳本 query。使用規則見 .claude/skills/ledger-invariants:
// append-only、同 transaction 更新餘額、鎖依 user_id 升冪、動錢一律冪等。
// 這裡刻意「沒有」UPDATE/DELETE token_entries 的 query —— 不要新增。
// 餘額與分錄都帶 community_id(schemas/23):NULL = 全域幣。
// 每一支都用 COALESCE(community_id, 0) 比對,因為 NULL = NULL 為 NULL 而不是 true——
// 直接寫 community_id = $3 會讓全域幣的每一次查詢都查不到列,
// 而那個 bug 的表現是「餘額突然變 0」,不是報錯。
//
// scope 一律由 currencies 現查,不由呼叫端傳:它必須等於 currencies.scope
// (複合外鍵擋著),讓呼叫端傳就是給了一個唯一的錯法。
func (q *Queries) LockBalanceForUpdate(ctx context.Context, arg LockBalanceForUpdateParams) (int64, error) {
	row := q.db.QueryRow(ctx, lockBalanceForUpdate, arg.UserID, arg.Currency, arg.CommunityID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const markOutboxDone = `-- name: MarkOutboxDone :exec
UPDATE platform.outbox_events SET status = 'done' WHERE id = $1
`

func (q *Queries) MarkOutboxDone(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markOutboxDone, id)
	return err
}

const markOutboxFailed = `-- name: MarkOutboxFailed :exec
UPDATE platform.outbox_events
SET status = 'failed', attempts = attempts + 1
WHERE id = $1
`

// 毒訊息終態:超過重試上限,不能卡住整條佇列
func (q *Queries) MarkOutboxFailed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markOutboxFailed, id)
	return err
}

const markOutboxRetry = `-- name: MarkOutboxRetry :exec
UPDATE platform.outbox_events
SET attempts = attempts + 1,
    next_retry_at = now() + make_interval(secs => $1::int)
WHERE id = $2
`

type MarkOutboxRetryParams struct {
	DelaySeconds int32
	ID           int64
}

// 退避時間由 DB 時鐘計算(單一時鐘來源,QA:app/DB 時鐘偏移會讓事件被提前取走)
func (q *Queries) MarkOutboxRetry(ctx context.Context, arg MarkOutboxRetryParams) error {
	_, err := q.db.Exec(ctx, markOutboxRetry, arg.DelaySeconds, arg.ID)
	return err
}

const reconcileBalances = `-- name: ReconcileBalances :many
SELECT
  COALESCE(b.user_id, s.user_id)::bigint        AS user_id,
  COALESCE(b.currency, s.currency)::text        AS currency,
  -- 補 0 而不是讓它是 NULL:community id 從 1 起算,0 明確代表全域幣。
  -- 留 NULL 的話這一欄要變成指標型別,而對帳報告的每個使用點都得多一次解參照,
  -- 換來的只是重述「全域」這件 scope 已經說過的事。
  COALESCE(b.community_id, s.community_id, 0)::bigint AS community_key,
  COALESCE(b.balance, 0)::bigint                AS balance,
  COALESCE(s.total, 0)::bigint                  AS entry_total
FROM platform.user_balances b
FULL JOIN (
  SELECT user_id, currency, community_id, SUM(amount) AS total
  FROM platform.token_entries
  GROUP BY user_id, currency, community_id
) s ON s.user_id = b.user_id
   AND s.currency = b.currency
   AND COALESCE(s.community_id, 0) = COALESCE(b.community_id, 0)
WHERE COALESCE(b.balance, 0) <> COALESCE(s.total, 0)
`

type ReconcileBalancesRow struct {
	UserID       int64
	Currency     string
	CommunityKey int64
	Balance      int64
	EntryTotal   int64
}

// 對帳:找出 SUM(entries) 與 balance 不一致的每一組(含只有分錄沒有餘額列、或反之)
//
// **分組必須含 community**:少了它,SUM 會把同一個人在所有社群的分錄加在一起,
// 而那個總和幾乎永遠不等於任何單一列的 balance —— 對帳會變成全表誤報,
// 比不對帳更糟(沒有人會再相信它)。
func (q *Queries) ReconcileBalances(ctx context.Context) ([]ReconcileBalancesRow, error) {
	rows, err := q.db.Query(ctx, reconcileBalances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReconcileBalancesRow
	for rows.Next() {
		var i ReconcileBalancesRow
		if err := rows.Scan(
			&i.UserID,
			&i.Currency,
			&i.CommunityKey,
			&i.Balance,
			&i.EntryTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setIdempotencyResponse = `-- name: SetIdempotencyResponse :exec
UPDATE platform.idempotency_keys SET response = $2 WHERE key = $1
`

type SetIdempotencyResponseParams struct {
	Key      string
	Response []byte
}

func (q *Queries) SetIdempotencyResponse(ctx context.Context, arg SetIdempotencyResponseParams) error {
	_, err := q.db.Exec(ctx, setIdempotencyResponse, arg.Key, arg.Response)
	return err
}

const sumEntriesForUser = `-- name: SumEntriesForUser :one
SELECT COALESCE(SUM(amount), 0)::bigint AS total
FROM platform.token_entries
WHERE user_id = $1 AND currency = $2
  AND COALESCE(community_id, 0) = COALESCE($3::bigint, 0)
`

type SumEntriesForUserParams struct {
	UserID      int64
	Currency    string
	CommunityID *int64
}

// 對帳 job 用:驗證 SUM(entries) = balance
func (q *Queries) SumEntriesForUser(ctx context.Context, arg SumEntriesForUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumEntriesForUser, arg.UserID, arg.Currency, arg.CommunityID)
	var total int64
	err := row.Scan(&total)
	return total, err
}
