// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package db

import (
	"context"
	"time"
)

const applyBalanceDelta = `-- name: ApplyBalanceDelta :one
UPDATE platform.user_balances
SET balance = balance + $3, updated_at = now()
WHERE user_id = $1 AND currency = $2
RETURNING balance
`

type ApplyBalanceDeltaParams struct {
	UserID   int64
	Currency string
	Balance  int64
}

// 呼叫前必須已 LockBalanceForUpdate;CHECK(balance >= 0) 是最後防線,不是主要檢查
func (q *Queries) ApplyBalanceDelta(ctx context.Context, arg ApplyBalanceDeltaParams) (int64, error) {
	row := q.db.QueryRow(ctx, applyBalanceDelta, arg.UserID, arg.Currency, arg.Balance)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const claimPendingOutbox = `-- name: ClaimPendingOutbox :many
SELECT id, topic, payload, status, attempts, next_retry_at, created_at FROM platform.outbox_events
WHERE status = 'pending' AND (next_retry_at IS NULL OR next_retry_at <= now())
ORDER BY id
FOR UPDATE SKIP LOCKED
LIMIT $1
`

// 多實例安全消費:SKIP LOCKED
func (q *Queries) ClaimPendingOutbox(ctx context.Context, limit int32) ([]PlatformOutboxEvent, error) {
	rows, err := q.db.Query(ctx, claimPendingOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlatformOutboxEvent
	for rows.Next() {
		var i PlatformOutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.NextRetryAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ensureBalanceRow = `-- name: EnsureBalanceRow :exec
INSERT INTO platform.user_balances (user_id, currency, balance)
VALUES ($1, $2, 0)
ON CONFLICT (user_id, currency) DO NOTHING
`

type EnsureBalanceRowParams struct {
	UserID   int64
	Currency string
}

func (q *Queries) EnsureBalanceRow(ctx context.Context, arg EnsureBalanceRowParams) error {
	_, err := q.db.Exec(ctx, ensureBalanceRow, arg.UserID, arg.Currency)
	return err
}

const getBalance = `-- name: GetBalance :one
SELECT balance FROM platform.user_balances
WHERE user_id = $1 AND currency = $2
`

type GetBalanceParams struct {
	UserID   int64
	Currency string
}

func (q *Queries) GetBalance(ctx context.Context, arg GetBalanceParams) (int64, error) {
	row := q.db.QueryRow(ctx, getBalance, arg.UserID, arg.Currency)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT key, request_hash, response, created_at FROM platform.idempotency_keys WHERE key = $1
`

func (q *Queries) GetIdempotencyKey(ctx context.Context, key string) (PlatformIdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, key)
	var i PlatformIdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.RequestHash,
		&i.Response,
		&i.CreatedAt,
	)
	return i, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :exec
INSERT INTO platform.idempotency_keys (key, request_hash, response)
VALUES ($1, $2, $3)
`

type InsertIdempotencyKeyParams struct {
	Key         string
	RequestHash string
	Response    []byte
}

// 與動錢同一個 transaction 寫入(見 ledger-invariants 第三條)。
// 在 tx 開頭先插(response 先 NULL),讓併發同 key 的第二個 tx 直接撞 PK;
// tx 若 rollback,key 同步消失,合法重試不會被擋。
func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, insertIdempotencyKey, arg.Key, arg.RequestHash, arg.Response)
	return err
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :one
INSERT INTO platform.outbox_events (topic, payload)
VALUES ($1, $2)
RETURNING id
`

type InsertOutboxEventParams struct {
	Topic   string
	Payload []byte
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertOutboxEvent, arg.Topic, arg.Payload)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertTokenEntry = `-- name: InsertTokenEntry :one
INSERT INTO platform.token_entries (user_id, currency, amount, reason, ref_type, ref_id, actor_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, created_at
`

type InsertTokenEntryParams struct {
	UserID   int64
	Currency string
	Amount   int64
	Reason   string
	RefType  *string
	RefID    *int64
	ActorID  *int64
}

type InsertTokenEntryRow struct {
	ID        int64
	CreatedAt time.Time
}

func (q *Queries) InsertTokenEntry(ctx context.Context, arg InsertTokenEntryParams) (InsertTokenEntryRow, error) {
	row := q.db.QueryRow(ctx, insertTokenEntry,
		arg.UserID,
		arg.Currency,
		arg.Amount,
		arg.Reason,
		arg.RefType,
		arg.RefID,
		arg.ActorID,
	)
	var i InsertTokenEntryRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listEntriesByUser = `-- name: ListEntriesByUser :many
SELECT id, user_id, currency, amount, reason, ref_type, ref_id, actor_id, created_at FROM platform.token_entries
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListEntriesByUserParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

func (q *Queries) ListEntriesByUser(ctx context.Context, arg ListEntriesByUserParams) ([]PlatformTokenEntry, error) {
	rows, err := q.db.Query(ctx, listEntriesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlatformTokenEntry
	for rows.Next() {
		var i PlatformTokenEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Currency,
			&i.Amount,
			&i.Reason,
			&i.RefType,
			&i.RefID,
			&i.ActorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBalanceForUpdate = `-- name: LockBalanceForUpdate :one

SELECT balance FROM platform.user_balances
WHERE user_id = $1 AND currency = $2
FOR UPDATE
`

type LockBalanceForUpdateParams struct {
	UserID   int64
	Currency string
}

// 帳本 query。使用規則見 .claude/skills/ledger-invariants:
// append-only、同 transaction 更新餘額、鎖依 user_id 升冪、動錢一律冪等。
// 這裡刻意「沒有」UPDATE/DELETE token_entries 的 query —— 不要新增。
func (q *Queries) LockBalanceForUpdate(ctx context.Context, arg LockBalanceForUpdateParams) (int64, error) {
	row := q.db.QueryRow(ctx, lockBalanceForUpdate, arg.UserID, arg.Currency)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const markOutboxDone = `-- name: MarkOutboxDone :exec
UPDATE platform.outbox_events SET status = 'done' WHERE id = $1
`

func (q *Queries) MarkOutboxDone(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markOutboxDone, id)
	return err
}

const markOutboxFailed = `-- name: MarkOutboxFailed :exec
UPDATE platform.outbox_events
SET status = 'failed', attempts = attempts + 1
WHERE id = $1
`

// 毒訊息終態:超過重試上限,不能卡住整條佇列
func (q *Queries) MarkOutboxFailed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markOutboxFailed, id)
	return err
}

const markOutboxRetry = `-- name: MarkOutboxRetry :exec
UPDATE platform.outbox_events
SET attempts = attempts + 1, next_retry_at = $2
WHERE id = $1
`

type MarkOutboxRetryParams struct {
	ID          int64
	NextRetryAt *time.Time
}

func (q *Queries) MarkOutboxRetry(ctx context.Context, arg MarkOutboxRetryParams) error {
	_, err := q.db.Exec(ctx, markOutboxRetry, arg.ID, arg.NextRetryAt)
	return err
}

const reconcileBalances = `-- name: ReconcileBalances :many
SELECT
  COALESCE(b.user_id, s.user_id)::bigint   AS user_id,
  COALESCE(b.currency, s.currency)::text   AS currency,
  COALESCE(b.balance, 0)::bigint           AS balance,
  COALESCE(s.total, 0)::bigint             AS entry_total
FROM platform.user_balances b
FULL JOIN (
  SELECT user_id, currency, SUM(amount) AS total
  FROM platform.token_entries
  GROUP BY user_id, currency
) s ON s.user_id = b.user_id AND s.currency = b.currency
WHERE COALESCE(b.balance, 0) <> COALESCE(s.total, 0)
`

type ReconcileBalancesRow struct {
	UserID     int64
	Currency   string
	Balance    int64
	EntryTotal int64
}

// 對帳:找出 SUM(entries) 與 balance 不一致的每一組(含只有分錄沒有餘額列、或反之)
func (q *Queries) ReconcileBalances(ctx context.Context) ([]ReconcileBalancesRow, error) {
	rows, err := q.db.Query(ctx, reconcileBalances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReconcileBalancesRow
	for rows.Next() {
		var i ReconcileBalancesRow
		if err := rows.Scan(
			&i.UserID,
			&i.Currency,
			&i.Balance,
			&i.EntryTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setIdempotencyResponse = `-- name: SetIdempotencyResponse :exec
UPDATE platform.idempotency_keys SET response = $2 WHERE key = $1
`

type SetIdempotencyResponseParams struct {
	Key      string
	Response []byte
}

func (q *Queries) SetIdempotencyResponse(ctx context.Context, arg SetIdempotencyResponseParams) error {
	_, err := q.db.Exec(ctx, setIdempotencyResponse, arg.Key, arg.Response)
	return err
}

const sumEntriesForUser = `-- name: SumEntriesForUser :one
SELECT COALESCE(SUM(amount), 0)::bigint AS total
FROM platform.token_entries
WHERE user_id = $1 AND currency = $2
`

type SumEntriesForUserParams struct {
	UserID   int64
	Currency string
}

// 對帳 job 用:驗證 SUM(entries) = balance
func (q *Queries) SumEntriesForUser(ctx context.Context, arg SumEntriesForUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumEntriesForUser, arg.UserID, arg.Currency)
	var total int64
	err := row.Scan(&total)
	return total, err
}
