// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maintenance.sql

package db

import (
	"context"
)

const cleanupIdempotencyKeys = `-- name: CleanupIdempotencyKeys :execrows
DELETE FROM platform.idempotency_keys
WHERE created_at < now() - make_interval(days => $1::int)
`

// 語意代價(接受):超過窗口的重送不再被識別為重放——30 天遠大於任何合法重試窗口
func (q *Queries) CleanupIdempotencyKeys(ctx context.Context, retentionDays int32) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupIdempotencyKeys, retentionDays)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cleanupOutboxEvents = `-- name: CleanupOutboxEvents :execrows
DELETE FROM platform.outbox_events
WHERE status IN ('done', 'failed')
  AND created_at < now() - make_interval(days => $1::int)
`

// 終態事件(done/failed)逾保留期即刪;pending 永不動(schemas/14)
func (q *Queries) CleanupOutboxEvents(ctx context.Context, retentionDays int32) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupOutboxEvents, retentionDays)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureMonthPartitions = `-- name: EnsureMonthPartitions :exec
SELECT platform.ensure_month_partitions()
`

// 為 platform schema 所有分區表補齊本月與下月分區(migration 00001 的函式)
func (q *Queries) EnsureMonthPartitions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, ensureMonthPartitions)
	return err
}

const insertJobRunLog = `-- name: InsertJobRunLog :exec

INSERT INTO platform.event_logs (channel, kind, action, status, latency_ms, response)
VALUES ('system', 'job.run', $1, $2, $3, $4)
`

type InsertJobRunLogParams struct {
	Action    string
	Status    *string
	LatencyMs *int32
	Response  []byte
}

// maintenance 排程器(schemas/14):job 執行紀錄、advisory lock、分區與列級清理。
// 分區到期偵測(pg_inherits catalog,sqlc 解析不了系統目錄)與 DROP TABLE(動態 DDL)
// 無法走 sqlc,實作在 maintenance 套件內(partition.go)。
// 每次 job 執行寫一列 event_logs(schemas/13 的 job.run 在此兌現;失敗也要記)
func (q *Queries) InsertJobRunLog(ctx context.Context, arg InsertJobRunLogParams) error {
	_, err := q.db.Exec(ctx, insertJobRunLog,
		arg.Action,
		arg.Status,
		arg.LatencyMs,
		arg.Response,
	)
	return err
}

const maintenanceUnlock = `-- name: MaintenanceUnlock :exec
SELECT pg_advisory_unlock(hashtext('maintenance'), hashtext($1::text))
`

func (q *Queries) MaintenanceUnlock(ctx context.Context, jobName string) error {
	_, err := q.db.Exec(ctx, maintenanceUnlock, jobName)
	return err
}

const tryMaintenanceLock = `-- name: TryMaintenanceLock :one
SELECT pg_try_advisory_lock(hashtext('maintenance'), hashtext($1::text))
`

// session-level advisory lock:同名 job 多實例只有一個能跑,拿不到就跳過本輪。
// 必須在同一條連線上執行 TryMaintenanceLock / MaintenanceUnlock(排程器用 pool.Acquire 釘住連線)。
func (q *Queries) TryMaintenanceLock(ctx context.Context, jobName string) (bool, error) {
	row := q.db.QueryRow(ctx, tryMaintenanceLock, jobName)
	var pg_try_advisory_lock bool
	err := row.Scan(&pg_try_advisory_lock)
	return pg_try_advisory_lock, err
}
