// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: market.sql

package db

import (
	"context"
	"time"
)

const getItemDefinitionByID = `-- name: GetItemDefinitionByID :one

SELECT id, public_id, name, category, tradable, bind_on_acquire, max_supply, minted_count
FROM platform.item_definitions
WHERE id = $1
`

type GetItemDefinitionByIDRow struct {
	ID            int64
	PublicID      string
	Name          string
	Category      string
	Tradable      bool
	BindOnAcquire bool
	MaxSupply     *int32
	MintedCount   int32
}

// ══ 物品定義與發放 ══
func (q *Queries) GetItemDefinitionByID(ctx context.Context, id int64) (GetItemDefinitionByIDRow, error) {
	row := q.db.QueryRow(ctx, getItemDefinitionByID, id)
	var i GetItemDefinitionByIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Category,
		&i.Tradable,
		&i.BindOnAcquire,
		&i.MaxSupply,
		&i.MintedCount,
	)
	return i, err
}

const getItemDefinitionByPublicID = `-- name: GetItemDefinitionByPublicID :one
SELECT id, public_id, name, category, tradable, bind_on_acquire, max_supply, minted_count
FROM platform.item_definitions
WHERE public_id = $1
`

type GetItemDefinitionByPublicIDRow struct {
	ID            int64
	PublicID      string
	Name          string
	Category      string
	Tradable      bool
	BindOnAcquire bool
	MaxSupply     *int32
	MintedCount   int32
}

func (q *Queries) GetItemDefinitionByPublicID(ctx context.Context, publicID string) (GetItemDefinitionByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, getItemDefinitionByPublicID, publicID)
	var i GetItemDefinitionByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Category,
		&i.Tradable,
		&i.BindOnAcquire,
		&i.MaxSupply,
		&i.MintedCount,
	)
	return i, err
}

const getListingByPublicID = `-- name: GetListingByPublicID :one
SELECT id, public_id, seller_id, item_instance_id, currency, price, status, listed_at, expires_at
FROM platform.market_listings
WHERE public_id = $1
`

// 不加鎖:先讀出賣家是誰,才知道要鎖哪兩個 users 列(鎖序需要先知道鎖的集合)。
// 讀到的內容一律在取得列鎖後重新驗證,不當作判斷依據。
func (q *Queries) GetListingByPublicID(ctx context.Context, publicID string) (PlatformMarketListing, error) {
	row := q.db.QueryRow(ctx, getListingByPublicID, publicID)
	var i PlatformMarketListing
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.SellerID,
		&i.ItemInstanceID,
		&i.Currency,
		&i.Price,
		&i.Status,
		&i.ListedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getTradeEligibility = `-- name: GetTradeEligibility :one

SELECT
  u.id,
  COALESCE((SELECT MAX(x.level) FROM platform.user_xp x WHERE x.user_id = u.id), 0)::int AS level,
  COALESCE((SELECT (EXTRACT(EPOCH FROM (now() - MIN(m.joined_at))) / 86400)::int
            FROM platform.space_members m WHERE m.user_id = u.id), 0)::int AS member_days,
  (EXTRACT(EPOCH FROM (now() - u.created_at)) / 86400)::int AS account_age_days,
  (EXISTS (SELECT 1 FROM platform.user_restrictions r
            WHERE r.user_id = u.id AND r.kind = 'no_trade'
              AND r.lifted_at IS NULL
              AND (r.expires_at IS NULL OR r.expires_at > now())))::bool AS no_trade,
  COALESCE((SELECT SUM(o.price)
            FROM platform.market_orders o
            JOIN platform.market_listings l ON l.id = o.listing_id
            WHERE (o.buyer_id = u.id OR o.seller_id = u.id)
              AND l.currency = $1
              AND o.settled_at >= date_trunc('day', now() AT TIME ZONE u.timezone) AT TIME ZONE u.timezone
           ), 0)::bigint AS traded_today
FROM platform.users u
WHERE u.id = $2 AND u.deleted_at IS NULL
`

type GetTradeEligibilityParams struct {
	Currency string
	UserID   int64
}

type GetTradeEligibilityRow struct {
	ID             int64
	Level          int32
	MemberDays     int32
	AccountAgeDays int32
	NoTrade        bool
	TradedToday    int64
}

// ══ 防洗點:交易門檻 / 單日上限 / no_trade ══
// 一次算完一個人的交易資格(schemas/09「防洗點」四項的資料來源),全部用 DB 時鐘:
//
//	level            該使用者在各社群的最高等級(M1 只有一個社群;user_xp 是投影表)
//	member_days      入群天數 = now() − MIN(space_members.joined_at),離群不歸零(schemas/01 增補 B)
//	account_age_days 帳號年齡 = now() − users.created_at
//	no_trade         有無生效中的 no_trade 限制(未解除且未到期)
//	traded_today     當日已成交額(買 + 賣合計,同幣別):日界線用該使用者自己的時區,
//	                 與每日簽到的「一天」同義,不另立第二套日曆
func (q *Queries) GetTradeEligibility(ctx context.Context, arg GetTradeEligibilityParams) (GetTradeEligibilityRow, error) {
	row := q.db.QueryRow(ctx, getTradeEligibility, arg.Currency, arg.UserID)
	var i GetTradeEligibilityRow
	err := row.Scan(
		&i.ID,
		&i.Level,
		&i.MemberDays,
		&i.AccountAgeDays,
		&i.NoTrade,
		&i.TradedToday,
	)
	return i, err
}

const insertItemInstance = `-- name: InsertItemInstance :one
INSERT INTO platform.item_instances (public_id, definition_id, owner_id, bound, quantity, acquired_via)
VALUES ($1, $2, $3, $4, 1,
        $5)
RETURNING id, public_id, acquired_at
`

type InsertItemInstanceParams struct {
	PublicID     string
	DefinitionID int64
	OwnerID      int64
	Bound        bool
	AcquiredVia  *string
}

type InsertItemInstanceRow struct {
	ID         int64
	PublicID   string
	AcquiredAt time.Time
}

// quantity 固定 1:M1 不做 stackable 疊加(schemas/09 有欄位但沒有合併/拆分語意)。
func (q *Queries) InsertItemInstance(ctx context.Context, arg InsertItemInstanceParams) (InsertItemInstanceRow, error) {
	row := q.db.QueryRow(ctx, insertItemInstance,
		arg.PublicID,
		arg.DefinitionID,
		arg.OwnerID,
		arg.Bound,
		arg.AcquiredVia,
	)
	var i InsertItemInstanceRow
	err := row.Scan(&i.ID, &i.PublicID, &i.AcquiredAt)
	return i, err
}

const insertMarketListing = `-- name: InsertMarketListing :one

INSERT INTO platform.market_listings (public_id, seller_id, item_instance_id, currency, price, expires_at)
VALUES ($1, $2, $3,
        $4, $5, $6::timestamptz)
RETURNING id, public_id, seller_id, currency, price, status, listed_at, expires_at
`

type InsertMarketListingParams struct {
	PublicID       string
	SellerID       int64
	ItemInstanceID int64
	Currency       string
	Price          int64
	ExpiresAt      *time.Time
}

type InsertMarketListingRow struct {
	ID        int64
	PublicID  string
	SellerID  int64
	Currency  string
	Price     int64
	Status    string
	ListedAt  time.Time
	ExpiresAt *time.Time
}

// ══ 掛單 ══
func (q *Queries) InsertMarketListing(ctx context.Context, arg InsertMarketListingParams) (InsertMarketListingRow, error) {
	row := q.db.QueryRow(ctx, insertMarketListing,
		arg.PublicID,
		arg.SellerID,
		arg.ItemInstanceID,
		arg.Currency,
		arg.Price,
		arg.ExpiresAt,
	)
	var i InsertMarketListingRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.SellerID,
		&i.Currency,
		&i.Price,
		&i.Status,
		&i.ListedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertMarketOrder = `-- name: InsertMarketOrder :one

INSERT INTO platform.market_orders (listing_id, buyer_id, seller_id, price, fee)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, settled_at
`

type InsertMarketOrderParams struct {
	ListingID int64
	BuyerID   int64
	SellerID  int64
	Price     int64
	Fee       int64
}

type InsertMarketOrderRow struct {
	ID        int64
	SettledAt time.Time
}

// ══ 成交紀錄 ══
// 買賣雙方 + 金額 + 手續費全額記帳:任兩人的資金淨流向可查(防洗點稽核的資料來源)。
func (q *Queries) InsertMarketOrder(ctx context.Context, arg InsertMarketOrderParams) (InsertMarketOrderRow, error) {
	row := q.db.QueryRow(ctx, insertMarketOrder,
		arg.ListingID,
		arg.BuyerID,
		arg.SellerID,
		arg.Price,
		arg.Fee,
	)
	var i InsertMarketOrderRow
	err := row.Scan(&i.ID, &i.SettledAt)
	return i, err
}

const listUserItemInstances = `-- name: ListUserItemInstances :many
SELECT i.public_id, i.bound, i.quantity, i.acquired_at, i.acquired_via,
       (i.locked_by_trade_id IS NOT NULL)::bool AS locked,
       d.public_id AS definition_public_id, d.name, d.category, d.rarity, d.icon_url, d.tradable
FROM platform.item_instances i
JOIN platform.item_definitions d ON d.id = i.definition_id
WHERE i.owner_id = $1
ORDER BY i.acquired_at DESC, i.id DESC
`

type ListUserItemInstancesRow struct {
	PublicID           string
	Bound              bool
	Quantity           int32
	AcquiredAt         time.Time
	AcquiredVia        *string
	Locked             bool
	DefinitionPublicID string
	Name               string
	Category           string
	Rarity             *string
	IconUrl            *string
	Tradable           bool
}

// 使用者的物品清單(含定義資訊);locked 讓前端知道「正在賣,不能再掛」。
func (q *Queries) ListUserItemInstances(ctx context.Context, ownerID int64) ([]ListUserItemInstancesRow, error) {
	rows, err := q.db.Query(ctx, listUserItemInstances, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserItemInstancesRow
	for rows.Next() {
		var i ListUserItemInstancesRow
		if err := rows.Scan(
			&i.PublicID,
			&i.Bound,
			&i.Quantity,
			&i.AcquiredAt,
			&i.AcquiredVia,
			&i.Locked,
			&i.DefinitionPublicID,
			&i.Name,
			&i.Category,
			&i.Rarity,
			&i.IconUrl,
			&i.Tradable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockItemInstanceByID = `-- name: LockItemInstanceByID :one
SELECT i.id, i.public_id, i.definition_id, i.owner_id, i.bound, i.locked_by_trade_id,
       d.public_id AS definition_public_id, d.category, d.tradable, d.bind_on_acquire
FROM platform.item_instances i
JOIN platform.item_definitions d ON d.id = i.definition_id
WHERE i.id = $1
FOR UPDATE OF i
`

type LockItemInstanceByIDRow struct {
	ID                 int64
	PublicID           string
	DefinitionID       int64
	OwnerID            int64
	Bound              bool
	LockedByTradeID    *int64
	DefinitionPublicID string
	Category           string
	Tradable           bool
	BindOnAcquire      bool
}

func (q *Queries) LockItemInstanceByID(ctx context.Context, id int64) (LockItemInstanceByIDRow, error) {
	row := q.db.QueryRow(ctx, lockItemInstanceByID, id)
	var i LockItemInstanceByIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.DefinitionID,
		&i.OwnerID,
		&i.Bound,
		&i.LockedByTradeID,
		&i.DefinitionPublicID,
		&i.Category,
		&i.Tradable,
		&i.BindOnAcquire,
	)
	return i, err
}

const lockItemInstanceByPublicID = `-- name: LockItemInstanceByPublicID :one
SELECT i.id, i.public_id, i.definition_id, i.owner_id, i.bound, i.locked_by_trade_id,
       d.public_id AS definition_public_id, d.category, d.tradable, d.bind_on_acquire
FROM platform.item_instances i
JOIN platform.item_definitions d ON d.id = i.definition_id
WHERE i.public_id = $1
FOR UPDATE OF i
`

type LockItemInstanceByPublicIDRow struct {
	ID                 int64
	PublicID           string
	DefinitionID       int64
	OwnerID            int64
	Bound              bool
	LockedByTradeID    *int64
	DefinitionPublicID string
	Category           string
	Tradable           bool
	BindOnAcquire      bool
}

// FOR UPDATE OF i:只鎖實例列(同一件物品的掛單串行化),不鎖共享讀的定義列。
func (q *Queries) LockItemInstanceByPublicID(ctx context.Context, publicID string) (LockItemInstanceByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, lockItemInstanceByPublicID, publicID)
	var i LockItemInstanceByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.DefinitionID,
		&i.OwnerID,
		&i.Bound,
		&i.LockedByTradeID,
		&i.DefinitionPublicID,
		&i.Category,
		&i.Tradable,
		&i.BindOnAcquire,
	)
	return i, err
}

const lockItemInstanceForTrade = `-- name: LockItemInstanceForTrade :execrows
UPDATE platform.item_instances
SET locked_by_trade_id = $1::bigint
WHERE id = $2 AND locked_by_trade_id IS NULL
`

type LockItemInstanceForTradeParams struct {
	TradeID int64
	ID      int64
}

// 掛單成立時把物品鎖住;WHERE 的 IS NULL 是最後防線(呼叫端已持有列鎖並檢查過)。
func (q *Queries) LockItemInstanceForTrade(ctx context.Context, arg LockItemInstanceForTradeParams) (int64, error) {
	result, err := q.db.Exec(ctx, lockItemInstanceForTrade, arg.TradeID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockListingByID = `-- name: LockListingByID :one
SELECT id, public_id, seller_id, item_instance_id, currency, price, status, listed_at, expires_at,
       now()::timestamptz AS db_now
FROM platform.market_listings
WHERE id = $1
FOR UPDATE
`

type LockListingByIDRow struct {
	ID             int64
	PublicID       string
	SellerID       int64
	ItemInstanceID int64
	Currency       string
	Price          int64
	Status         string
	ListedAt       time.Time
	ExpiresAt      *time.Time
	DbNow          time.Time
}

// 同一張掛單的成交/取消串行化,後到者看到非 open 即拒絕。
// db_now 一併回傳:過期比對用 DB 時鐘,避免 app/DB 時鐘偏移誤判。
func (q *Queries) LockListingByID(ctx context.Context, id int64) (LockListingByIDRow, error) {
	row := q.db.QueryRow(ctx, lockListingByID, id)
	var i LockListingByIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.SellerID,
		&i.ItemInstanceID,
		&i.Currency,
		&i.Price,
		&i.Status,
		&i.ListedAt,
		&i.ExpiresAt,
		&i.DbNow,
	)
	return i, err
}

const lockListingByPublicID = `-- name: LockListingByPublicID :one
SELECT id, public_id, seller_id, item_instance_id, currency, price, status, listed_at, expires_at,
       now()::timestamptz AS db_now
FROM platform.market_listings
WHERE public_id = $1
FOR UPDATE
`

type LockListingByPublicIDRow struct {
	ID             int64
	PublicID       string
	SellerID       int64
	ItemInstanceID int64
	Currency       string
	Price          int64
	Status         string
	ListedAt       time.Time
	ExpiresAt      *time.Time
	DbNow          time.Time
}

func (q *Queries) LockListingByPublicID(ctx context.Context, publicID string) (LockListingByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, lockListingByPublicID, publicID)
	var i LockListingByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.SellerID,
		&i.ItemInstanceID,
		&i.Currency,
		&i.Price,
		&i.Status,
		&i.ListedAt,
		&i.ExpiresAt,
		&i.DbNow,
	)
	return i, err
}

const lockUserForTrade = `-- name: LockUserForTrade :one

SELECT id FROM platform.users
WHERE id = $1 AND deleted_at IS NULL
FOR UPDATE
`

// 物品與市集 query(schemas/09-items-market.md)。動錢一律經 ledger(marketpg 用 ApplyInTx
// 同 tx 綁定),這裡只有物品 / 掛單 / 成交紀錄側的讀寫;token_entries 一律不碰(append-only 鐵則)。
//
// 全域鎖序(與 shoppg / dailypg 同向,結構上不可能死鎖):
//
//	users → market_listings → item_instances → user_balances(user_id 升冪)
//
// 交易雙方的 users 列鎖:同一使用者的成交全序列化。
// 單日交易額上限與 API 冪等鍵的重放判定,都必須在「前一筆成交 commit 之後」
// 才有意義(READ COMMITTED 下先讀後寫會踩到舊快照)。呼叫端依 user_id 升冪呼叫。
func (q *Queries) LockUserForTrade(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockUserForTrade, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const mintDefinitionSupply = `-- name: MintDefinitionSupply :one
UPDATE platform.item_definitions
SET minted_count = minted_count + 1
WHERE id = $1
  AND (max_supply IS NULL OR minted_count < max_supply)
RETURNING id, public_id, name, category, tradable, bind_on_acquire, max_supply, minted_count
`

type MintDefinitionSupplyRow struct {
	ID            int64
	PublicID      string
	Name          string
	Category      string
	Tradable      bool
	BindOnAcquire bool
	MaxSupply     *int32
	MintedCount   int32
}

// 超發保護:檢查與遞增是**同一個敘述**,不是先查後寫。
// 併發時後到者在 UPDATE 取得列鎖後會依最新版本重跑 WHERE(READ COMMITTED 的
// EvalPlanQual),額度用完就是 0 rows —— 呼叫端據此回 ErrSupplyExhausted。
// max_supply IS NULL = 不限量,仍然遞增 minted_count(發行量要可查)。
func (q *Queries) MintDefinitionSupply(ctx context.Context, id int64) (MintDefinitionSupplyRow, error) {
	row := q.db.QueryRow(ctx, mintDefinitionSupply, id)
	var i MintDefinitionSupplyRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Category,
		&i.Tradable,
		&i.BindOnAcquire,
		&i.MaxSupply,
		&i.MintedCount,
	)
	return i, err
}

const transferItemInstance = `-- name: TransferItemInstance :execrows
UPDATE platform.item_instances
SET owner_id = $1,
    locked_by_trade_id = NULL,
    bound = $2,
    acquired_at = now(),
    acquired_via = 'market'
WHERE id = $3
  AND owner_id = $4
  AND locked_by_trade_id = $5::bigint
`

type TransferItemInstanceParams struct {
	NewOwnerID int64
	Bound      bool
	ID         int64
	SellerID   int64
	TradeID    int64
}

// 成交換手:owner 換人 + 清鎖 + 更新取得脈絡,單一敘述。
// WHERE 同時比對原持有人與鎖:鎖不指向本掛單就換不動(ledger-invariants 第五條)。
// bound 依定義的 bind_on_acquire 重新決定:交易後綁定的物品,新主人手上就是綁定的。
func (q *Queries) TransferItemInstance(ctx context.Context, arg TransferItemInstanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, transferItemInstance,
		arg.NewOwnerID,
		arg.Bound,
		arg.ID,
		arg.SellerID,
		arg.TradeID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unlockItemInstance = `-- name: UnlockItemInstance :execrows
UPDATE platform.item_instances
SET locked_by_trade_id = NULL
WHERE id = $1 AND locked_by_trade_id = $2::bigint
`

type UnlockItemInstanceParams struct {
	ID      int64
	TradeID int64
}

// 取消掛單時解鎖;只解本掛單放的鎖,不會誤解別人的。
func (q *Queries) UnlockItemInstance(ctx context.Context, arg UnlockItemInstanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, unlockItemInstance, arg.ID, arg.TradeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateListingStatus = `-- name: UpdateListingStatus :execrows
UPDATE platform.market_listings
SET status = $1
WHERE id = $2 AND status = 'open'
`

type UpdateListingStatusParams struct {
	Status string
	ID     int64
}

// 呼叫前必須已鎖住掛單列;WHERE status='open' 是狀態機單向的最後防線。
func (q *Queries) UpdateListingStatus(ctx context.Context, arg UpdateListingStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateListingStatus, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
