// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

// 注單。扣款經 Ledger(reason=bet_stake),與 INSERT 本列必須同一個 tx —— 這依賴 Ledger.ApplyInTx(外部傳入 tx)。activity 仍只透過 interface 動錢,邊界沒破。
type ActivityBet struct {
	ID                  int64
	PublicID            string
	TournamentID        int64
	UserID              int64
	Stake               int64
	PotentialPayout     int64
	Status              string
	LedgerStakeEntryID  *int64
	LedgerRefundEntryID *int64
	PayoutRecalculated  bool
	SettledAt           *time.Time
	CreatedAt           time.Time
}

// 串關的每一腿。同輪比賽彼此不共用選手,所以各腿天然無相關 —— 單淘汰的結構性保證。棄賽時該腿標 void 並從乘積中移除,剩餘腿仍用各自鎖定的 odds_milli 重算。
type ActivityBetLeg struct {
	ID        int64
	BetID     int64
	MatchID   int64
	Side      int16
	OddsMilli int64
	Result    string
}

// 跨屆選手檔案,以遊戲ID 為自然鍵。與 tournament_players 的分工:這裡是跨屆聚合,那裡是報名當下的快照 —— 因為「段位一經確認即為本屆計算依據」,本屆段位不能被下屆覆寫。
type ActivityFencer struct {
	ID                int64
	PublicID          string
	GameID            string
	UserID            *int64
	DiscordName       *string
	LastRankLevel     *int16
	LastRankedAt      *time.Time
	TournamentsPlayed int32
	Wins              int32
	Losses            int32
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

// 讓武項目:低段位者花 BP 施加在高段位者身上的正式比賽限制。與 platform 的收藏品是不同概念 —— 不可交易、逐屆定義、只在賽內有意義。
type ActivityHandicapItem struct {
	ID           int64
	TournamentID int64
	// 系統刻意不做互斥檢查(09-12 定案)。victory 類同時選多項會互相矛盾,但那由裁判臨場判 —— 前端只給非阻擋式提示,不擋購買。
	Category    string
	Name        string
	Description *string
	RefereeNote *string
	Cost        int64
	Repeatable  bool
	SortOrder   int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// 每次購買一列。退費只是 BP 內部的事(改 spent + 標 voided),不經 Ledger。外鍵指向 match_budgets 的複合鍵 —— 沒有預算的人連一列都插不進來。
type ActivityHandicapSelection struct {
	ID         int64
	PublicID   string
	MatchID    int64
	PlayerID   int64
	ItemID     int64
	Cost       int64
	TargetNote *string
	Voided     bool
	CreatedAt  time.Time
}

// 單淘汰賽程樹。round 1 = 首輪,slot 為該輪內 0-based 位置。同輪比賽彼此不共用選手 —— 這是串關天然無相關的結構性保證,不需要特判。
type ActivityMatch struct {
	ID               int64
	PublicID         string
	TournamentID     int64
	Round            int32
	Slot             int32
	P1PlayerID       *int64
	P2PlayerID       *int64
	WinnerPlayerID   *int64
	Status           string
	HandicapOpen     bool
	HandicapLockedAt *time.Time
	StreamUrl        *string
	ResultKind       string
	StartedAt        *time.Time
	FinishedAt       *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

// BP 預算。每輪配對後依當下段位差重算發放,該場有效,賽後作廢 —— 不跨輪累積、不找零。不進平台帳本、不走 Ledger、不需冪等:它不是貨幣。
type ActivityMatchBudget struct {
	MatchID   int64
	PlayerID  int64
	Budget    int64
	Spent     int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ActivityTournament struct {
	ID          int64
	PublicID    string
	Slug        string
	Name        string
	CommunityID int64
	// 階段限制一律在伺服器端驗證(requirePhase),前端變灰只是視覺。
	Phase       string
	Config      []byte
	SignupBonus int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ActivityTournamentPlayer struct {
	ID           int64
	PublicID     string
	TournamentID int64
	FencerID     int64
	UserID       *int64
	DisplayName  string
	// 本屆評定段位,1=開山 2=斷水 3=飛花 4=無我。一經確認即為本屆計算 BP 的依據。進入 drawing 階段後不可再改 —— BP 依段位差算出,抽籤後改段位會讓已發的 match_budgets 對不上。
	RankLevel        *int16
	RankedAt         *time.Time
	RankedBy         *int64
	PasscodeHash     string
	PasscodeIssuedAt time.Time
	DiscordName      string
	SelfRatedLevel   *int16
	LadderRank       *string
	LadderScore      *int32
	ArtsNote         *string
	AvailabilityNote *string
	SeedNo           *int32
	Status           string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

// 觀眾投票,驅動浮動賠率。隱含機率 = (該方票數 + SMOOTHING) / (總票數 + 2×SMOOTHING);賠率 = (1 − VIG) / 隱含機率,夾在 [MIN_ODDS, MAX_ODDS]。參數在 tournaments.config。
type ActivityVote struct {
	ID        int64
	MatchID   int64
	UserID    int64
	Side      int16
	CreatedAt time.Time
	UpdatedAt time.Time
}

type PlatformActivityDaily struct {
	UserID        int64
	CommunityID   int64
	Date          pgtype.Date
	Messages      int32
	Reactions     int32
	VoiceSeconds  int32
	OnlineSeconds int32
	FirstSeenAt   *time.Time
	LastSeenAt    *time.Time
	XpGained      int64
}

type PlatformAdminAuditLog struct {
	ID          int64
	ActorUserID int64
	Action      string
	TargetType  *string
	TargetID    *int64
	Before      []byte
	After       []byte
	Reason      string
	CreatedAt   time.Time
}

// 三處隨機(開箱 / 小遊戲 / 賽事下注)共用的留痕。三件事:(1) 隨時算得出實際產出速率,不必等到通膨才發現;(2) 有人質疑黑箱時拿得出種子與賠率;(3) 賠率寫在設定不寫在程式,改了不必重新部署,改動進 admin_audit_logs。
type PlatformChanceDraw struct {
	ID           int64
	CommunityID  int64
	UserID       int64
	Kind         string
	Ref          string
	OddsSnapshot []byte
	Seed         string
	Outcome      []byte
	Stake        int64
	Payout       int64
	CreatedAt    time.Time
}

type PlatformChanceDrawsDefault struct {
	ID           int64
	CommunityID  int64
	UserID       int64
	Kind         string
	Ref          string
	OddsSnapshot []byte
	Seed         string
	Outcome      []byte
	Stake        int64
	Payout       int64
	CreatedAt    time.Time
}

type PlatformChannelPurpose struct {
	Key         string
	Name        string
	Description *string
	Enabled     bool
	CreatedAt   time.Time
}

type PlatformCommunity struct {
	ID          int64
	PublicID    string
	Name        string
	XpRulesetID *int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type PlatformCommunitySpace struct {
	ID          int64
	PublicID    string
	CommunityID int64
	Provider    string
	ExternalID  string
	Name        *string
	CreatedAt   time.Time
	Config      []byte
}

type PlatformConversationChunk struct {
	ID                 int64
	SpaceID            int64
	ChannelID          string
	ThreadID           *string
	StartedAt          time.Time
	EndedAt            time.Time
	ParticipantUserIds []int64
	MessageCount       int32
	Text               string
	EmbedModel         *string
	EmbeddedAt         *time.Time
}

type PlatformCurrency struct {
	Code      string
	Name      string
	Symbol    *string
	Tradable  bool
	CreatedAt time.Time
	// global = 平台通用幣,餘額與分錄的 community_id 為 NULL;community = 社群限定點數,必須帶 community_id。一旦有餘額就改不動(複合外鍵擋著)——把流通中的幣改作用域是資料搬遷,不該是一句 UPDATE。
	Scope string
}

type PlatformDailyClaim struct {
	UserID    int64
	ClaimDate pgtype.Date
	ClaimedAt time.Time
	Timezone  string
	Streak    int32
	Amount    int64
	Source    string
}

type PlatformEconomyConfig struct {
	ID          int64
	Key         string
	Value       []byte
	EffectiveAt time.Time
	CreatedBy   *int64
	Note        *string
}

type PlatformEntitlement struct {
	ID              int64
	UserID          int64
	ItemID          int64
	GrantedAt       time.Time
	ExpiresAt       *time.Time
	RefundableUntil *time.Time
	RevokedAt       *time.Time
	PublicID        string
}

type PlatformEventLog struct {
	ID        int64
	RequestID *string
	Channel   string
	Kind      string
	Action    string
	UserID    *int64
	SpaceID   *int64
	Status    *string
	ErrorCode *string
	LatencyMs *int32
	Request   []byte
	CreatedAt time.Time
	Response  []byte
	TraceID   *string
}

type PlatformEventLogsDefault struct {
	ID        int64
	RequestID *string
	Channel   string
	Kind      string
	Action    string
	UserID    *int64
	SpaceID   *int64
	Status    *string
	ErrorCode *string
	LatencyMs *int32
	Request   []byte
	CreatedAt time.Time
}

// 獎品在**建立時**就從管理員帳上扣除並凍結,不是開獎時才扣 —— 否則管理員在開獎前把點數花光,抽獎就變成空頭支票。
type PlatformGiveaway struct {
	ID          int64
	PublicID    string
	CommunityID int64
	SpaceID     int64
	Title       string
	PrizeKind   string
	PrizeRef    string
	PrizeAmount *int64
	WinnerCount int32
	EntryCost   int64
	Status      string
	OpensAt     time.Time
	ClosesAt    time.Time
	DrawnAt     *time.Time
	CreatedBy   int64
	CreatedAt   time.Time
}

type PlatformGiveawayEntry struct {
	ID         int64
	GiveawayID int64
	UserID     int64
	Won        bool
	EnteredAt  time.Time
}

type PlatformHighlight struct {
	ID        int64
	Period    string
	MessageID string
	UserID    int64
	Excerpt   string
	Score     int32
	VoteCount int32
	Selected  bool
	CreatedAt time.Time
}

type PlatformIdempotencyKey struct {
	Key         string
	RequestHash string
	Response    []byte
	CreatedAt   time.Time
}

type PlatformIdentity struct {
	ID              int64
	UserID          int64
	Provider        string
	ProviderUserID  string
	Username        *string
	AccessTokenEnc  []byte
	RefreshTokenEnc []byte
	Scope           *string
	ExpiresAt       *time.Time
	LinkedAt        time.Time
}

type PlatformItemDefinition struct {
	ID            int64
	PublicID      string
	Name          string
	Category      string
	Rarity        *string
	IconUrl       *string
	Tradable      bool
	BindOnAcquire bool
	Stackable     bool
	MaxSupply     *int32
	MintedCount   int32
	CreatedAt     time.Time
}

type PlatformItemInstance struct {
	ID              int64
	PublicID        string
	DefinitionID    int64
	OwnerID         int64
	Bound           bool
	Quantity        int32
	LockedByTradeID *int64
	AcquiredAt      time.Time
	AcquiredVia     *string
	LockedReason    *string
}

type PlatformLevelReward struct {
	ID          int64
	CommunityID int64
	Subject     string
	Level       int32
	RewardKind  string
	RewardRef   string
	Amount      *int64
	Note        *string
	CreatedAt   time.Time
}

type PlatformLevelRewardGrant struct {
	ID            int64
	RewardID      int64
	UserID        int64
	PetInstanceID *int64
	GrantedAt     time.Time
}

type PlatformLootBox struct {
	ID           int64
	PublicID     string
	CommunityID  int64
	Name         string
	CostCurrency string
	CostAmount   int64
	DailyLimit   *int32
	Enabled      bool
	CreatedAt    time.Time
}

type PlatformLootBoxItem struct {
	ID         int64
	BoxID      int64
	RewardKind string
	RewardRef  string
	Amount     *int64
	Weight     int32
	Remaining  *int32
}

type PlatformMarketListing struct {
	ID             int64
	PublicID       string
	SellerID       int64
	ItemInstanceID int64
	Currency       string
	Price          int64
	Status         string
	ListedAt       time.Time
	ExpiresAt      *time.Time
}

type PlatformMarketOrder struct {
	ID        int64
	ListingID int64
	BuyerID   int64
	SellerID  int64
	Price     int64
	Fee       int64
	SettledAt time.Time
}

type PlatformMessageLog struct {
	ID            int64
	UserID        int64
	SpaceID       int64
	ChannelID     string
	ChannelKind   string
	ThreadID      *string
	MessageID     string
	Excerpt       *string
	FullLength    *int32
	HasAttachment bool
	ReplyTo       *string
	CreatedAt     time.Time
	DeletedAt     *time.Time
}

type PlatformMessageLogsDefault struct {
	ID            int64
	UserID        int64
	SpaceID       int64
	ChannelID     string
	ChannelKind   string
	ThreadID      *string
	MessageID     string
	Excerpt       *string
	FullLength    *int32
	HasAttachment bool
	ReplyTo       *string
	CreatedAt     time.Time
	DeletedAt     *time.Time
}

type PlatformMessageRevision struct {
	ID         int64
	MessageID  string
	UserID     int64
	Excerpt    *string
	Kind       string
	CapturedAt time.Time
}

type PlatformMessageRevisionsDefault struct {
	ID         int64
	MessageID  string
	UserID     int64
	Excerpt    *string
	Kind       string
	CapturedAt time.Time
}

type PlatformMessageStat struct {
	MessageID     string
	UserID        int64
	ReactionCount int32
	ReplyCount    int32
	UpdatedAt     time.Time
}

type PlatformOutboxEvent struct {
	ID          int64
	Topic       string
	Payload     []byte
	Status      string
	Attempts    int32
	NextRetryAt *time.Time
	CreatedAt   time.Time
	// 最後一次失敗的原因。沒有它的話,死信只知道「送不出去」,而那正是需要人介入時最該知道的一件事。
	LastError *string
	FailedAt  *time.Time
}

type PlatformPermission struct {
	Key         string
	Name        string
	Description string
	IsDangerous bool
	CreatedAt   time.Time
}

type PlatformPetEquipment struct {
	ID             int64
	PetInstanceID  int64
	Slot           string
	ItemInstanceID int64
	EquippedAt     time.Time
}

// 寵物的可變狀態。等級不存欄位,由 xp 用 xp_rulesets.config 的曲線反推(schemas/24)。擁有權、稀缺、交易鎖全在 item_instances —— 寵物可以連同等級在市集換手。
type PlatformPetState struct {
	ItemInstanceID int64
	OwnerID        int64
	Nickname       *string
	Xp             int64
	Deployed       bool
	LastFedAt      *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type PlatformPresenceSpan struct {
	ID        int64
	UserID    int64
	SpaceID   int64
	Status    string
	StartedAt time.Time
	EndedAt   *time.Time
}

type PlatformPresenceSpansDefault struct {
	ID        int64
	UserID    int64
	SpaceID   int64
	Status    string
	StartedAt time.Time
	EndedAt   *time.Time
}

type PlatformReactionEvent struct {
	ID        int64
	MessageID string
	UserID    int64
	SpaceID   int64
	Emoji     string
	AddedAt   time.Time
	RemovedAt *time.Time
}

type PlatformRedemption struct {
	ID        int64
	PublicID  string
	UserID    int64
	ItemID    int64
	Status    string
	Note      *string
	HandledBy *int64
	HandledAt *time.Time
	CreatedAt time.Time
}

type PlatformRole struct {
	ID        int64
	Key       string
	Name      string
	CreatedAt time.Time
	PublicID  string
	// NULL = 內建角色(owner/admin/moderator/auditor),管理端不得刪除或改權限:它們是系統啟動與緊急救援的依據,刪掉之後沒有人能修好自己的權限。社群要不同的權限組合,複製一份成自己的角色。
	CommunityID *int64
	CreatedBy   *int64
}

type PlatformRolePermission struct {
	RoleID     int64
	Permission string
}

type PlatformRoleProviderBinding struct {
	ID             int64
	RoleID         int64
	SpaceID        int64
	Provider       string
	ExternalRoleID string
	SyncMode       string
}

type PlatformSession struct {
	ID               int64
	PublicID         string
	UserID           int64
	RefreshTokenHash []byte
	IssuedAt         time.Time
	ExpiresAt        time.Time
	LastUsedAt       *time.Time
	RevokedAt        *time.Time
	RevokedReason    *string
	UserAgent        *string
	Ip               *netip.Addr
	RotatedFrom      *int64
}

type PlatformShopItem struct {
	ID                     int64
	PublicID               string
	Name                   string
	Description            *string
	Fulfillment            string
	Currency               string
	Price                  int64
	DurationDays           *int32
	Stock                  *int32
	PerUserLimit           *int32
	RefundWindowSeconds    int32
	GrantsItemDefinitionID *int64
	ExternalRoleID         *string
	ListedAt               *time.Time
	DelistedAt             *time.Time
	CreatedAt              time.Time
}

type PlatformSpaceChannel struct {
	ID          int64
	SpaceID     int64
	ExternalID  string
	Name        *string
	Kind        string
	LogMessages bool
	GrantXp     bool
	CreatedAt   time.Time
	ArchivedAt  *time.Time
}

type PlatformSpaceChannelPurpose struct {
	ID                int64
	SpaceID           int64
	Purpose           string
	ChannelExternalID string
	UpdatedBy         *int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type PlatformSpaceMember struct {
	ID        int64
	SpaceID   int64
	UserID    int64
	JoinedAt  time.Time
	LeftAt    *time.Time
	LeaveKind *string
}

type PlatformTokenEntriesDefault struct {
	ID        int64
	UserID    int64
	Currency  string
	Amount    int64
	Reason    string
	RefType   *string
	RefID     *int64
	ActorID   *int64
	CreatedAt time.Time
}

type PlatformTokenEntry struct {
	ID        int64
	UserID    int64
	Currency  string
	Amount    int64
	Reason    string
	RefType   *string
	RefID     *int64
	ActorID   *int64
	CreatedAt time.Time
	// 對帳式因此改為依 (user_id, currency, community_id) 分組。不分組的 SUM 會永遠等於總額而失去檢查價值——.claude/skills/ledger-invariants 已同步更新。
	CommunityID *int64
	Scope       string
}

type PlatformUser struct {
	ID                int64
	PublicID          string
	DisplayName       *string
	AvatarUrl         *string
	Timezone          string
	TimezoneChangedAt *time.Time
	Email             *string
	CreatedAt         time.Time
	LastSeenAt        *time.Time
	DeletedAt         *time.Time
}

type PlatformUserBalance struct {
	UserID      int64
	Currency    string
	Balance     int64
	UpdatedAt   time.Time
	CommunityID *int64
	Scope       string
	ID          int64
}

type PlatformUserDailyState struct {
	UserID        int64
	CurrentStreak int32
	BestStreak    int32
	LastClaimDate pgtype.Date
	UpdatedAt     time.Time
}

type PlatformUserPrivacySetting struct {
	UserID         int64
	OptOutLogging  bool
	OptOutAiCorpus bool
	UpdatedAt      time.Time
}

type PlatformUserRestriction struct {
	ID        int64
	UserID    int64
	Kind      string
	Reason    string
	CreatedBy int64
	CreatedAt time.Time
	ExpiresAt *time.Time
	LiftedAt  *time.Time
}

type PlatformUserRole struct {
	ID          int64
	UserID      int64
	RoleID      int64
	CommunityID *int64
	Source      string
	GrantedBy   *int64
	GrantedAt   time.Time
	ExpiresAt   *time.Time
}

type PlatformUserTermCount struct {
	UserID int64
	Period string
	Term   string
	Count  int32
}

type PlatformUserXp struct {
	UserID      int64
	CommunityID int64
	Xp          int64
	// **不使用**(2026-09-11 起)。等級是 xp 的純函數:level = floor((xp / base) ^ (1/exponent)) + 1,曲線見 xp_rulesets.config。存成欄位就會有與 xp 不一致的一天,而 xp 才是事實。
	Level     int32
	LastXpAt  *time.Time
	UpdatedAt time.Time
}

type PlatformVoiceSession struct {
	ID              int64
	UserID          int64
	SpaceID         int64
	ChannelID       string
	JoinedAt        time.Time
	LeftAt          *time.Time
	DurationSeconds *int32
	SelfMuted       *bool
	SelfDeafened    *bool
	PeerCountAvg    *float32
}

type PlatformVoiceSessionsDefault struct {
	ID              int64
	UserID          int64
	SpaceID         int64
	ChannelID       string
	JoinedAt        time.Time
	LeftAt          *time.Time
	DurationSeconds *int32
	SelfMuted       *bool
	SelfDeafened    *bool
	PeerCountAvg    *float32
}

type PlatformXpEvent struct {
	ID          int64
	UserID      int64
	CommunityID int64
	SpaceID     *int64
	Source      string
	Amount      int64
	RefID       *string
	CreatedAt   time.Time
	// NULL = 這筆 XP 是給人的;有值 = 給那隻寵物的。同一個活動事件會產生兩列(人一列、出戰寵物一列)。
	PetInstanceID *int64
}

type PlatformXpEventType struct {
	Key         string
	Name        string
	Description *string
	Enabled     bool
	CreatedAt   time.Time
}

type PlatformXpEventsDefault struct {
	ID          int64
	UserID      int64
	CommunityID int64
	SpaceID     *int64
	Source      string
	Amount      int64
	RefID       *string
	CreatedAt   time.Time
}

type PlatformXpRuleset struct {
	ID        int64
	Name      string
	Config    []byte
	CreatedAt time.Time
}
