// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type PlatformActivityDaily struct {
	UserID        int64
	CommunityID   int64
	Date          pgtype.Date
	Messages      int32
	Reactions     int32
	VoiceSeconds  int32
	OnlineSeconds int32
	FirstSeenAt   *time.Time
	LastSeenAt    *time.Time
	XpGained      int64
}

type PlatformAdminAuditLog struct {
	ID          int64
	ActorUserID int64
	Action      string
	TargetType  *string
	TargetID    *int64
	Before      []byte
	After       []byte
	Reason      string
	CreatedAt   time.Time
}

type PlatformCommunity struct {
	ID          int64
	PublicID    string
	Name        string
	XpRulesetID *int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type PlatformCommunitySpace struct {
	ID          int64
	PublicID    string
	CommunityID int64
	Provider    string
	ExternalID  string
	Name        *string
	CreatedAt   time.Time
	Config      []byte
}

type PlatformConversationChunk struct {
	ID                 int64
	SpaceID            int64
	ChannelID          string
	ThreadID           *string
	StartedAt          time.Time
	EndedAt            time.Time
	ParticipantUserIds []int64
	MessageCount       int32
	Text               string
	EmbedModel         *string
	EmbeddedAt         *time.Time
}

type PlatformCurrency struct {
	Code      string
	Name      string
	Symbol    *string
	Tradable  bool
	CreatedAt time.Time
}

type PlatformDailyClaim struct {
	UserID    int64
	ClaimDate pgtype.Date
	ClaimedAt time.Time
	Timezone  string
	Streak    int32
	Amount    int64
	Source    string
}

type PlatformEconomyConfig struct {
	ID          int64
	Key         string
	Value       []byte
	EffectiveAt time.Time
	CreatedBy   *int64
	Note        *string
}

type PlatformEntitlement struct {
	ID              int64
	UserID          int64
	ItemID          int64
	GrantedAt       time.Time
	ExpiresAt       *time.Time
	RefundableUntil *time.Time
	RevokedAt       *time.Time
}

type PlatformEventLog struct {
	ID        int64
	RequestID *string
	Channel   string
	Kind      string
	Action    string
	UserID    *int64
	SpaceID   *int64
	Status    *string
	ErrorCode *string
	LatencyMs *int32
	Request   []byte
	CreatedAt time.Time
	Response  []byte
	TraceID   *string
}

type PlatformEventLogsDefault struct {
	ID        int64
	RequestID *string
	Channel   string
	Kind      string
	Action    string
	UserID    *int64
	SpaceID   *int64
	Status    *string
	ErrorCode *string
	LatencyMs *int32
	Request   []byte
	CreatedAt time.Time
}

type PlatformHighlight struct {
	ID        int64
	Period    string
	MessageID string
	UserID    int64
	Excerpt   string
	Score     int32
	VoteCount int32
	Selected  bool
	CreatedAt time.Time
}

type PlatformIdempotencyKey struct {
	Key         string
	RequestHash string
	Response    []byte
	CreatedAt   time.Time
}

type PlatformIdentity struct {
	ID              int64
	UserID          int64
	Provider        string
	ProviderUserID  string
	Username        *string
	AccessTokenEnc  []byte
	RefreshTokenEnc []byte
	Scope           *string
	ExpiresAt       *time.Time
	LinkedAt        time.Time
}

type PlatformItemDefinition struct {
	ID            int64
	PublicID      string
	Name          string
	Category      string
	Rarity        *string
	IconUrl       *string
	Tradable      bool
	BindOnAcquire bool
	Stackable     bool
	MaxSupply     *int32
	MintedCount   int32
	CreatedAt     time.Time
}

type PlatformItemInstance struct {
	ID              int64
	PublicID        string
	DefinitionID    int64
	OwnerID         int64
	Bound           bool
	Quantity        int32
	LockedByTradeID *int64
	AcquiredAt      time.Time
	AcquiredVia     *string
}

type PlatformMarketListing struct {
	ID             int64
	PublicID       string
	SellerID       int64
	ItemInstanceID int64
	Currency       string
	Price          int64
	Status         string
	ListedAt       time.Time
	ExpiresAt      *time.Time
}

type PlatformMarketOrder struct {
	ID        int64
	ListingID int64
	BuyerID   int64
	SellerID  int64
	Price     int64
	Fee       int64
	SettledAt time.Time
}

type PlatformMessageLog struct {
	ID            int64
	UserID        int64
	SpaceID       int64
	ChannelID     string
	ChannelKind   string
	ThreadID      *string
	MessageID     string
	Excerpt       *string
	FullLength    *int32
	HasAttachment bool
	ReplyTo       *string
	CreatedAt     time.Time
	DeletedAt     *time.Time
}

type PlatformMessageLogsDefault struct {
	ID            int64
	UserID        int64
	SpaceID       int64
	ChannelID     string
	ChannelKind   string
	ThreadID      *string
	MessageID     string
	Excerpt       *string
	FullLength    *int32
	HasAttachment bool
	ReplyTo       *string
	CreatedAt     time.Time
	DeletedAt     *time.Time
}

type PlatformMessageRevision struct {
	ID         int64
	MessageID  string
	UserID     int64
	Excerpt    *string
	Kind       string
	CapturedAt time.Time
}

type PlatformMessageRevisionsDefault struct {
	ID         int64
	MessageID  string
	UserID     int64
	Excerpt    *string
	Kind       string
	CapturedAt time.Time
}

type PlatformMessageStat struct {
	MessageID     string
	UserID        int64
	ReactionCount int32
	ReplyCount    int32
	UpdatedAt     time.Time
}

type PlatformOutboxEvent struct {
	ID          int64
	Topic       string
	Payload     []byte
	Status      string
	Attempts    int32
	NextRetryAt *time.Time
	CreatedAt   time.Time
}

type PlatformPresenceSpan struct {
	ID        int64
	UserID    int64
	SpaceID   int64
	Status    string
	StartedAt time.Time
	EndedAt   *time.Time
}

type PlatformPresenceSpansDefault struct {
	ID        int64
	UserID    int64
	SpaceID   int64
	Status    string
	StartedAt time.Time
	EndedAt   *time.Time
}

type PlatformReactionEvent struct {
	ID        int64
	MessageID string
	UserID    int64
	SpaceID   int64
	Emoji     string
	AddedAt   time.Time
	RemovedAt *time.Time
}

type PlatformRedemption struct {
	ID        int64
	PublicID  string
	UserID    int64
	ItemID    int64
	Status    string
	Note      *string
	HandledBy *int64
	HandledAt *time.Time
	CreatedAt time.Time
}

type PlatformRole struct {
	ID        int64
	Key       string
	Name      string
	CreatedAt time.Time
}

type PlatformRolePermission struct {
	RoleID     int64
	Permission string
}

type PlatformRoleProviderBinding struct {
	ID             int64
	RoleID         int64
	SpaceID        int64
	Provider       string
	ExternalRoleID string
	SyncMode       string
}

type PlatformShopItem struct {
	ID                     int64
	PublicID               string
	Name                   string
	Description            *string
	Fulfillment            string
	Currency               string
	Price                  int64
	DurationDays           *int32
	Stock                  *int32
	PerUserLimit           *int32
	RefundWindowSeconds    int32
	GrantsItemDefinitionID *int64
	ExternalRoleID         *string
	ListedAt               *time.Time
	DelistedAt             *time.Time
	CreatedAt              time.Time
}

type PlatformSpaceChannel struct {
	ID          int64
	SpaceID     int64
	ExternalID  string
	Name        *string
	Kind        string
	LogMessages bool
	GrantXp     bool
	CreatedAt   time.Time
	ArchivedAt  *time.Time
}

type PlatformSpaceMember struct {
	ID        int64
	SpaceID   int64
	UserID    int64
	JoinedAt  time.Time
	LeftAt    *time.Time
	LeaveKind *string
}

type PlatformTokenEntriesDefault struct {
	ID        int64
	UserID    int64
	Currency  string
	Amount    int64
	Reason    string
	RefType   *string
	RefID     *int64
	ActorID   *int64
	CreatedAt time.Time
}

type PlatformTokenEntry struct {
	ID        int64
	UserID    int64
	Currency  string
	Amount    int64
	Reason    string
	RefType   *string
	RefID     *int64
	ActorID   *int64
	CreatedAt time.Time
}

type PlatformUser struct {
	ID                int64
	PublicID          string
	DisplayName       *string
	AvatarUrl         *string
	Timezone          string
	TimezoneChangedAt *time.Time
	Email             *string
	CreatedAt         time.Time
	LastSeenAt        *time.Time
	DeletedAt         *time.Time
}

type PlatformUserBalance struct {
	UserID    int64
	Currency  string
	Balance   int64
	UpdatedAt time.Time
}

type PlatformUserDailyState struct {
	UserID        int64
	CurrentStreak int32
	BestStreak    int32
	LastClaimDate pgtype.Date
	UpdatedAt     time.Time
}

type PlatformUserPrivacySetting struct {
	UserID         int64
	OptOutLogging  bool
	OptOutAiCorpus bool
	UpdatedAt      time.Time
}

type PlatformUserRestriction struct {
	ID        int64
	UserID    int64
	Kind      string
	Reason    string
	CreatedBy int64
	CreatedAt time.Time
	ExpiresAt *time.Time
	LiftedAt  *time.Time
}

type PlatformUserRole struct {
	ID          int64
	UserID      int64
	RoleID      int64
	CommunityID *int64
	Source      string
	GrantedBy   *int64
	GrantedAt   time.Time
	ExpiresAt   *time.Time
}

type PlatformUserTermCount struct {
	UserID int64
	Period string
	Term   string
	Count  int32
}

type PlatformUserXp struct {
	UserID      int64
	CommunityID int64
	Xp          int64
	Level       int32
	LastXpAt    *time.Time
	UpdatedAt   time.Time
}

type PlatformVoiceSession struct {
	ID              int64
	UserID          int64
	SpaceID         int64
	ChannelID       string
	JoinedAt        time.Time
	LeftAt          *time.Time
	DurationSeconds *int32
	SelfMuted       *bool
	SelfDeafened    *bool
	PeerCountAvg    *float32
}

type PlatformVoiceSessionsDefault struct {
	ID              int64
	UserID          int64
	SpaceID         int64
	ChannelID       string
	JoinedAt        time.Time
	LeftAt          *time.Time
	DurationSeconds *int32
	SelfMuted       *bool
	SelfDeafened    *bool
	PeerCountAvg    *float32
}

type PlatformXpEvent struct {
	ID          int64
	UserID      int64
	CommunityID int64
	SpaceID     *int64
	Source      string
	Amount      int64
	RefID       *string
	CreatedAt   time.Time
}

type PlatformXpEventType struct {
	Key         string
	Name        string
	Description *string
	Enabled     bool
	CreatedAt   time.Time
}

type PlatformXpEventsDefault struct {
	ID          int64
	UserID      int64
	CommunityID int64
	SpaceID     *int64
	Source      string
	Amount      int64
	RefID       *string
	CreatedAt   time.Time
}

type PlatformXpRuleset struct {
	ID        int64
	Name      string
	Config    []byte
	CreatedAt time.Time
}
