// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification.sql

package db

import (
	"context"
)

const ackAnnouncements = `-- name: AckAnnouncements :execrows
UPDATE platform.outbox_events
SET status = 'done'
WHERE id = ANY($1::bigint[])
  AND topic = ANY($2::text[])
  AND status <> 'done'
`

type AckAnnouncementsParams struct {
	Ids    []int64
	Topics []string
}

// 確認送達 → 終態 done。
//
// topic 條件是**授權**,不是最佳化:少了它,閘道送一串猜出來的 id
// 就能把退款、工單建立這類內部事件標成已完成 —— 事件會靜靜消失,
// 而且沒有任何一層擋得住。
//
// status <> 'done' 讓重送的 Ack 變成 0 列(冪等),而不是錯誤;
// 也讓「已經被判毒訊息但其實貼出去了」的遲到 Ack 仍然收得回來。
func (q *Queries) AckAnnouncements(ctx context.Context, arg AckAnnouncementsParams) (int64, error) {
	result, err := q.db.Exec(ctx, ackAnnouncements, arg.Ids, arg.Topics)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimAnnouncements = `-- name: ClaimAnnouncements :many

WITH picked AS (
  SELECT e.id
  FROM platform.outbox_events e
  WHERE e.status = 'pending'
    AND e.topic = ANY($2::text[])
    AND (e.next_retry_at IS NULL OR e.next_retry_at <= now())
    AND e.attempts < $3::int
  ORDER BY e.id
  FOR UPDATE SKIP LOCKED
  LIMIT $4::int
)
UPDATE platform.outbox_events e
SET attempts      = e.attempts + 1,
    -- 逾時由 DB 時鐘算(單一時鐘來源,與 MarkOutboxRetry 同一個理由:
    -- app 與 DB 的時鐘偏移會讓事件被提前取走)。
    next_retry_at = now() + make_interval(secs => $1::int)
FROM picked
WHERE e.id = picked.id
RETURNING e.id, e.topic, e.payload
`

type ClaimAnnouncementsParams struct {
	VisibilitySeconds int32
	Topics            []string
	MaxAttempts       int32
	RowLimit          int32
}

type ClaimAnnouncementsRow struct {
	ID      int64
	Topic   string
	Payload []byte
}

// 通知拉取(notificationpg):outbox_events → Discord 閘道的取貨口。
//
// 這個檔案**不新增任何狀態欄位**。認領重用既有的 next_retry_at 當可見性逾時,
// 重試次數重用既有的 attempts,終態重用既有的 status='failed'。
// 理由是專案第 9 條:outbox 的投遞狀態已經有一個權威位置,
// 為了「拉取」再開一組 claimed_at / claimed_by 欄位,就會有兩套會漂移的語意。
//
// 三條紀律:
//  1. **每個查詢都帶 topic 白名單參數。** 不是為了效能,是授權:
//     閘道只能碰 Discord 清單內的事件,連 Ack 都不能碰別的
//     (不然它猜個 id 就能把內部事件標成已完成 —— 那是靜默丟事件)。
//  2. **一律 FOR UPDATE SKIP LOCKED,絕不等鎖。** 兩個 Pull 併發時各拿各的,
//     而不是後到的那個卡住;也因此不可能與另一個 Pull 死鎖。
//  3. **status 只有 Ack 與毒訊息終止會改。** 認領本身不改 status ——
//     沒有 Ack 的事件到期自動重新可見,這就是 at-least-once。
//
// 認領一批待送的公告事件:把 next_retry_at 推到 now() + visibility_seconds,
// 在那之前它對任何消費者(包含另一個 Pull)都不可見。
//
// attempts 在認領時 +1,不是在 Ack 時。理由:重送一次就是重試一次,
// 而 attempts 是毒訊息計數器的既有語意(outbox.Consumer 也是這樣用)。
// 不計數的話,一則永遠貼不出去的公告會無限重來 —— 佇列裡的毒訊息
// 不能沒有終點。
//
// RETURNING 的順序不保證(UPDATE ... FROM 不吃 ORDER BY),
// 呼叫端依 id 排序後才交出去:舊事件先貼。
func (q *Queries) ClaimAnnouncements(ctx context.Context, arg ClaimAnnouncementsParams) ([]ClaimAnnouncementsRow, error) {
	rows, err := q.db.Query(ctx, claimAnnouncements,
		arg.VisibilitySeconds,
		arg.Topics,
		arg.MaxAttempts,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimAnnouncementsRow
	for rows.Next() {
		var i ClaimAnnouncementsRow
		if err := rows.Scan(&i.ID, &i.Topic, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failExhaustedAnnouncements = `-- name: FailExhaustedAnnouncements :execrows
WITH stale AS (
  SELECT e.id
  FROM platform.outbox_events e
  WHERE e.status = 'pending'
    AND e.topic = ANY($1::text[])
    AND e.attempts >= $2::int
    AND (e.next_retry_at IS NULL OR e.next_retry_at <= now())
  ORDER BY e.id
  FOR UPDATE SKIP LOCKED
  LIMIT $3::int
)
UPDATE platform.outbox_events e
SET status = 'failed'
FROM stale
WHERE e.id = stale.id
`

type FailExhaustedAnnouncementsParams struct {
	Topics      []string
	MaxAttempts int32
	RowLimit    int32
}

// 毒訊息終止:重試次數用完、可見性也逾時了(= 沒有人正在處理它),
// 標成 failed 讓它離開待送佇列。
//
// 沒有這一段的話,貼不出去的公告會永遠停在 pending:健康檢查的積壓量
// 只增不減,而清理 job 只刪終態(done/failed),它會永遠留在表裡。
//
// 條件與 ClaimAnnouncements 的 attempts 門檻是同一個數字,由呼叫端傳同一個值
// —— 兩邊各寫一個常數就會出現「不再回傳但也不終止」的夾縫。
func (q *Queries) FailExhaustedAnnouncements(ctx context.Context, arg FailExhaustedAnnouncementsParams) (int64, error) {
	result, err := q.db.Exec(ctx, failExhaustedAnnouncements, arg.Topics, arg.MaxAttempts, arg.RowLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listItemNames = `-- name: ListItemNames :many
SELECT i.public_id, i.name
FROM platform.shop_items i
WHERE i.public_id = ANY($1::text[])
`

type ListItemNamesRow struct {
	PublicID string
	Name     string
}

// 已下架的商品照樣回名稱:公告講的是「當時買了什麼」,
// 那件事不會因為商品下架就不算數。
func (q *Queries) ListItemNames(ctx context.Context, publicIds []string) ([]ListItemNamesRow, error) {
	rows, err := q.db.Query(ctx, listItemNames, publicIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemNamesRow
	for rows.Next() {
		var i ListItemNamesRow
		if err := rows.Scan(&i.PublicID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserDisplayNames = `-- name: ListUserDisplayNames :many

SELECT u.id, COALESCE(u.display_name, '')::text AS display_name
FROM platform.users u
WHERE u.id = ANY($1::bigint[]) AND u.deleted_at IS NULL
`

type ListUserDisplayNamesRow struct {
	ID          int64
	DisplayName string
}

// ── 渲染要用的名稱 ─────────────────────────────────────────────────────
//
// payload 裡只有內部 id,公告要顯示的是人名與商品名。
// 「哪個欄位是人、哪個是商品」的知識在 core/platform/notification,
// 這裡只負責照著查。查不到的鍵不補列 —— 渲染端有預設值(未知成員/未知商品)。
// 軟刪除的使用者查不到 → 公告顯示「未知成員」。
// 這是刻意的:註銷的帳號不該在**新**貼出去的訊息裡被點名。
func (q *Queries) ListUserDisplayNames(ctx context.Context, userIds []int64) ([]ListUserDisplayNamesRow, error) {
	rows, err := q.db.Query(ctx, listUserDisplayNames, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserDisplayNamesRow
	for rows.Next() {
		var i ListUserDisplayNamesRow
		if err := rows.Scan(&i.ID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
