// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: play.sql

package db

import (
	"context"
	"time"
)

const addPetXP = `-- name: AddPetXP :one
UPDATE platform.pet_states SET xp = xp + $2, updated_at = now()
WHERE item_instance_id = $1
RETURNING xp
`

type AddPetXPParams struct {
	ItemInstanceID int64
	Xp             int64
}

func (q *Queries) AddPetXP(ctx context.Context, arg AddPetXPParams) (int64, error) {
	row := q.db.QueryRow(ctx, addPetXP, arg.ItemInstanceID, arg.Xp)
	var xp int64
	err := row.Scan(&xp)
	return xp, err
}

const closeGiveaway = `-- name: CloseGiveaway :exec
UPDATE platform.giveaways SET status = 'drawn', drawn_at = now() WHERE id = $1
`

func (q *Queries) CloseGiveaway(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, closeGiveaway, id)
	return err
}

const countDrawsToday = `-- name: CountDrawsToday :one
SELECT count(*)::bigint FROM platform.chance_draws
WHERE user_id = $1
  AND created_at >= date_trunc('day', now() AT TIME ZONE 'UTC') AT TIME ZONE 'UTC'
`

// 每日次數上限(schemas/25:20 次/人/日)。用 UTC 當日,與 XP 的 daily_cap 一致 ——
// 兩個「今天」用不同定義會讓人在某個時區看到兩者不同步。
func (q *Queries) CountDrawsToday(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countDrawsToday, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createGiveaway = `-- name: CreateGiveaway :one

INSERT INTO platform.giveaways
  (public_id, community_id, space_id, title, prize_kind, prize_ref, prize_amount,
   winner_count, entry_cost, opens_at, closes_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now(), $10, $11)
RETURNING id, public_id, title, closes_at
`

type CreateGiveawayParams struct {
	PublicID    string
	CommunityID int64
	SpaceID     int64
	Title       string
	PrizeKind   string
	PrizeRef    string
	PrizeAmount *int64
	WinnerCount int32
	EntryCost   int64
	ClosesAt    time.Time
	CreatedBy   int64
}

type CreateGiveawayRow struct {
	ID       int64
	PublicID string
	Title    string
	ClosesAt time.Time
}

// ── 抽獎活動 ──────────────────────────────────────────────────
func (q *Queries) CreateGiveaway(ctx context.Context, arg CreateGiveawayParams) (CreateGiveawayRow, error) {
	row := q.db.QueryRow(ctx, createGiveaway,
		arg.PublicID,
		arg.CommunityID,
		arg.SpaceID,
		arg.Title,
		arg.PrizeKind,
		arg.PrizeRef,
		arg.PrizeAmount,
		arg.WinnerCount,
		arg.EntryCost,
		arg.ClosesAt,
		arg.CreatedBy,
	)
	var i CreateGiveawayRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Title,
		&i.ClosesAt,
	)
	return i, err
}

const createPetState = `-- name: CreatePetState :exec
INSERT INTO platform.pet_states (item_instance_id, owner_id)
VALUES ($1, $2)
ON CONFLICT (item_instance_id) DO NOTHING
`

type CreatePetStateParams struct {
	ItemInstanceID int64
	OwnerID        int64
}

// 發到寵物時建狀態列。owner_id 是 item_instances.owner_id 的受控副本
// (複合外鍵保證一致),存它是為了「同時只能出戰一隻」那條部分唯一索引。
func (q *Queries) CreatePetState(ctx context.Context, arg CreatePetStateParams) error {
	_, err := q.db.Exec(ctx, createPetState, arg.ItemInstanceID, arg.OwnerID)
	return err
}

const decrementLootBoxItem = `-- name: DecrementLootBoxItem :execrows
UPDATE platform.loot_box_items
SET remaining = remaining - 1
WHERE id = $1 AND remaining IS NOT NULL AND remaining > 0
`

// 條件帶 remaining > 0:就算呼叫端算錯,DB 也不會讓它變成負數。
func (q *Queries) DecrementLootBoxItem(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, decrementLootBoxItem, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deployPet = `-- name: DeployPet :execrows
UPDATE platform.pet_states SET deployed = true, updated_at = now()
WHERE item_instance_id = $1 AND owner_id = $2
`

type DeployPetParams struct {
	ItemInstanceID int64
	OwnerID        int64
}

func (q *Queries) DeployPet(ctx context.Context, arg DeployPetParams) (int64, error) {
	result, err := q.db.Exec(ctx, deployPet, arg.ItemInstanceID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enterGiveaway = `-- name: EnterGiveaway :execrows
INSERT INTO platform.giveaway_entries (giveaway_id, user_id)
VALUES ($1, $2)
ON CONFLICT (giveaway_id, user_id) DO NOTHING
`

type EnterGiveawayParams struct {
	GiveawayID int64
	UserID     int64
}

// 一人一次靠 UNIQUE 擋,不靠應用層先查再寫(那有競態,而且是兩份真相)。
func (q *Queries) EnterGiveaway(ctx context.Context, arg EnterGiveawayParams) (int64, error) {
	result, err := q.db.Exec(ctx, enterGiveaway, arg.GiveawayID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDeployedPetID = `-- name: GetDeployedPetID :one
SELECT item_instance_id, xp FROM platform.pet_states
WHERE owner_id = $1 AND deployed
`

type GetDeployedPetIDRow struct {
	ItemInstanceID int64
	Xp             int64
}

func (q *Queries) GetDeployedPetID(ctx context.Context, ownerID int64) (GetDeployedPetIDRow, error) {
	row := q.db.QueryRow(ctx, getDeployedPetID, ownerID)
	var i GetDeployedPetIDRow
	err := row.Scan(&i.ItemInstanceID, &i.Xp)
	return i, err
}

const getGiveawayByPublicID = `-- name: GetGiveawayByPublicID :one
SELECT id, public_id, community_id, title, prize_kind, prize_ref, prize_amount,
       winner_count, entry_cost, status, opens_at, closes_at, created_by
FROM platform.giveaways WHERE public_id = $1
`

type GetGiveawayByPublicIDRow struct {
	ID          int64
	PublicID    string
	CommunityID int64
	Title       string
	PrizeKind   string
	PrizeRef    string
	PrizeAmount *int64
	WinnerCount int32
	EntryCost   int64
	Status      string
	OpensAt     time.Time
	ClosesAt    time.Time
	CreatedBy   int64
}

func (q *Queries) GetGiveawayByPublicID(ctx context.Context, publicID string) (GetGiveawayByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, getGiveawayByPublicID, publicID)
	var i GetGiveawayByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.CommunityID,
		&i.Title,
		&i.PrizeKind,
		&i.PrizeRef,
		&i.PrizeAmount,
		&i.WinnerCount,
		&i.EntryCost,
		&i.Status,
		&i.OpensAt,
		&i.ClosesAt,
		&i.CreatedBy,
	)
	return i, err
}

const getLootBoxByPublicID = `-- name: GetLootBoxByPublicID :one

SELECT id, public_id, community_id, name, cost_currency, cost_amount, daily_limit, enabled
FROM platform.loot_boxes WHERE public_id = $1
`

type GetLootBoxByPublicIDRow struct {
	ID           int64
	PublicID     string
	CommunityID  int64
	Name         string
	CostCurrency string
	CostAmount   int64
	DailyLimit   *int32
	Enabled      bool
}

// ── 開箱 ──────────────────────────────────────────────────────
func (q *Queries) GetLootBoxByPublicID(ctx context.Context, publicID string) (GetLootBoxByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, getLootBoxByPublicID, publicID)
	var i GetLootBoxByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.CommunityID,
		&i.Name,
		&i.CostCurrency,
		&i.CostAmount,
		&i.DailyLimit,
		&i.Enabled,
	)
	return i, err
}

const getPetByPublicID = `-- name: GetPetByPublicID :one
SELECT ps.item_instance_id, ps.owner_id, ps.xp, ps.deployed,
       COALESCE(ps.nickname, d.name) AS name
FROM platform.pet_states ps
JOIN platform.item_instances ii ON ii.id = ps.item_instance_id
JOIN platform.item_definitions d ON d.id = ii.definition_id
WHERE ii.public_id = $1
`

type GetPetByPublicIDRow struct {
	ItemInstanceID int64
	OwnerID        int64
	Xp             int64
	Deployed       bool
	Name           string
}

func (q *Queries) GetPetByPublicID(ctx context.Context, publicID string) (GetPetByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, getPetByPublicID, publicID)
	var i GetPetByPublicIDRow
	err := row.Scan(
		&i.ItemInstanceID,
		&i.OwnerID,
		&i.Xp,
		&i.Deployed,
		&i.Name,
	)
	return i, err
}

const grantItemToUser = `-- name: GrantItemToUser :one
INSERT INTO platform.item_instances
  (public_id, definition_id, owner_id, bound, acquired_via, acquired_at)
SELECT $1, d.id, $2, d.bind_on_acquire, $4, now()
FROM platform.item_definitions d
WHERE d.public_id = $3
RETURNING id, public_id, (SELECT category FROM platform.item_definitions WHERE public_id = $3) AS category
`

type GrantItemToUserParams struct {
	PublicID    string
	OwnerID     int64
	PublicID_2  string
	AcquiredVia *string
}

type GrantItemToUserRow struct {
	ID       int64
	PublicID string
	Category string
}

// 開箱與抽獎共用的發物品路徑。
func (q *Queries) GrantItemToUser(ctx context.Context, arg GrantItemToUserParams) (GrantItemToUserRow, error) {
	row := q.db.QueryRow(ctx, grantItemToUser,
		arg.PublicID,
		arg.OwnerID,
		arg.PublicID_2,
		arg.AcquiredVia,
	)
	var i GrantItemToUserRow
	err := row.Scan(&i.ID, &i.PublicID, &i.Category)
	return i, err
}

const insertChanceDraw = `-- name: InsertChanceDraw :one


INSERT INTO platform.chance_draws
  (community_id, user_id, kind, ref, odds_snapshot, seed, outcome, stake, payout)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, created_at
`

type InsertChanceDrawParams struct {
	CommunityID  int64
	UserID       int64
	Kind         string
	Ref          string
	OddsSnapshot []byte
	Seed         string
	Outcome      []byte
	Stake        int64
	Payout       int64
}

type InsertChanceDrawRow struct {
	ID        int64
	CreatedAt time.Time
}

// 小遊戲、開箱、抽獎、寵物的查詢(schemas/25)。
//
// 檔名是 play 不是 chance:抽獎(giveaway)本身沒有隨機以外的共通點,
// 但這四個功能在使用者眼裡是同一件事 ——「可以玩的東西」。
//
// 注意:activity_ 前綴保留給活動層(themis),這裡不使用。
// ── 抽籤留痕(三處共用)───────────────────────────────────────
// 每一次隨機都要留痕:產出速率、黑箱質疑、賠率變更的稽核都靠它。
func (q *Queries) InsertChanceDraw(ctx context.Context, arg InsertChanceDrawParams) (InsertChanceDrawRow, error) {
	row := q.db.QueryRow(ctx, insertChanceDraw,
		arg.CommunityID,
		arg.UserID,
		arg.Kind,
		arg.Ref,
		arg.OddsSnapshot,
		arg.Seed,
		arg.Outcome,
		arg.Stake,
		arg.Payout,
	)
	var i InsertChanceDrawRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listLootBoxes = `-- name: ListLootBoxes :many
SELECT public_id, name, cost_currency, cost_amount, daily_limit
FROM platform.loot_boxes WHERE community_id = $1 AND enabled ORDER BY id
`

type ListLootBoxesRow struct {
	PublicID     string
	Name         string
	CostCurrency string
	CostAmount   int64
	DailyLimit   *int32
}

func (q *Queries) ListLootBoxes(ctx context.Context, communityID int64) ([]ListLootBoxesRow, error) {
	rows, err := q.db.Query(ctx, listLootBoxes, communityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLootBoxesRow
	for rows.Next() {
		var i ListLootBoxesRow
		if err := rows.Scan(
			&i.PublicID,
			&i.Name,
			&i.CostCurrency,
			&i.CostAmount,
			&i.DailyLimit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenGiveaways = `-- name: ListOpenGiveaways :many
SELECT g.public_id, g.title, g.entry_cost, g.winner_count, g.closes_at,
       (SELECT count(*) FROM platform.giveaway_entries e WHERE e.giveaway_id = g.id)::bigint AS entries
FROM platform.giveaways g
WHERE g.community_id = $1 AND g.status = 'open' AND g.closes_at > now()
ORDER BY g.closes_at
`

type ListOpenGiveawaysRow struct {
	PublicID    string
	Title       string
	EntryCost   int64
	WinnerCount int32
	ClosesAt    time.Time
	Entries     int64
}

func (q *Queries) ListOpenGiveaways(ctx context.Context, communityID int64) ([]ListOpenGiveawaysRow, error) {
	rows, err := q.db.Query(ctx, listOpenGiveaways, communityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenGiveawaysRow
	for rows.Next() {
		var i ListOpenGiveawaysRow
		if err := rows.Scan(
			&i.PublicID,
			&i.Title,
			&i.EntryCost,
			&i.WinnerCount,
			&i.ClosesAt,
			&i.Entries,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPets = `-- name: ListPets :many

SELECT ii.public_id, COALESCE(ps.nickname, d.name) AS name, d.rarity, d.icon_url,
       ps.xp, ps.deployed
FROM platform.pet_states ps
JOIN platform.item_instances ii ON ii.id = ps.item_instance_id
JOIN platform.item_definitions d ON d.id = ii.definition_id
WHERE ps.owner_id = $1
ORDER BY ps.deployed DESC, ps.xp DESC
`

type ListPetsRow struct {
	PublicID string
	Name     string
	Rarity   *string
	IconUrl  *string
	Xp       int64
	Deployed bool
}

// ── 寵物 ──────────────────────────────────────────────────────
func (q *Queries) ListPets(ctx context.Context, ownerID int64) ([]ListPetsRow, error) {
	rows, err := q.db.Query(ctx, listPets, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPetsRow
	for rows.Next() {
		var i ListPetsRow
		if err := rows.Scan(
			&i.PublicID,
			&i.Name,
			&i.Rarity,
			&i.IconUrl,
			&i.Xp,
			&i.Deployed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockGiveawayForDraw = `-- name: LockGiveawayForDraw :one
SELECT id, community_id, prize_kind, prize_ref, prize_amount, winner_count, status
FROM platform.giveaways WHERE id = $1 FOR UPDATE
`

type LockGiveawayForDrawRow struct {
	ID          int64
	CommunityID int64
	PrizeKind   string
	PrizeRef    string
	PrizeAmount *int64
	WinnerCount int32
	Status      string
}

// 開獎要序列化:兩個人同時按開獎會抽出兩組贏家,而獎品只有一份。
func (q *Queries) LockGiveawayForDraw(ctx context.Context, id int64) (LockGiveawayForDrawRow, error) {
	row := q.db.QueryRow(ctx, lockGiveawayForDraw, id)
	var i LockGiveawayForDrawRow
	err := row.Scan(
		&i.ID,
		&i.CommunityID,
		&i.PrizeKind,
		&i.PrizeRef,
		&i.PrizeAmount,
		&i.WinnerCount,
		&i.Status,
	)
	return i, err
}

const lockLootBoxItems = `-- name: LockLootBoxItems :many
SELECT id, reward_kind, reward_ref, amount, weight, remaining
FROM platform.loot_box_items
WHERE box_id = $1
ORDER BY id
FOR UPDATE
`

type LockLootBoxItemsRow struct {
	ID         int64
	RewardKind string
	RewardRef  string
	Amount     *int64
	Weight     int32
	Remaining  *int32
}

// **FOR UPDATE**:有限獎池的 remaining 要在同一個 transaction 裡讀了再扣,
// 否則兩個人同時抽最後一件,兩個人都會拿到。
func (q *Queries) LockLootBoxItems(ctx context.Context, boxID int64) ([]LockLootBoxItemsRow, error) {
	rows, err := q.db.Query(ctx, lockLootBoxItems, boxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockLootBoxItemsRow
	for rows.Next() {
		var i LockLootBoxItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.RewardKind,
			&i.RewardRef,
			&i.Amount,
			&i.Weight,
			&i.Remaining,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markGiveawayWinners = `-- name: MarkGiveawayWinners :execrows
UPDATE platform.giveaway_entries SET won = true
WHERE giveaway_id = $1 AND user_id = ANY($2::bigint[])
`

type MarkGiveawayWinnersParams struct {
	GiveawayID int64
	Column2    []int64
}

func (q *Queries) MarkGiveawayWinners(ctx context.Context, arg MarkGiveawayWinnersParams) (int64, error) {
	result, err := q.db.Exec(ctx, markGiveawayWinners, arg.GiveawayID, arg.Column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pickGiveawayWinners = `-- name: PickGiveawayWinners :many
SELECT e.id, e.user_id
FROM platform.giveaway_entries e
WHERE e.giveaway_id = $1
ORDER BY random()
LIMIT $2
`

type PickGiveawayWinnersParams struct {
	GiveawayID int64
	Limit      int32
}

type PickGiveawayWinnersRow struct {
	ID     int64
	UserID int64
}

// 隨機取 N 位。random() 在這裡夠用:抽獎的公平性由「誰都不能改參加名單」
// 保證(UNIQUE + append),不是由亂數品質保證;而且結果會連同 seed 進 chance_draws。
func (q *Queries) PickGiveawayWinners(ctx context.Context, arg PickGiveawayWinnersParams) ([]PickGiveawayWinnersRow, error) {
	rows, err := q.db.Query(ctx, pickGiveawayWinners, arg.GiveawayID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PickGiveawayWinnersRow
	for rows.Next() {
		var i PickGiveawayWinnersRow
		if err := rows.Scan(&i.ID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renamePet = `-- name: RenamePet :execrows
UPDATE platform.pet_states SET nickname = $3, updated_at = now()
WHERE item_instance_id = $1 AND owner_id = $2
`

type RenamePetParams struct {
	ItemInstanceID int64
	OwnerID        int64
	Nickname       *string
}

func (q *Queries) RenamePet(ctx context.Context, arg RenamePetParams) (int64, error) {
	result, err := q.db.Exec(ctx, renamePet, arg.ItemInstanceID, arg.OwnerID, arg.Nickname)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sumFaucetSince = `-- name: SumFaucetSince :one
SELECT COALESCE(SUM(payout - stake), 0)::bigint AS net
FROM platform.chance_draws
WHERE community_id = $1 AND created_at >= $2
`

type SumFaucetSinceParams struct {
	CommunityID int64
	CreatedAt   time.Time
}

// 產出速率:這段時間系統淨吐出多少點。負數 = 淨回收(水槽正常運作)。
func (q *Queries) SumFaucetSince(ctx context.Context, arg SumFaucetSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumFaucetSince, arg.CommunityID, arg.CreatedAt)
	var net int64
	err := row.Scan(&net)
	return net, err
}

const undeployAllPets = `-- name: UndeployAllPets :exec
UPDATE platform.pet_states SET deployed = false, updated_at = now()
WHERE owner_id = $1 AND deployed
`

// 換出戰前先全部收起來。部分唯一索引保證「同時只有一隻」,
// 但那是最後防線 —— 直接撞索引會得到約束錯誤而不是可讀訊息。
func (q *Queries) UndeployAllPets(ctx context.Context, ownerID int64) error {
	_, err := q.db.Exec(ctx, undeployAllPets, ownerID)
	return err
}
