// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	// 呼叫前必須已 LockBalanceForUpdate;CHECK(balance >= 0) 是最後防線,不是主要檢查
	ApplyBalanceDelta(ctx context.Context, arg ApplyBalanceDeltaParams) (int64, error)
	// 多實例安全消費:SKIP LOCKED
	ClaimPendingOutbox(ctx context.Context, limit int32) ([]PlatformOutboxEvent, error)
	CreateIdentity(ctx context.Context, arg CreateIdentityParams) (PlatformIdentity, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (PlatformUser, error)
	EnsureBalanceRow(ctx context.Context, arg EnsureBalanceRowParams) error
	GetBalance(ctx context.Context, arg GetBalanceParams) (int64, error)
	// 經濟設定:不覆寫舊值,讀取取「生效時間最新」的一筆
	GetCurrentConfig(ctx context.Context, key string) ([]byte, error)
	GetDailyState(ctx context.Context, userID int64) (PlatformUserDailyState, error)
	GetIdempotencyKey(ctx context.Context, key string) (PlatformIdempotencyKey, error)
	GetUserByID(ctx context.Context, id int64) (PlatformUser, error)
	GetUserByIdentity(ctx context.Context, arg GetUserByIdentityParams) (PlatformUser, error)
	GetUserByPublicID(ctx context.Context, publicID string) (PlatformUser, error)
	// reason NOT NULL 是刻意的:強迫動作當下寫理由(schemas/03)
	InsertAdminAudit(ctx context.Context, arg InsertAdminAuditParams) (int64, error)
	// 調整 = 插新列(必帶 created_by;seed 列 created_by 為 NULL)
	InsertConfig(ctx context.Context, arg InsertConfigParams) (PlatformEconomyConfig, error)
	// 簽到:防連點靠 daily_claims 的 PK(user_id, claim_date),不用冪等鍵(ledger-invariants 第三條)
	InsertDailyClaim(ctx context.Context, arg InsertDailyClaimParams) (PlatformDailyClaim, error)
	// 與動錢同一個 transaction 寫入(見 ledger-invariants 第三條)。
	// 在 tx 開頭先插(response 先 NULL),讓併發同 key 的第二個 tx 直接撞 PK;
	// tx 若 rollback,key 同步消失,合法重試不會被擋。
	InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) error
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (int64, error)
	InsertTokenEntry(ctx context.Context, arg InsertTokenEntryParams) (InsertTokenEntryRow, error)
	ListAdminAuditByActor(ctx context.Context, arg ListAdminAuditByActorParams) ([]PlatformAdminAuditLog, error)
	ListCurrentConfigs(ctx context.Context) ([]ListCurrentConfigsRow, error)
	ListEntriesByUser(ctx context.Context, arg ListEntriesByUserParams) ([]PlatformTokenEntry, error)
	// 帳本 query。使用規則見 .claude/skills/ledger-invariants:
	// append-only、同 transaction 更新餘額、鎖依 user_id 升冪、動錢一律冪等。
	// 這裡刻意「沒有」UPDATE/DELETE token_entries 的 query —— 不要新增。
	LockBalanceForUpdate(ctx context.Context, arg LockBalanceForUpdateParams) (int64, error)
	MarkOutboxDone(ctx context.Context, id int64) error
	// 毒訊息終態:超過重試上限,不能卡住整條佇列
	MarkOutboxFailed(ctx context.Context, id int64) error
	MarkOutboxRetry(ctx context.Context, arg MarkOutboxRetryParams) error
	// 對帳:找出 SUM(entries) 與 balance 不一致的每一組(含只有分錄沒有餘額列、或反之)
	ReconcileBalances(ctx context.Context) ([]ReconcileBalancesRow, error)
	SetIdempotencyResponse(ctx context.Context, arg SetIdempotencyResponseParams) error
	// 對帳 job 用:驗證 SUM(entries) = balance
	SumEntriesForUser(ctx context.Context, arg SumEntriesForUserParams) (int64, error)
	TouchUserLastSeen(ctx context.Context, id int64) error
	UpdateIdentityTokens(ctx context.Context, arg UpdateIdentityTokensParams) error
	UpdateUserTimezone(ctx context.Context, arg UpdateUserTimezoneParams) (UpdateUserTimezoneRow, error)
	UpsertDailyState(ctx context.Context, arg UpsertDailyStateParams) error
}

var _ Querier = (*Queries)(nil)
