// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"time"
)

type Querier interface {
	// 與 InsertXpEvent 同 tx;now() 為 tx 時間,與事件的 created_at 同值。
	// level 不動:M1 曲線未上線,恆 0(schemas/06)
	AddUserXp(ctx context.Context, arg AddUserXpParams) (int64, error)
	// 呼叫前必須已 LockBalanceForUpdate;CHECK(balance >= 0) 是最後防線,不是主要檢查
	ApplyBalanceDelta(ctx context.Context, arg ApplyBalanceDeltaParams) (int64, error)
	// 多實例安全消費:SKIP LOCKED
	ClaimPendingOutbox(ctx context.Context, limit int32) ([]PlatformOutboxEvent, error)
	// 語意代價(接受):超過窗口的重送不再被識別為重放——30 天遠大於任何合法重試窗口
	CleanupIdempotencyKeys(ctx context.Context, retentionDays int32) (int64, error)
	// 終態事件(done/failed)逾保留期即刪;pending 永不動(schemas/14)
	CleanupOutboxEvents(ctx context.Context, retentionDays int32) (int64, error)
	// per_user_limit 的計數口徑(schemas/08):未撤銷的 entitlements + 非 cancelled/rejected
	// 的 redemptions。退款(撤銷)與被拒/取消的工單釋放額度。
	CountUserItemAcquisitions(ctx context.Context, arg CountUserItemAcquisitionsParams) (int64, error)
	CreateIdentity(ctx context.Context, arg CreateIdentityParams) (PlatformIdentity, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (PlatformUser, error)
	EnsureBalanceRow(ctx context.Context, arg EnsureBalanceRowParams) error
	// 為 platform schema 所有分區表補齊本月與下月分區(migration 00001 的函式)
	EnsureMonthPartitions(ctx context.Context) error
	// 與 EnsureBalanceRow 同模式:先保證投影列存在,才能 FOR UPDATE 串行化同 user 的併發入帳
	EnsureUserXpRow(ctx context.Context, arg EnsureUserXpRowParams) error
	GetBalance(ctx context.Context, arg GetBalanceParams) (int64, error)
	// LEFT JOIN:community 存在但 xp_ruleset_id 為 NULL(M1 可能還沒建 ruleset)時
	// 回 NULL config,呼叫端採安全預設(無冷卻、無 cap);community 不存在 → 無列(ErrNoRows)
	GetCommunityXpConfig(ctx context.Context, id int64) ([]byte, error)
	// 經濟設定:不覆寫舊值,讀取取「生效時間最新」的一筆
	GetCurrentConfig(ctx context.Context, key string) ([]byte, error)
	GetDailyState(ctx context.Context, userID int64) (PlatformUserDailyState, error)
	// manual 購買的押款分錄 ref 指向 redemption;免費 manual 商品沒有分錄 → no rows。
	GetHoldEntryForRedemption(ctx context.Context, refID *int64) (GetHoldEntryForRedemptionRow, error)
	GetIdempotencyKey(ctx context.Context, key string) (PlatformIdempotencyKey, error)
	// 最近一次簽到(依絕對時間),供改時區冷卻檢查(timezone_change_min_gap_hours)比對 claimed_at
	GetLastDailyClaim(ctx context.Context, userID int64) (PlatformDailyClaim, error)
	// Purchase 把扣款分錄的 ref 指向 entitlement(ref_type='entitlement', ref_id=權益 id),
	// 退款由此精確找回原分錄——不靠「該 user 該 item 最近一筆」猜測,也不改 schema。
	// 免費商品(price=0)購買時沒有分錄 → no rows,呼叫端視為無錢可退、僅撤銷權益。
	GetPurchaseEntryForEntitlement(ctx context.Context, refID *int64) (GetPurchaseEntryForEntitlementRow, error)
	// is_listed 用 DB 時鐘計算(單一時鐘來源):listed_at 非空且已到、delisted_at 空或未到。
	GetShopItemForPurchase(ctx context.Context, publicID string) (GetShopItemForPurchaseRow, error)
	// 管理員經濟操作 query。動錢一律走 ledger 的 ApplyInTx,這裡只有讀取;
	// audit 寫入用 audit.sql 的 InsertAdminAudit,不重複定義。
	// 退款前讀原分錄(分區表,依 id 掃全分區;管理操作低頻,可接受)
	GetTokenEntryByID(ctx context.Context, id int64) (PlatformTokenEntry, error)
	GetUserByID(ctx context.Context, id int64) (PlatformUser, error)
	GetUserByIdentity(ctx context.Context, arg GetUserByIdentityParams) (PlatformUser, error)
	GetUserByPublicID(ctx context.Context, publicID string) (PlatformUser, error)
	// XP query。設計依 schemas/06(含增補 E)與 schemas/01 增補 A:
	// xp_events 是事實、user_xp 是投影(必可重算)、XP 不進帳本不經 Ledger(刻意設計,
	// XP 錯了重算即可,沒有對帳需求;混進帳本會淹沒金流稽核)。
	// 冷卻用 user_xp.last_xp_at 直接查 DB(schemas/06:不上 Redis)。
	// source 檢查:registry 管「存在與開關」(全域);數值/冷卻/上限在 xp_rulesets.config
	GetXpEventType(ctx context.Context, key string) (GetXpEventTypeRow, error)
	// reason NOT NULL 是刻意的:強迫動作當下寫理由(schemas/03)
	InsertAdminAudit(ctx context.Context, arg InsertAdminAuditParams) (int64, error)
	// 調整 = 插新列(必帶 created_by;seed 列 created_by 為 NULL)
	InsertConfig(ctx context.Context, arg InsertConfigParams) (PlatformEconomyConfig, error)
	// 簽到:防連點靠 daily_claims 的 PK(user_id, claim_date),不用冪等鍵(ledger-invariants 第三條)
	InsertDailyClaim(ctx context.Context, arg InsertDailyClaimParams) (PlatformDailyClaim, error)
	// expires_at / refundable_until 在購買當下用 DB 時鐘算好「存欄位」
	// (schemas/08:窗口逐商品調,存值不現算)。
	// duration_days NULL → expires_at NULL = 永久;refund_window_seconds <= 0 → NULL = 不可退。
	InsertEntitlement(ctx context.Context, arg InsertEntitlementParams) (PlatformEntitlement, error)
	// 與動錢同一個 transaction 寫入(見 ledger-invariants 第三條)。
	// 在 tx 開頭先插(response 先 NULL),讓併發同 key 的第二個 tx 直接撞 PK;
	// tx 若 rollback,key 同步消失,合法重試不會被擋。
	InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) error
	// maintenance 排程器(schemas/14):job 執行紀錄、advisory lock、分區與列級清理。
	// 分區到期偵測(pg_inherits catalog,sqlc 解析不了系統目錄)與 DROP TABLE(動態 DDL)
	// 無法走 sqlc,實作在 maintenance 套件內(partition.go)。
	// 每次 job 執行寫一列 event_logs(schemas/13 的 job.run 在此兌現;失敗也要記)
	InsertJobRunLog(ctx context.Context, arg InsertJobRunLogParams) error
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (int64, error)
	InsertRedemption(ctx context.Context, arg InsertRedemptionParams) (PlatformRedemption, error)
	InsertTokenEntry(ctx context.Context, arg InsertTokenEntryParams) (InsertTokenEntryRow, error)
	InsertXpEvent(ctx context.Context, arg InsertXpEventParams) (InsertXpEventRow, error)
	// 冷卻計時器:該 (user, community, source) 最近一筆事件的時間。
	// 不用 user_xp.last_xp_at 當計時器 —— 它是「最後任何入帳」的跨 source 資訊欄位,
	// 拿來計時會讓 voice 高頻入帳餓死 message 的冷卻、admin 修正也會重置計時(QA 中1)。
	// 無列(ErrNoRows)= 該 source 從未入帳 = 無冷卻。呼叫前必須已 LockUserXp(串行化)
	LastXpEventAtBySource(ctx context.Context, arg LastXpEventAtBySourceParams) (time.Time, error)
	ListAdminAuditByActor(ctx context.Context, arg ListAdminAuditByActorParams) ([]PlatformAdminAuditLog, error)
	ListCurrentConfigs(ctx context.Context) ([]ListCurrentConfigsRow, error)
	ListEntriesByUser(ctx context.Context, arg ListEntriesByUserParams) ([]PlatformTokenEntry, error)
	// 帳本 query。使用規則見 .claude/skills/ledger-invariants:
	// append-only、同 transaction 更新餘額、鎖依 user_id 升冪、動錢一律冪等。
	// 這裡刻意「沒有」UPDATE/DELETE token_entries 的 query —— 不要新增。
	LockBalanceForUpdate(ctx context.Context, arg LockBalanceForUpdateParams) (int64, error)
	// FOR UPDATE OF e:只鎖權益列(同一權益的退款串行化),不鎖共享讀的商品列。
	// db_now 一併回傳:退款窗口比對用 DB 時鐘,避免 app/DB 時鐘偏移誤判(同 outbox 的教訓)。
	LockEntitlementForRefund(ctx context.Context, id int64) (LockEntitlementForRefundRow, error)
	// 限時權益到期回收(schemas/14 entitlement_reaper、schemas/08 部分索引)。
	// 本檔只有到期掃描與撤銷;outbox 寫入沿用 ledger.sql 的 InsertOutboxEvent
	// (一個概念一個權威,不重複)。entitlements 之外的表僅共享讀。
	// FOR UPDATE OF e SKIP LOCKED:多實例回收互不重複,也不與退款互擋——
	// shoppg 退款持有的 entitlement 列鎖讓本輪直接跳過,下一輪再看
	// (屆時要嘛已 revoked 不再匹配,要嘛退款窗口已過照常回收,兩者皆正確)。
	// OF e:只鎖權益列,不鎖共享讀的 shop_items。
	// WHERE 條件正中既有部分索引 (expires_at) WHERE revoked_at IS NULL AND expires_at IS NOT NULL。
	// external_role_id:auto_role 商品的 Discord 身分組,消費端收回身分組要用。
	LockExpiredEntitlements(ctx context.Context, limit int32) ([]LockExpiredEntitlementsRow, error)
	// FOR UPDATE OF r:同一工單的 approve / reject / cancel 串行化,
	// 後到者看到非 pending 即拒絕(狀態機單向)。
	LockRedemptionForHandle(ctx context.Context, id int64) (LockRedemptionForHandleRow, error)
	// 串行化同一使用者的併發 Claim:跨當地午夜(或併發改時區)時兩個 tx 可能算出
	// 不同 claim_date,單靠 PK 擋不住(streak 誤算、20h 閘門可繞過)。
	// 先鎖 users 列,之後的冷卻/streak 讀取全在鎖後;PK 仍是防連點的最終防線。
	LockUserForDaily(ctx context.Context, id int64) (LockUserForDailyRow, error)
	// 商店 query(schemas/08-shop.md)。動錢一律經 ledger(shoppg 用 ApplyInTx 同 tx 綁定),
	// 這裡只有商品 / 權益 / 工單側的讀寫;token_entries 僅有 SELECT(append-only 鐵則)。
	// 同一使用者的購買以 users 列鎖串行化:per_user_limit 計數與 API 冪等鍵的重放判定,
	// 都必須在「前一筆購買 commit 之後」才有意義(READ COMMITTED 下先讀後寫會踩到舊快照)。
	// 鎖序:users → user_balances(與 dailypg 同向,不會與帳本互鎖)。
	LockUserForShop(ctx context.Context, id int64) (int64, error)
	// 一併回 DB 時鐘:冷卻比較的兩端(事件時間與 now)都用 DB 時鐘,
	// 單一時鐘來源,app/DB 時鐘偏移不影響判斷
	LockUserXp(ctx context.Context, arg LockUserXpParams) (LockUserXpRow, error)
	MaintenanceUnlock(ctx context.Context, jobName string) error
	MarkOutboxDone(ctx context.Context, id int64) error
	// 毒訊息終態:超過重試上限,不能卡住整條佇列
	MarkOutboxFailed(ctx context.Context, id int64) error
	// 退避時間由 DB 時鐘計算(單一時鐘來源,QA:app/DB 時鐘偏移會讓事件被提前取走)
	MarkOutboxRetry(ctx context.Context, arg MarkOutboxRetryParams) error
	// 投影重算:xp ← SUM(events)、last_xp_at ← MAX(created_at),整個投影可從事實重建。
	// 呼叫前必須已 LockUserXp,否則與並行 Award 有覆寫競態(先算 SUM、後拿鎖會蓋掉新事件)
	RebuildUserXp(ctx context.Context, arg RebuildUserXpParams) (int64, error)
	// 對帳:找出 SUM(entries) 與 balance 不一致的每一組(含只有分錄沒有餘額列、或反之)
	ReconcileBalances(ctx context.Context) ([]ReconcileBalancesRow, error)
	// 呼叫前必須已 LockEntitlementForRefund 且確認 revoked_at IS NULL。
	RevokeEntitlement(ctx context.Context, id int64) (*time.Time, error)
	// 呼叫前必須已 LockExpiredEntitlements 持鎖;revoked_at IS NULL 再守一層,
	// 影響列數 ≠ 輸入數即狀態矛盾,呼叫端失敗出聲。時間用 DB 時鐘(單一時鐘來源)。
	RevokeExpiredEntitlements(ctx context.Context, ids []int64) (int64, error)
	SetIdempotencyResponse(ctx context.Context, arg SetIdempotencyResponseParams) error
	// 對帳 job 用:驗證 SUM(entries) = balance
	SumEntriesForUser(ctx context.Context, arg SumEntriesForUserParams) (int64, error)
	// daily_cap 判斷:UTC 當日該 user 該 community 該 source 的總和(schemas/01 A)。
	// 呼叫前必須已 LockUserXp,同 user 的併發入帳已串行化,SUM 不會低估
	SumXpTodayBySource(ctx context.Context, arg SumXpTodayBySourceParams) (int64, error)
	TouchUserLastSeen(ctx context.Context, id int64) error
	// session-level advisory lock:同名 job 多實例只有一個能跑,拿不到就跳過本輪。
	// 必須在同一條連線上執行 TryMaintenanceLock / MaintenanceUnlock(排程器用 pool.Acquire 釘住連線)。
	TryMaintenanceLock(ctx context.Context, jobName string) (bool, error)
	UpdateIdentityTokens(ctx context.Context, arg UpdateIdentityTokensParams) error
	// 呼叫前必須已 LockRedemptionForHandle 且確認 status='pending'。
	UpdateRedemptionStatus(ctx context.Context, arg UpdateRedemptionStatusParams) (PlatformRedemption, error)
	UpdateUserTimezone(ctx context.Context, arg UpdateUserTimezoneParams) (UpdateUserTimezoneRow, error)
	UpsertDailyState(ctx context.Context, arg UpsertDailyStateParams) error
}

var _ Querier = (*Queries)(nil)
