// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shop.sql

package db

import (
	"context"
	"time"
)

const countUserItemAcquisitions = `-- name: CountUserItemAcquisitions :one
SELECT (
  (SELECT count(*) FROM platform.entitlements e
     WHERE e.user_id = $1 AND e.item_id = $2
       AND e.revoked_at IS NULL)
+ (SELECT count(*) FROM platform.redemptions r
     WHERE r.user_id = $1 AND r.item_id = $2
       AND r.status NOT IN ('cancelled', 'rejected'))
)::bigint AS acquired
`

type CountUserItemAcquisitionsParams struct {
	UserID int64
	ItemID int64
}

// per_user_limit 的計數口徑(schemas/08):未撤銷的 entitlements + 非 cancelled/rejected
// 的 redemptions。退款(撤銷)與被拒/取消的工單釋放額度。
func (q *Queries) CountUserItemAcquisitions(ctx context.Context, arg CountUserItemAcquisitionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserItemAcquisitions, arg.UserID, arg.ItemID)
	var acquired int64
	err := row.Scan(&acquired)
	return acquired, err
}

const getHoldEntryForRedemption = `-- name: GetHoldEntryForRedemption :one
SELECT id, currency, amount FROM platform.token_entries
WHERE reason = 'redemption_hold' AND ref_type = 'redemption' AND ref_id = $1
ORDER BY created_at DESC
LIMIT 1
`

type GetHoldEntryForRedemptionRow struct {
	ID       int64
	Currency string
	Amount   int64
}

// manual 購買的押款分錄 ref 指向 redemption;免費 manual 商品沒有分錄 → no rows。
func (q *Queries) GetHoldEntryForRedemption(ctx context.Context, refID *int64) (GetHoldEntryForRedemptionRow, error) {
	row := q.db.QueryRow(ctx, getHoldEntryForRedemption, refID)
	var i GetHoldEntryForRedemptionRow
	err := row.Scan(&i.ID, &i.Currency, &i.Amount)
	return i, err
}

const getPurchaseEntryForEntitlement = `-- name: GetPurchaseEntryForEntitlement :one
SELECT id, currency, amount FROM platform.token_entries
WHERE reason = 'shop_purchase' AND ref_type = 'entitlement' AND ref_id = $1
ORDER BY created_at DESC
LIMIT 1
`

type GetPurchaseEntryForEntitlementRow struct {
	ID       int64
	Currency string
	Amount   int64
}

// Purchase 把扣款分錄的 ref 指向 entitlement(ref_type='entitlement', ref_id=權益 id),
// 退款由此精確找回原分錄——不靠「該 user 該 item 最近一筆」猜測,也不改 schema。
// 免費商品(price=0)購買時沒有分錄 → no rows,呼叫端視為無錢可退、僅撤銷權益。
func (q *Queries) GetPurchaseEntryForEntitlement(ctx context.Context, refID *int64) (GetPurchaseEntryForEntitlementRow, error) {
	row := q.db.QueryRow(ctx, getPurchaseEntryForEntitlement, refID)
	var i GetPurchaseEntryForEntitlementRow
	err := row.Scan(&i.ID, &i.Currency, &i.Amount)
	return i, err
}

const getShopItemForPurchase = `-- name: GetShopItemForPurchase :one
SELECT i.id, i.public_id, i.name, i.description, i.fulfillment, i.currency, i.price, i.duration_days, i.stock, i.per_user_limit, i.refund_window_seconds, i.grants_item_definition_id, i.external_role_id, i.listed_at, i.delisted_at, i.created_at,
  (i.listed_at IS NOT NULL AND i.listed_at <= now()
   AND (i.delisted_at IS NULL OR i.delisted_at > now()))::bool AS is_listed
FROM platform.shop_items i
WHERE i.public_id = $1
`

type GetShopItemForPurchaseRow struct {
	ID                     int64
	PublicID               string
	Name                   string
	Description            *string
	Fulfillment            string
	Currency               string
	Price                  int64
	DurationDays           *int32
	Stock                  *int32
	PerUserLimit           *int32
	RefundWindowSeconds    int32
	GrantsItemDefinitionID *int64
	ExternalRoleID         *string
	ListedAt               *time.Time
	DelistedAt             *time.Time
	CreatedAt              time.Time
	IsListed               bool
}

// is_listed 用 DB 時鐘計算(單一時鐘來源):listed_at 非空且已到、delisted_at 空或未到。
func (q *Queries) GetShopItemForPurchase(ctx context.Context, publicID string) (GetShopItemForPurchaseRow, error) {
	row := q.db.QueryRow(ctx, getShopItemForPurchase, publicID)
	var i GetShopItemForPurchaseRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Description,
		&i.Fulfillment,
		&i.Currency,
		&i.Price,
		&i.DurationDays,
		&i.Stock,
		&i.PerUserLimit,
		&i.RefundWindowSeconds,
		&i.GrantsItemDefinitionID,
		&i.ExternalRoleID,
		&i.ListedAt,
		&i.DelistedAt,
		&i.CreatedAt,
		&i.IsListed,
	)
	return i, err
}

const insertEntitlement = `-- name: InsertEntitlement :one
INSERT INTO platform.entitlements (user_id, item_id, expires_at, refundable_until)
VALUES (
  $1, $2,
  CASE WHEN $3::int IS NULL THEN NULL
       ELSE now() + make_interval(days => $3::int) END,
  CASE WHEN $4::int <= 0 THEN NULL
       ELSE now() + make_interval(secs => $4::int) END
)
RETURNING id, user_id, item_id, granted_at, expires_at, refundable_until, revoked_at
`

type InsertEntitlementParams struct {
	UserID              int64
	ItemID              int64
	DurationDays        *int32
	RefundWindowSeconds int32
}

// expires_at / refundable_until 在購買當下用 DB 時鐘算好「存欄位」
// (schemas/08:窗口逐商品調,存值不現算)。
// duration_days NULL → expires_at NULL = 永久;refund_window_seconds <= 0 → NULL = 不可退。
func (q *Queries) InsertEntitlement(ctx context.Context, arg InsertEntitlementParams) (PlatformEntitlement, error) {
	row := q.db.QueryRow(ctx, insertEntitlement,
		arg.UserID,
		arg.ItemID,
		arg.DurationDays,
		arg.RefundWindowSeconds,
	)
	var i PlatformEntitlement
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemID,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.RefundableUntil,
		&i.RevokedAt,
	)
	return i, err
}

const insertRedemption = `-- name: InsertRedemption :one
INSERT INTO platform.redemptions (public_id, user_id, item_id)
VALUES ($1, $2, $3)
RETURNING id, public_id, user_id, item_id, status, note, handled_by, handled_at, created_at
`

type InsertRedemptionParams struct {
	PublicID string
	UserID   int64
	ItemID   int64
}

func (q *Queries) InsertRedemption(ctx context.Context, arg InsertRedemptionParams) (PlatformRedemption, error) {
	row := q.db.QueryRow(ctx, insertRedemption, arg.PublicID, arg.UserID, arg.ItemID)
	var i PlatformRedemption
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.ItemID,
		&i.Status,
		&i.Note,
		&i.HandledBy,
		&i.HandledAt,
		&i.CreatedAt,
	)
	return i, err
}

const lockEntitlementForRefund = `-- name: LockEntitlementForRefund :one
SELECT e.id, e.user_id, e.item_id, e.granted_at, e.expires_at, e.refundable_until, e.revoked_at,
       i.public_id AS item_public_id,
       now()::timestamptz AS db_now
FROM platform.entitlements e
JOIN platform.shop_items i ON i.id = e.item_id
WHERE e.id = $1
FOR UPDATE OF e
`

type LockEntitlementForRefundRow struct {
	ID              int64
	UserID          int64
	ItemID          int64
	GrantedAt       time.Time
	ExpiresAt       *time.Time
	RefundableUntil *time.Time
	RevokedAt       *time.Time
	ItemPublicID    string
	DbNow           time.Time
}

// FOR UPDATE OF e:只鎖權益列(同一權益的退款串行化),不鎖共享讀的商品列。
// db_now 一併回傳:退款窗口比對用 DB 時鐘,避免 app/DB 時鐘偏移誤判(同 outbox 的教訓)。
func (q *Queries) LockEntitlementForRefund(ctx context.Context, id int64) (LockEntitlementForRefundRow, error) {
	row := q.db.QueryRow(ctx, lockEntitlementForRefund, id)
	var i LockEntitlementForRefundRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemID,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.RefundableUntil,
		&i.RevokedAt,
		&i.ItemPublicID,
		&i.DbNow,
	)
	return i, err
}

const lockRedemptionForHandle = `-- name: LockRedemptionForHandle :one
SELECT r.id, r.public_id, r.user_id, r.item_id, r.status, r.note, r.created_at,
       i.public_id AS item_public_id
FROM platform.redemptions r
JOIN platform.shop_items i ON i.id = r.item_id
WHERE r.id = $1
FOR UPDATE OF r
`

type LockRedemptionForHandleRow struct {
	ID           int64
	PublicID     string
	UserID       int64
	ItemID       int64
	Status       string
	Note         *string
	CreatedAt    time.Time
	ItemPublicID string
}

// FOR UPDATE OF r:同一工單的 approve / reject / cancel 串行化,
// 後到者看到非 pending 即拒絕(狀態機單向)。
func (q *Queries) LockRedemptionForHandle(ctx context.Context, id int64) (LockRedemptionForHandleRow, error) {
	row := q.db.QueryRow(ctx, lockRedemptionForHandle, id)
	var i LockRedemptionForHandleRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.ItemID,
		&i.Status,
		&i.Note,
		&i.CreatedAt,
		&i.ItemPublicID,
	)
	return i, err
}

const lockUserForShop = `-- name: LockUserForShop :one

SELECT id FROM platform.users
WHERE id = $1 AND deleted_at IS NULL
FOR UPDATE
`

// 商店 query(schemas/08-shop.md)。動錢一律經 ledger(shoppg 用 ApplyInTx 同 tx 綁定),
// 這裡只有商品 / 權益 / 工單側的讀寫;token_entries 僅有 SELECT(append-only 鐵則)。
// 同一使用者的購買以 users 列鎖串行化:per_user_limit 計數與 API 冪等鍵的重放判定,
// 都必須在「前一筆購買 commit 之後」才有意義(READ COMMITTED 下先讀後寫會踩到舊快照)。
// 鎖序:users → user_balances(與 dailypg 同向,不會與帳本互鎖)。
func (q *Queries) LockUserForShop(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockUserForShop, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const revokeEntitlement = `-- name: RevokeEntitlement :one
UPDATE platform.entitlements SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
RETURNING revoked_at
`

// 呼叫前必須已 LockEntitlementForRefund 且確認 revoked_at IS NULL。
func (q *Queries) RevokeEntitlement(ctx context.Context, id int64) (*time.Time, error) {
	row := q.db.QueryRow(ctx, revokeEntitlement, id)
	var revoked_at *time.Time
	err := row.Scan(&revoked_at)
	return revoked_at, err
}

const updateRedemptionStatus = `-- name: UpdateRedemptionStatus :one
UPDATE platform.redemptions
SET status = $1,
    note = COALESCE($2::text, note),
    handled_by = $3,
    handled_at = now()
WHERE id = $4
RETURNING id, public_id, user_id, item_id, status, note, handled_by, handled_at, created_at
`

type UpdateRedemptionStatusParams struct {
	Status    string
	Note      *string
	HandledBy *int64
	ID        int64
}

// 呼叫前必須已 LockRedemptionForHandle 且確認 status='pending'。
func (q *Queries) UpdateRedemptionStatus(ctx context.Context, arg UpdateRedemptionStatusParams) (PlatformRedemption, error) {
	row := q.db.QueryRow(ctx, updateRedemptionStatus,
		arg.Status,
		arg.Note,
		arg.HandledBy,
		arg.ID,
	)
	var i PlatformRedemption
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.ItemID,
		&i.Status,
		&i.Note,
		&i.HandledBy,
		&i.HandledAt,
		&i.CreatedAt,
	)
	return i, err
}
