// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"
)

const createIdentity = `-- name: CreateIdentity :one
INSERT INTO platform.identities
  (user_id, provider, provider_user_id, username, access_token_enc, refresh_token_enc, scope, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, provider, provider_user_id, username, access_token_enc, refresh_token_enc, scope, expires_at, linked_at
`

type CreateIdentityParams struct {
	UserID          int64
	Provider        string
	ProviderUserID  string
	Username        *string
	AccessTokenEnc  []byte
	RefreshTokenEnc []byte
	Scope           *string
	ExpiresAt       *time.Time
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (PlatformIdentity, error) {
	row := q.db.QueryRow(ctx, createIdentity,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.Username,
		arg.AccessTokenEnc,
		arg.RefreshTokenEnc,
		arg.Scope,
		arg.ExpiresAt,
	)
	var i PlatformIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Username,
		&i.AccessTokenEnc,
		&i.RefreshTokenEnc,
		&i.Scope,
		&i.ExpiresAt,
		&i.LinkedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO platform.users (public_id, display_name, avatar_url)
VALUES ($1, $2, $3)
RETURNING id, public_id, display_name, avatar_url, timezone, timezone_changed_at, email, created_at, last_seen_at, deleted_at
`

type CreateUserParams struct {
	PublicID    string
	DisplayName *string
	AvatarUrl   *string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (PlatformUser, error) {
	row := q.db.QueryRow(ctx, createUser, arg.PublicID, arg.DisplayName, arg.AvatarUrl)
	var i PlatformUser
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.TimezoneChangedAt,
		&i.Email,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, public_id, display_name, avatar_url, timezone, timezone_changed_at, email, created_at, last_seen_at, deleted_at FROM platform.users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (PlatformUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i PlatformUser
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.TimezoneChangedAt,
		&i.Email,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByIdentity = `-- name: GetUserByIdentity :one
SELECT u.id, u.public_id, u.display_name, u.avatar_url, u.timezone, u.timezone_changed_at, u.email, u.created_at, u.last_seen_at, u.deleted_at FROM platform.users u
JOIN platform.identities i ON i.user_id = u.id
WHERE i.provider = $1 AND i.provider_user_id = $2 AND u.deleted_at IS NULL
`

type GetUserByIdentityParams struct {
	Provider       string
	ProviderUserID string
}

func (q *Queries) GetUserByIdentity(ctx context.Context, arg GetUserByIdentityParams) (PlatformUser, error) {
	row := q.db.QueryRow(ctx, getUserByIdentity, arg.Provider, arg.ProviderUserID)
	var i PlatformUser
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.TimezoneChangedAt,
		&i.Email,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByPublicID = `-- name: GetUserByPublicID :one
SELECT id, public_id, display_name, avatar_url, timezone, timezone_changed_at, email, created_at, last_seen_at, deleted_at FROM platform.users WHERE public_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByPublicID(ctx context.Context, publicID string) (PlatformUser, error) {
	row := q.db.QueryRow(ctx, getUserByPublicID, publicID)
	var i PlatformUser
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.TimezoneChangedAt,
		&i.Email,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.DeletedAt,
	)
	return i, err
}

const touchUserLastSeen = `-- name: TouchUserLastSeen :exec
UPDATE platform.users SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) TouchUserLastSeen(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchUserLastSeen, id)
	return err
}

const updateIdentityTokens = `-- name: UpdateIdentityTokens :exec
UPDATE platform.identities
SET access_token_enc = $2, refresh_token_enc = $3, scope = $4, expires_at = $5
WHERE id = $1
`

type UpdateIdentityTokensParams struct {
	ID              int64
	AccessTokenEnc  []byte
	RefreshTokenEnc []byte
	Scope           *string
	ExpiresAt       *time.Time
}

func (q *Queries) UpdateIdentityTokens(ctx context.Context, arg UpdateIdentityTokensParams) error {
	_, err := q.db.Exec(ctx, updateIdentityTokens,
		arg.ID,
		arg.AccessTokenEnc,
		arg.RefreshTokenEnc,
		arg.Scope,
		arg.ExpiresAt,
	)
	return err
}

const updateUserTimezone = `-- name: UpdateUserTimezone :one
UPDATE platform.users
SET timezone = $2, timezone_changed_at = now()
WHERE id = $1
RETURNING timezone, timezone_changed_at
`

type UpdateUserTimezoneParams struct {
	ID       int64
	Timezone string
}

type UpdateUserTimezoneRow struct {
	Timezone          string
	TimezoneChangedAt *time.Time
}

func (q *Queries) UpdateUserTimezone(ctx context.Context, arg UpdateUserTimezoneParams) (UpdateUserTimezoneRow, error) {
	row := q.db.QueryRow(ctx, updateUserTimezone, arg.ID, arg.Timezone)
	var i UpdateUserTimezoneRow
	err := row.Scan(&i.Timezone, &i.TimezoneChangedAt)
	return i, err
}
