// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: xp.sql

package db

import (
	"context"
	"time"
)

const addUserXp = `-- name: AddUserXp :one
UPDATE platform.user_xp
SET xp = xp + $3, last_xp_at = now(), updated_at = now()
WHERE user_id = $1 AND community_id = $2
RETURNING xp
`

type AddUserXpParams struct {
	UserID      int64
	CommunityID int64
	Xp          int64
}

// 與 InsertXpEvent 同 tx;now() 為 tx 時間,與事件的 created_at 同值。
// level 不動:M1 曲線未上線,恆 0(schemas/06)
func (q *Queries) AddUserXp(ctx context.Context, arg AddUserXpParams) (int64, error) {
	row := q.db.QueryRow(ctx, addUserXp, arg.UserID, arg.CommunityID, arg.Xp)
	var xp int64
	err := row.Scan(&xp)
	return xp, err
}

const ensureUserXpRow = `-- name: EnsureUserXpRow :exec
INSERT INTO platform.user_xp (user_id, community_id)
VALUES ($1, $2)
ON CONFLICT (user_id, community_id) DO NOTHING
`

type EnsureUserXpRowParams struct {
	UserID      int64
	CommunityID int64
}

// 與 EnsureBalanceRow 同模式:先保證投影列存在,才能 FOR UPDATE 串行化同 user 的併發入帳
func (q *Queries) EnsureUserXpRow(ctx context.Context, arg EnsureUserXpRowParams) error {
	_, err := q.db.Exec(ctx, ensureUserXpRow, arg.UserID, arg.CommunityID)
	return err
}

const getCommunityXpConfig = `-- name: GetCommunityXpConfig :one
SELECT r.config
FROM platform.communities c
LEFT JOIN platform.xp_rulesets r ON r.id = c.xp_ruleset_id
WHERE c.id = $1
`

// LEFT JOIN:community 存在但 xp_ruleset_id 為 NULL(M1 可能還沒建 ruleset)時
// 回 NULL config,呼叫端採安全預設(無冷卻、無 cap);community 不存在 → 無列(ErrNoRows)
func (q *Queries) GetCommunityXpConfig(ctx context.Context, id int64) ([]byte, error) {
	row := q.db.QueryRow(ctx, getCommunityXpConfig, id)
	var config []byte
	err := row.Scan(&config)
	return config, err
}

const getXpEventType = `-- name: GetXpEventType :one

SELECT key, enabled FROM platform.xp_event_types WHERE key = $1
`

type GetXpEventTypeRow struct {
	Key     string
	Enabled bool
}

// XP query。設計依 schemas/06(含增補 E)與 schemas/01 增補 A:
// xp_events 是事實、user_xp 是投影(必可重算)、XP 不進帳本不經 Ledger(刻意設計,
// XP 錯了重算即可,沒有對帳需求;混進帳本會淹沒金流稽核)。
// 冷卻用 user_xp.last_xp_at 直接查 DB(schemas/06:不上 Redis)。
// source 檢查:registry 管「存在與開關」(全域);數值/冷卻/上限在 xp_rulesets.config
func (q *Queries) GetXpEventType(ctx context.Context, key string) (GetXpEventTypeRow, error) {
	row := q.db.QueryRow(ctx, getXpEventType, key)
	var i GetXpEventTypeRow
	err := row.Scan(&i.Key, &i.Enabled)
	return i, err
}

const insertXpEvent = `-- name: InsertXpEvent :one
INSERT INTO platform.xp_events (user_id, community_id, space_id, source, amount, ref_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_at
`

type InsertXpEventParams struct {
	UserID      int64
	CommunityID int64
	SpaceID     *int64
	Source      string
	Amount      int64
	RefID       *string
}

type InsertXpEventRow struct {
	ID        int64
	CreatedAt time.Time
}

func (q *Queries) InsertXpEvent(ctx context.Context, arg InsertXpEventParams) (InsertXpEventRow, error) {
	row := q.db.QueryRow(ctx, insertXpEvent,
		arg.UserID,
		arg.CommunityID,
		arg.SpaceID,
		arg.Source,
		arg.Amount,
		arg.RefID,
	)
	var i InsertXpEventRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const lastXpEventAtBySource = `-- name: LastXpEventAtBySource :one
SELECT created_at FROM platform.xp_events
WHERE user_id = $1 AND community_id = $2 AND source = $3
ORDER BY created_at DESC
LIMIT 1
`

type LastXpEventAtBySourceParams struct {
	UserID      int64
	CommunityID int64
	Source      string
}

// 冷卻計時器:該 (user, community, source) 最近一筆事件的時間。
// 不用 user_xp.last_xp_at 當計時器 —— 它是「最後任何入帳」的跨 source 資訊欄位,
// 拿來計時會讓 voice 高頻入帳餓死 message 的冷卻、admin 修正也會重置計時(QA 中1)。
// 無列(ErrNoRows)= 該 source 從未入帳 = 無冷卻。呼叫前必須已 LockUserXp(串行化)
func (q *Queries) LastXpEventAtBySource(ctx context.Context, arg LastXpEventAtBySourceParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, lastXpEventAtBySource, arg.UserID, arg.CommunityID, arg.Source)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const lockUserXp = `-- name: LockUserXp :one
SELECT xp, now()::timestamptz AS db_now
FROM platform.user_xp
WHERE user_id = $1 AND community_id = $2
FOR UPDATE
`

type LockUserXpParams struct {
	UserID      int64
	CommunityID int64
}

type LockUserXpRow struct {
	Xp    int64
	DbNow time.Time
}

// 一併回 DB 時鐘:冷卻比較的兩端(事件時間與 now)都用 DB 時鐘,
// 單一時鐘來源,app/DB 時鐘偏移不影響判斷
func (q *Queries) LockUserXp(ctx context.Context, arg LockUserXpParams) (LockUserXpRow, error) {
	row := q.db.QueryRow(ctx, lockUserXp, arg.UserID, arg.CommunityID)
	var i LockUserXpRow
	err := row.Scan(&i.Xp, &i.DbNow)
	return i, err
}

const rebuildUserXp = `-- name: RebuildUserXp :one
UPDATE platform.user_xp u
SET xp = s.total, last_xp_at = s.last_at, updated_at = now()
FROM (
  SELECT COALESCE(SUM(amount), 0)::bigint AS total, MAX(created_at) AS last_at
  FROM platform.xp_events
  WHERE user_id = $1 AND community_id = $2
) s
WHERE u.user_id = $1 AND u.community_id = $2
RETURNING u.xp
`

type RebuildUserXpParams struct {
	UserID      int64
	CommunityID int64
}

// 投影重算:xp ← SUM(events)、last_xp_at ← MAX(created_at),整個投影可從事實重建。
// 呼叫前必須已 LockUserXp,否則與並行 Award 有覆寫競態(先算 SUM、後拿鎖會蓋掉新事件)
func (q *Queries) RebuildUserXp(ctx context.Context, arg RebuildUserXpParams) (int64, error) {
	row := q.db.QueryRow(ctx, rebuildUserXp, arg.UserID, arg.CommunityID)
	var xp int64
	err := row.Scan(&xp)
	return xp, err
}

const sumXpTodayBySource = `-- name: SumXpTodayBySource :one
SELECT COALESCE(SUM(amount), 0)::bigint AS total
FROM platform.xp_events
WHERE user_id = $1 AND community_id = $2 AND source = $3
  AND created_at >= date_trunc('day', now() AT TIME ZONE 'UTC') AT TIME ZONE 'UTC'
`

type SumXpTodayBySourceParams struct {
	UserID      int64
	CommunityID int64
	Source      string
}

// daily_cap 判斷:UTC 當日該 user 該 community 該 source 的總和(schemas/01 A)。
// 呼叫前必須已 LockUserXp,同 user 的併發入帳已串行化,SUM 不會低估
func (q *Queries) SumXpTodayBySource(ctx context.Context, arg SumXpTodayBySourceParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumXpTodayBySource, arg.UserID, arg.CommunityID, arg.Source)
	var total int64
	err := row.Scan(&total)
	return total, err
}
